/*
 * Copyright 2015-2020 CNRS-UM LIRMM, CNRS-AIST JRL
 */

#pragma once

#include <string>

namespace mc_rtc
{

constexpr auto JVRC_DESCRIPTION_PATH = "${JVRC_DESCRIPTION_PATH}";
constexpr auto MC_ENV_DESCRIPTION_PATH = "${MC_ENV_DESCRIPTION_PATH}";
constexpr auto MC_INT_OBJ_DESCRIPTION_PATH = "${MC_INT_OBJ_DESCRIPTION_PATH}";
constexpr auto INSTALL_PREFIX = "${MC_RTC_INSTALL_PREFIX}/";
constexpr auto MC_ROBOTS_INSTALL_PREFIX = "${MC_ROBOTS_RUNTIME_DESTINATION_PREFIX}/";
constexpr auto MC_OBSERVERS_INSTALL_PREFIX = "${MC_OBSERVERS_RUNTIME_DESTINATION_PREFIX}/";
constexpr auto MC_CONTROLLER_INSTALL_PREFIX = "${MC_CONTROLLER_RUNTIME_DESTINATION_PREFIX}/";
constexpr auto MC_PLUGINS_INSTALL_PREFIX = "${MC_PLUGINS_RUNTIME_DESTINATION_PREFIX}";
constexpr auto DATA_PATH = "${CMAKE_INSTALL_PREFIX}/share/mc_rtc/";
constexpr auto CONF_PATH = "${CMAKE_INSTALL_PREFIX}/etc/mc_rtc.yaml";
constexpr bool MC_RTC_SUPPORT_ROS = ${MC_RTC_HAS_ROS_SUPPORT};
constexpr auto JSON_SCHEMA_PATH = "${MC_RTC_JSON_SCHEMA_PATH}/";
constexpr bool MC_RTC_BUILD_IN_NIX = "${MC_RTC_BUILD_IN_NIX}";
} // namespace mc_rtc
