# distutils: language = c++

cimport mc_rtc.c_mc_rtc as c_mc_rtc

MC_ENV_DESCRIPTION_PATH = c_mc_rtc.MC_ENV_DESCRIPTION_PATH
HRP2_DRC_DESCRIPTION_PATH = c_mc_rtc.HRP2_DRC_DESCRIPTION_PATH
HRP4_DESCRIPTION_PATH = c_mc_rtc.HRP4_DESCRIPTION_PATH
INSTALL_PREFIX = c_mc_rtc.INSTALL_PREFIX
MC_ROBOTS_INSTALL_PREFIX = c_mc_rtc.MC_ROBOTS_INSTALL_PREFIX
MC_CONTROLLER_INSTALL_PREFIX = c_mc_rtc.MC_CONTROLLER_INSTALL_PREFIX
DATA_PATH = c_mc_rtc.DATA_PATH
CONF_PATH = c_mc_rtc.CONF_PATH
