#ifndef _H_MCRBDYNSTANCE_H_
#define _H_MCRBDYNSTANCE_H_

#include <mc_rbdyn/Contact.h>

namespace mc_rbdyn
{

struct Robot;

struct StanceImpl;

struct Stance
{
public:
  static unsigned int nrConeGen;
  static double defaultFriction;
  static unsigned int nrBilatPoints;
public:
  Stance(const std::vector< std::vector<double> > & q, const std::vector<Contact> & geomContacts, const std::vector<Contact> stabContacts);

  ~Stance();

  /* Allow move operations to work on Stance vectors */
  Stance(Stance &&) = default;
  Stance& operator=(Stance&&) = default;

  const std::vector<Contact> & contacts() const;

  const std::vector< std::vector<double> > q() const;

  const std::vector<Contact> & geomContacts() const;

  const std::vector<Contact> & stabContacts() const;

  void updateContact(const Contact & oldContact, const Contact & newContact);

  Eigen::Vector3d com(const Robot & robot) const;

  std::vector<std::string> robotSurfacesInContact();
public:
  std::unique_ptr<StanceImpl> impl;
};

typedef std::pair<std::vector<Contact>, std::vector<Contact> > contact_vector_pair_t;
typedef std::pair< contact_vector_pair_t, contact_vector_pair_t > apply_return_t;

struct StanceAction
{
  virtual apply_return_t apply(const Stance & stance) = 0;

  virtual void update(const Stance & stance) = 0;

  virtual std::string toStr() = 0;

  virtual std::string type() = 0;
};

struct IdentityContactAction : public StanceAction
{
public:
  virtual apply_return_t apply(const Stance & stance) override;

  virtual void update(const Stance & stance) override;

  virtual std::string toStr() override;

  virtual std::string type() override;
};

struct AddContactAction : public StanceAction
{
public:
  AddContactAction(const Contact & contact);

  virtual apply_return_t apply(const Stance & stance) override;

  virtual void update(const Stance & stance) override;

  virtual std::string toStr() override;

  virtual std::string type() override;
public:
  Contact contact;
};

struct RemoveContactAction : public StanceAction
{
public:
  RemoveContactAction(const Contact & contact);

  virtual apply_return_t apply(const Stance & stance) override;

  virtual void update(const Stance & stance) override;

  virtual std::string toStr() override;

  virtual std::string type() override;
public:
  Contact contact;
};

/*FIXME Need a python util to convert stance files generated by python into something readable by the C++ counterpart */

void loadStances(const std::string & filename, std::vector<Stance> & stances, std::vector< std::shared_ptr<StanceAction> > & actions);

void saveStances(const std::string & filename, std::vector<Stance> & stances, std::vector< std::shared_ptr<StanceAction> > & actions);

void saveStancesJSON(const std::string & filename, std::vector<Stance> & stances, std::vector< std::shared_ptr<StanceAction> > & actions);

}

#endif
