# DO NOT EDIT THIS FILE!
#
# Python module OpenHRP generated by omniidl

import omniORB
omniORB.updateModule("OpenHRP")

# ** 1. Stub files contributing to this module
import MCControlService_idl

# ** 2. Sub-modules

# ** 3. End
