mc_rtc::gui Namespace Reference
mc_rtc::gui Namespace Reference
Namespaces
details
plot
Classes
struct ArrayInputImpl
ArrayInput should display an array (.
struct ArrayLabelImpl
ArrayLabel should display data in an array form.
struct ArrowConfig
struct ArrowImpl
struct ArrowROImpl
Arrow should display an arrow from the point at the start to the point at the end.
struct ButtonImpl
Button should provide a clickable button.
struct CallbackElement
A generic element to handle request from the client.
struct CheckboxImpl
Checkbox display a toggable checkbox.
struct Color
struct ComboInputImpl
ComboInput should display a combo box with the set of choices provided by values.
struct CommonInputImpl
Saves typing for the most common case.
struct DataComboInputImpl
DataComboInput should behave like ComboInput but the data source is stored in the GUI data store.
struct DataElement
A generic element to write data to the GUI.
struct Element
Element is the common class for every element's type available in the GUI.
struct ForceConfig
struct ForceImpl
struct ForceROImpl
Force should display a force vector in 3D environment.
struct FormArrayInput
struct FormComboInput
struct FormDataComboInput
struct FormDataInput
struct FormElement
struct FormImpl
Create a user-defined form.
struct IntegerInputImpl
This element should implement a dialog to input an integer.
struct LabelImpl
Label should display data.
struct LineConfig
struct NumberInputImpl
This element should implement a dialog to input a number.
struct NumberSliderImpl
NumberSlider should display a number slider with minimum and maximum values specified.
struct Point3DImpl
Point3D should display a 3D point in the environment.
struct Point3DROImpl
Point3D should display a 3D point in the environment.
struct PointConfig
struct PolygonImpl
Polygon should display a polygon or a set of polygons.
struct RotationImpl
Rotation display a widget that shows the rotation.
struct RotationROImpl
Rotation display a widget that shows the rotation.
struct SchemaImpl
Should display a form using the data provided in the configured schema folder.
struct StateBuilder
Used to build a GUI state from multiple objects.
struct StringInputImpl
This element should implement a dialog to input a string.
struct TrajectoryImpl
Trajectory can represent a pre-defined trajectory or a real-time trajectory depending on type of data returned by the callback.
struct TransformImpl
Transform display a widget that shows a 6D frame.
struct TransformROImpl
Transform display a widget that shows a 6D frame.
struct VoidCallbackElement
A generic element to handle request from the client when no data is required.
struct XYThetaImpl
An XYTheta element represents an oriented point in the XY plane.
struct XYThetaROImpl
An XYTheta element represents an oriented point in the XY plane.
Typedefs
using FormCheckbox = FormDataInput< bool, Elements::Checkbox >
using FormIntegerInput = FormDataInput< int, Elements::IntegerInput >
using FormNumberInput = FormDataInput< double, Elements::NumberInput >
using FormStringInput = FormDataInput< std::string, Elements::StringInput >
Enumerations
enum Elements {
Elements::Label = 0,
Elements::ArrayLabel,
Elements::Button,
Elements::Checkbox,
Elements::StringInput,
Elements::IntegerInput,
Elements::NumberInput,
Elements::NumberSlider,
Elements::ArrayInput,
Elements::ComboInput,
Elements::DataComboInput,
Elements::Point3D,
Elements::Trajectory,
Elements::Rotation,
Elements::Transform,
Elements::Schema,
Elements::Form,
Elements::Polygon,
Elements::Force,
Elements::Arrow,
Elements::XYTheta,
Elements::Table
}
An enumeration of available elements.
enum ElementsStacking {
ElementsStacking::Vertical = 0,
ElementsStacking::Horizontal
}
Describe elements stacking policy for the client.
enum LineStyle {
LineStyle::Solid,
LineStyle::Dotted
}
Functions
template<typename GetT , typename SetT >
ArrayInputImpl< GetT, SetT > ArrayInput (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create an ArrayInput element (no labels)
template<typename GetT , typename SetT >
ArrayInputImpl< GetT, SetT > ArrayInput (const std::string &name, const std::vector< std::string > &labels, GetT get_fn, SetT set_fn)
Helper function to create an ArrayInput element (with labels)
template<typename GetT >
ArrayLabelImpl< GetT > ArrayLabel (const std::string &name, GetT get_fn)
Helper function to build an ArrayLabelImpl (no labels)
template<typename GetT >
ArrayLabelImpl< GetT > ArrayLabel (const std::string &name, const std::vector< std::string > &labels, GetT get_fn)
Helper function to build an ArrayLabelImpl (with labels)
template<typename GetStart , typename GetEnd >
ArrowROImpl< GetStart, GetEnd > Arrow (const std::string &name, GetStart get_start_fn, GetEnd get_end_fn)
Helper function to create an ArrowImpl.
template<typename GetStart , typename GetEnd >
ArrowROImpl< GetStart, GetEnd > Arrow (const std::string &name, const ArrowConfig &config, GetStart get_start_fn, GetEnd get_end_fn)
Helper function to create an ArrowImpl.
template<typename GetStart , typename SetStart , typename GetEnd , typename SetEnd >
ArrowImpl< GetStart, SetStart, GetEnd, SetEnd > Arrow (const std::string &name, GetStart get_start_fn, SetStart set_start_fn, GetEnd get_end_fn, SetEnd set_end_fn)
template<typename GetStart , typename SetStart , typename GetEnd , typename SetEnd >
ArrowImpl< GetStart, SetStart, GetEnd, SetEnd > Arrow (const std::string &name, const ArrowConfig &config, GetStart get_start_fn, SetStart set_start_fn, GetEnd get_end_fn, SetEnd set_end_fn)
template<typename Callback >
ButtonImpl< Callback > Button (const std::string &name, Callback cb)
Helper function to create a ButtonImpl.
template<typename GetT , typename Callback >
CheckboxImpl< GetT, Callback > Checkbox (const std::string &name, GetT get_fn, Callback cb)
Helper function to create a Checkbox.
template<typename GetT , typename SetT >
ComboInputImpl< GetT, SetT > ComboInput (const std::string &name, const std::vector< std::string > &values, GetT get_fn, SetT set_fn)
Helper function to create a ComboInputImpl.
template<typename GetT , typename SetT >
DataComboInputImpl< GetT, SetT > DataComboInput (const std::string &name, const std::vector< std::string > &values, GetT get_fn, SetT set_fn)
Helper function to build a DataComboInputImpl.
template<typename GetForce , typename GetSurface >
ForceROImpl< GetForce, GetSurface > Force (const std::string &name, GetForce get_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
template<typename GetForce , typename GetSurface >
ForceROImpl< GetForce, GetSurface > Force (const std::string &name, const ForceConfig &config, GetForce get_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
template<typename GetForce , typename GetSurface , typename SetForce >
ForceImpl< GetForce, GetSurface, SetForce > Force (const std::string &name, GetForce get_force_fn, SetForce set_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
template<typename GetForce , typename GetSurface , typename SetForce >
ForceImpl< GetForce, GetSurface, SetForce > Force (const std::string &name, const ForceConfig &config, GetForce get_force_fn, SetForce set_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
template<typename Callback , typename... Args>
FormImpl< Callback > Form (const std::string &name, Callback cb, Args &&... args)
Helper to create a Form element.
template<typename GetT , typename SetT >
IntegerInputImpl< GetT, SetT > IntegerInput (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create a IntegerInputImpl.
template<typename GetT >
LabelImpl< GetT > Label (const std::string &name, GetT get_fn)
Helper function to create a Label element.
template<typename GetT , typename SetT >
NumberInputImpl< GetT, SetT > NumberInput (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create a NumberInputImpl.
template<typename GetT , typename SetT >
NumberSliderImpl< GetT, SetT > NumberSlider (const std::string &name, GetT get_fn, SetT set_fn, double min, double max)
Helper function to create a NumberSliderImpl.
template<typename GetT >
Point3DROImpl< GetT > Point3D (const std::string &name, GetT get_fn)
Helper function to create a Point3DROImpl.
template<typename GetT , typename SetT >
Point3DImpl< GetT, SetT > Point3D (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create a Point3DImpl.
template<typename GetT >
Point3DROImpl< GetT > Point3D (const std::string &name, const PointConfig &config, GetT get_fn)
Helper function to create a Point3DROImpl with configuration.
template<typename GetT , typename SetT >
Point3DImpl< GetT, SetT > Point3D (const std::string &name, const PointConfig &config, GetT get_fn, SetT set_fn)
Helper function to create a Point3DImpl with configuration.
template<typename GetT >
PolygonImpl< GetT > Polygon (const std::string &name, GetT get_fn)
Helper function to build a PolygonImpl.
template<typename GetT >
PolygonImpl< GetT > Polygon (const std::string &name, const Color &color, GetT get_fn)
Helper function to build a PolygonImpl.
template<typename GetT >
RotationROImpl< GetT > Rotation (const std::string &name, GetT get_fn)
Helper function to create a Rotation element (read-only)
template<typename GetT , typename SetT >
RotationImpl< GetT, SetT > Rotation (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create a Rotation element (writable)
template<typename Callback >
SchemaImpl< Callback > Schema (const std::string &name, const std::string &schema, Callback cb)
Helper function to create a Schema element.
template<typename GetT , typename SetT >
StringInputImpl< GetT, SetT > StringInput (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create a StringInputImpl.
template<typename GetData >
details::StaticTableImpl< GetData > Table (const std::string &name, std::vector< std::string > header, GetData get_data_fn)
Helper function to a get a StaticTableImpl.
template<typename GetData >
details::StaticTableImpl< GetData > Table (const std::string &name, std::vector< std::string > header, std::vector< std::string > format, GetData get_data_fn)
Helper function to a get a StaticTableImpl with format.
template<typename GetHeader , typename GetData >
details::TableImpl< GetHeader, GetData > Table (const std::string &name, GetHeader get_header_fn, GetData get_data_fn)
Helper function to get a TableImpl.
template<typename GetHeader , typename GetFormat , typename GetData >
details::FormattedTableImpl< GetHeader, GetFormat, GetData > Table (const std::string &name, GetHeader get_header_fn, GetFormat get_format_fn, GetData get_data_fn)
Helper function to get a FormattedTableImpl.
template<typename GetT >
TrajectoryImpl< GetT > Trajectory (const std::string &name, GetT get_fn)
Function helper to get a TrajectoryImpl.
template<typename GetT >
TrajectoryImpl< GetT > Trajectory (const std::string &name, const LineConfig &config, GetT get_fn)
Function helper to get a TrajectoryImpl.
template<typename GetT >
TransformROImpl< GetT > Transform (const std::string &name, GetT get_fn)
Helper function to create a Transform element (read-only)
template<typename GetT , typename SetT >
TransformImpl< GetT, SetT > Transform (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create a Transform element (editable)
template<typename GetT >
XYThetaROImpl< GetT > XYTheta (const std::string &name, GetT get_fn)
Helper function to create an XYTheta element (read-only)
template<typename GetT , typename SetT >
XYThetaImpl< GetT, SetT > XYTheta (const std::string &name, GetT get_fn, SetT set_fn)
Helper function to create an XYTheta element.
Typedef Documentation
FormCheckbox
using mc_rtc::gui::FormCheckbox = typedef FormDataInput<bool, Elements::Checkbox>
FormIntegerInput
using mc_rtc::gui::FormIntegerInput = typedef FormDataInput<int, Elements::IntegerInput>
FormNumberInput
using mc_rtc::gui::FormNumberInput = typedef FormDataInput<double, Elements::NumberInput>
FormStringInput
using mc_rtc::gui::FormStringInput = typedef FormDataInput<std::string, Elements::StringInput>
Enumeration Type Documentation
Elements
enum mc_rtc::gui::Elements strong
An enumeration of available elements.
Enumerator
Label
ArrayLabel
Button
Checkbox
StringInput
IntegerInput
NumberInput
NumberSlider
ArrayInput
ComboInput
DataComboInput
Point3D
Trajectory
Rotation
Transform
Schema
Form
Polygon
Force
Arrow
XYTheta
Table
ElementsStacking
enum mc_rtc::gui::ElementsStacking strong
Describe elements stacking policy for the client.
Enumerator
Vertical
Horizontal
LineStyle
enum mc_rtc::gui::LineStyle strong
Enumerator
Solid
Dotted
Function Documentation
ArrayInput() [1/2]
template<typename GetT , typename SetT > ArrayInputImpl<GetT, SetT> mc_rtc::gui::ArrayInput (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create an ArrayInput element (no labels)
References mc_rtc::gui::Element::name().
ArrayInput() [2/2]
template<typename GetT , typename SetT > ArrayInputImpl<GetT, SetT> mc_rtc::gui::ArrayInput (const std::string & name, const std::vector< std::string > & labels, GetT get_fn, SetT set_fn)
Helper function to create an ArrayInput element (with labels)
References mc_rtc::gui::Element::name().
ArrayLabel() [1/2]
template<typename GetT > ArrayLabelImpl<GetT> mc_rtc::gui::ArrayLabel (const std::string & name, GetT get_fn)
Helper function to build an ArrayLabelImpl (no labels)
References mc_rtc::gui::Element::name().
ArrayLabel() [2/2]
template<typename GetT > ArrayLabelImpl<GetT> mc_rtc::gui::ArrayLabel (const std::string & name, const std::vector< std::string > & labels, GetT get_fn)
Helper function to build an ArrayLabelImpl (with labels)
References mc_rtc::gui::Element::name().
Arrow() [1/4]
template<typename GetStart , typename GetEnd > ArrowROImpl<GetStart, GetEnd> mc_rtc::gui::Arrow (const std::string & name, GetStart get_start_fn, GetEnd get_end_fn)
Helper function to create an ArrowImpl.
References mc_rtc::gui::Element::name().
Arrow() [2/4]
template<typename GetStart , typename GetEnd > ArrowROImpl<GetStart, GetEnd> mc_rtc::gui::Arrow (const std::string & name, const ArrowConfig & config, GetStart get_start_fn, GetEnd get_end_fn)
Helper function to create an ArrowImpl.
References mc_rtc::gui::Element::name().
Arrow() [3/4]
template<typename GetStart , typename SetStart , typename GetEnd , typename SetEnd > ArrowImpl<GetStart, SetStart, GetEnd, SetEnd> mc_rtc::gui::Arrow (const std::string & name, GetStart get_start_fn, SetStart set_start_fn, GetEnd get_end_fn, SetEnd set_end_fn)
References mc_rtc::gui::Element::name().
Arrow() [4/4]
template<typename GetStart , typename SetStart , typename GetEnd , typename SetEnd > ArrowImpl<GetStart, SetStart, GetEnd, SetEnd> mc_rtc::gui::Arrow (const std::string & name, const ArrowConfig & config, GetStart get_start_fn, SetStart set_start_fn, GetEnd get_end_fn, SetEnd set_end_fn)
References mc_rtc::gui::Element::name().
Button()
template<typename Callback > ButtonImpl<Callback> mc_rtc::gui::Button (const std::string & name, Callback cb)
Helper function to create a ButtonImpl.
References mc_rtc::gui::Element::name().
Checkbox()
template<typename GetT , typename Callback > CheckboxImpl<GetT, Callback> mc_rtc::gui::Checkbox (const std::string & name, GetT get_fn, Callback cb)
Helper function to create a Checkbox.
References mc_rtc::gui::Element::name().
ComboInput()
template<typename GetT , typename SetT > ComboInputImpl<GetT, SetT> mc_rtc::gui::ComboInput (const std::string & name, const std::vector< std::string > & values, GetT get_fn, SetT set_fn)
Helper function to create a ComboInputImpl.
References mc_rtc::gui::Element::name().
DataComboInput()
template<typename GetT , typename SetT > DataComboInputImpl<GetT, SetT> mc_rtc::gui::DataComboInput (const std::string & name, const std::vector< std::string > & values, GetT get_fn, SetT set_fn)
Helper function to build a DataComboInputImpl.
References mc_rtc::gui::Element::name().
Force() [1/4]
template<typename GetForce , typename GetSurface > ForceROImpl<GetForce, GetSurface> mc_rtc::gui::Force (const std::string & name, GetForce get_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
References mc_rtc::gui::Element::name().
Force() [2/4]
template<typename GetForce , typename GetSurface > ForceROImpl<GetForce, GetSurface> mc_rtc::gui::Force (const std::string & name, const ForceConfig & config, GetForce get_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
References mc_rtc::gui::Element::name().
Force() [3/4]
template<typename GetForce , typename GetSurface , typename SetForce > ForceImpl<GetForce, GetSurface, SetForce> mc_rtc::gui::Force (const std::string & name, GetForce get_force_fn, SetForce set_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
References mc_rtc::gui::Element::name().
Force() [4/4]
template<typename GetForce , typename GetSurface , typename SetForce > ForceImpl<GetForce, GetSurface, SetForce> mc_rtc::gui::Force (const std::string & name, const ForceConfig & config, GetForce get_force_fn, SetForce set_force_fn, GetSurface get_surface_fn)
Helper function to get a ForceImpl.
References mc_rtc::gui::Element::name().
Form()
template<typename Callback , typename... Args> FormImpl<Callback> mc_rtc::gui::Form (const std::string & name, Callback cb, Args &&... args)
Helper to create a Form element.
References mc_rtc::gui::Element::name().
IntegerInput()
template<typename GetT , typename SetT > IntegerInputImpl<GetT, SetT> mc_rtc::gui::IntegerInput (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create a IntegerInputImpl.
References mc_rtc::gui::Element::name().
Label()
template<typename GetT > LabelImpl<GetT> mc_rtc::gui::Label (const std::string & name, GetT get_fn)
Helper function to create a Label element.
References mc_rtc::gui::Element::name().
NumberInput()
template<typename GetT , typename SetT > NumberInputImpl<GetT, SetT> mc_rtc::gui::NumberInput (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create a NumberInputImpl.
References mc_rtc::gui::Element::name().
NumberSlider()
template<typename GetT , typename SetT > NumberSliderImpl<GetT, SetT> mc_rtc::gui::NumberSlider (const std::string & name, GetT get_fn, SetT set_fn, double min, double max)
Helper function to create a NumberSliderImpl.
References mc_rtc::gui::Element::name().
Point3D() [1/4]
template<typename GetT > Point3DROImpl<GetT> mc_rtc::gui::Point3D (const std::string & name, GetT get_fn)
Helper function to create a Point3DROImpl.
References mc_rtc::gui::Element::name().
Point3D() [2/4]
template<typename GetT , typename SetT > Point3DImpl<GetT, SetT> mc_rtc::gui::Point3D (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create a Point3DImpl.
References mc_rtc::gui::Element::name().
Point3D() [3/4]
template<typename GetT > Point3DROImpl<GetT> mc_rtc::gui::Point3D (const std::string & name, const PointConfig & config, GetT get_fn)
Helper function to create a Point3DROImpl with configuration.
References mc_rtc::gui::Element::name().
Point3D() [4/4]
template<typename GetT , typename SetT > Point3DImpl<GetT, SetT> mc_rtc::gui::Point3D (const std::string & name, const PointConfig & config, GetT get_fn, SetT set_fn)
Helper function to create a Point3DImpl with configuration.
References mc_rtc::gui::Element::name().
Polygon() [1/2]
template<typename GetT > PolygonImpl<GetT> mc_rtc::gui::Polygon (const std::string & name, GetT get_fn)
Helper function to build a PolygonImpl.
References mc_rtc::gui::Element::name().
Polygon() [2/2]
template<typename GetT > PolygonImpl<GetT> mc_rtc::gui::Polygon (const std::string & name, const Color & color, GetT get_fn)
Helper function to build a PolygonImpl.
References mc_rtc::gui::Element::name().
Rotation() [1/2]
template<typename GetT > RotationROImpl<GetT> mc_rtc::gui::Rotation (const std::string & name, GetT get_fn)
Helper function to create a Rotation element (read-only)
References mc_rtc::gui::Element::name().
Rotation() [2/2]
template<typename GetT , typename SetT > RotationImpl<GetT, SetT> mc_rtc::gui::Rotation (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create a Rotation element (writable)
References mc_rtc::gui::Element::name().
Schema()
template<typename Callback > SchemaImpl<Callback> mc_rtc::gui::Schema (const std::string & name, const std::string & schema, Callback cb)
Helper function to create a Schema element.
References mc_rtc::gui::Element::name().
StringInput()
template<typename GetT , typename SetT > StringInputImpl<GetT, SetT> mc_rtc::gui::StringInput (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create a StringInputImpl.
References mc_rtc::gui::Element::name().
Table() [1/4]
template<typename GetData > details::StaticTableImpl<GetData> mc_rtc::gui::Table (const std::string & name, std::vector< std::string > header, GetData get_data_fn)
Helper function to a get a StaticTableImpl.
References mc_rtc::gui::Element::name(), and Table().
Referenced by Table().
Table() [2/4]
template<typename GetData > details::StaticTableImpl<GetData> mc_rtc::gui::Table (const std::string & name, std::vector< std::string > header, std::vector< std::string > format, GetData get_data_fn)
Helper function to a get a StaticTableImpl with format.
References mc_rtc::gui::Element::name(), and Table().
Table() [3/4]
template<typename GetHeader , typename GetData > details::TableImpl<GetHeader, GetData> mc_rtc::gui::Table (const std::string & name, GetHeader get_header_fn, GetData get_data_fn)
Helper function to get a TableImpl.
References mc_rtc::gui::Element::name(), and Table().
Table() [4/4]
template<typename GetHeader , typename GetFormat , typename GetData > details::FormattedTableImpl<GetHeader, GetFormat, GetData> mc_rtc::gui::Table (const std::string & name, GetHeader get_header_fn, GetFormat get_format_fn, GetData get_data_fn)
Helper function to get a FormattedTableImpl.
References mc_rtc::gui::Element::name(), and Table().
Trajectory() [1/2]
template<typename GetT > TrajectoryImpl<GetT> mc_rtc::gui::Trajectory (const std::string & name, GetT get_fn)
Function helper to get a TrajectoryImpl.
References mc_rtc::gui::Element::name().
Trajectory() [2/2]
template<typename GetT > TrajectoryImpl<GetT> mc_rtc::gui::Trajectory (const std::string & name, const LineConfig & config, GetT get_fn)
Function helper to get a TrajectoryImpl.
References mc_rtc::gui::Element::name().
Transform() [1/2]
template<typename GetT > TransformROImpl<GetT> mc_rtc::gui::Transform (const std::string & name, GetT get_fn)
Helper function to create a Transform element (read-only)
References mc_rtc::gui::Element::name().
Transform() [2/2]
template<typename GetT , typename SetT > TransformImpl<GetT, SetT> mc_rtc::gui::Transform (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create a Transform element (editable)
References mc_rtc::gui::Element::name().
XYTheta() [1/2]
template<typename GetT > XYThetaROImpl<GetT> mc_rtc::gui::XYTheta (const std::string & name, GetT get_fn)
Helper function to create an XYTheta element (read-only)
References mc_rtc::gui::Element::name().
XYTheta() [2/2]
template<typename GetT , typename SetT > XYThetaImpl<GetT, SetT> mc_rtc::gui::XYTheta (const std::string & name, GetT get_fn, SetT set_fn)
Helper function to create an XYTheta element.
References mc_rtc::gui::Element::name().