mc_rtc::gui::plot Namespace Reference
mc_rtc::gui::plot Namespace Reference
Namespaces
impl
Classes
struct AxisConfiguration
Describe the configuration of an axis.
struct PolygonDescription
Describe a polygon to be plotted.
struct Range
Range for abscissa or ordinate display.
Enumerations
enum Plot {
Plot::Standard = 0,
Plot::XY
}
Describe plot types for the client.
enum Type {
Type::Abscissa,
Type::Ordinate,
Type::Polygon,
Type::Polygons,
Type::AbscissaOrdinate
}
Distinguish plot types.
Functions
template<typename GetT >
impl::Abscissa< GetT > X (AxisConfiguration config, GetT get_fn)
Helper to create an impl::Abscissa.
template<typename GetT >
impl::Abscissa< GetT > X (const std::string &legend, GetT get_fn)
Helper to create an impl::Abscissa without limits.
template<typename GetT >
impl::Abscissa< GetT > X (const char *legend, GetT get_fn)
Helper to create an impl::Abscissa without limits (C-string overload)
template<typename GetXT , typename GetYT >
impl::AbscissaOrdinate< GetXT, GetYT > XY (const std::string &name, GetXT get_x_fn, GetYT get_y_fn, Color color, Style style=Style::Solid, Side side=Side::Left)
Helper to create an impl::Ordinate.
template<typename GetXT , typename GetYT , typename GetColor >
impl::AbscissaOrdinateWithColor< GetXT, GetYT, GetColor > XY (const std::string &name, GetXT get_x_fn, GetYT get_y_fn, GetColor get_color_fn, Style style=Style::Solid, Side side=Side::Left)
Helper to create an impl::OrdinateWithColor.
template<typename GetT >
impl::Ordinate< GetT > Y (const std::string &name, GetT get_fn, Color color, Style style=Style::Solid, Side side=Side::Left)
Helper to create an impl::Ordinate.
template<typename GetT , typename GetColor >
impl::OrdinateWithColor< GetT, GetColor > Y (const std::string &name, GetT get_fn, GetColor get_color, Style style=Style::Solid, Side side=Side::Left)
Helper to create an impl::OrdinateWithColor.
template<typename GetT >
impl::Polygon< GetT > Polygon (const std::string &name, GetT get_fn, Side side=Side::Left)
Helper function to create an impl::Polygon.
template<typename GetT >
impl::Polygons< GetT > Polygons (const std::string &name, GetT get_fn, Side side=Side::Left)
Helper function to create an impl::Polygon.
template<typename T >
constexpr bool is_Abscissa ()
template<typename T >
constexpr bool is_not_Abscissa ()
template<typename T , typename T2 , typename... Args>
constexpr bool is_not_Abscissa ()
template<typename T >
constexpr bool is_2d ()
template<typename T , typename T2 , typename... Args>
constexpr bool is_2d ()
Enumeration Type Documentation
Plot
enum mc_rtc::gui::plot::Plot strong
Describe plot types for the client.
Enumerator
Standard
Identify a plot that provides an abscissa.
XY
Identify a plot that provides XY legends.
Type
enum mc_rtc::gui::plot::Type strong
Distinguish plot types.
Enumerator
Abscissa
This plot type is expected to return X values only.
Ordinate
This plot type is expected to return Y values only.
Polygon
This plot type is expected to return a list of points to plot.
Polygons
This plot type is expected to return a list of polygons.
AbscissaOrdinate
This plot type return (X, Y) couples.
Function Documentation
is_2d() [1/2]
template<typename T > constexpr bool mc_rtc::gui::plot::is_2d ()
References Abscissa, and Ordinate.
is_2d() [2/2]
template<typename T , typename T2 , typename... Args> constexpr bool mc_rtc::gui::plot::is_2d ()
is_Abscissa()
template<typename T > constexpr bool mc_rtc::gui::plot::is_Abscissa ()
References Abscissa.
is_not_Abscissa() [1/2]
template<typename T > constexpr bool mc_rtc::gui::plot::is_not_Abscissa ()
References Abscissa.
is_not_Abscissa() [2/2]
template<typename T , typename T2 , typename... Args> constexpr bool mc_rtc::gui::plot::is_not_Abscissa ()
Polygon()
template<typename GetT > impl::Polygon<GetT> mc_rtc::gui::plot::Polygon (const std::string & name, GetT get_fn, Side side = Side::Left)
Helper function to create an impl::Polygon.
References mc_rtc::gui::plot::impl::Polygon< GetT >::side().
Polygons()
template<typename GetT > impl::Polygons<GetT> mc_rtc::gui::plot::Polygons (const std::string & name, GetT get_fn, Side side = Side::Left)
Helper function to create an impl::Polygon.
References mc_rtc::gui::plot::impl::Polygons< GetT >::side().
X() [1/3]
template<typename GetT > impl::Abscissa<GetT> mc_rtc::gui::plot::X (AxisConfiguration config, GetT get_fn)
Helper to create an impl::Abscissa.
X() [2/3]
template<typename GetT > impl::Abscissa<GetT> mc_rtc::gui::plot::X (const std::string & legend, GetT get_fn)
Helper to create an impl::Abscissa without limits.
X() [3/3]
template<typename GetT > impl::Abscissa<GetT> mc_rtc::gui::plot::X (const char * legend, GetT get_fn)
Helper to create an impl::Abscissa without limits (C-string overload)
XY() [1/2]
template<typename GetXT , typename GetYT > impl::AbscissaOrdinate<GetXT, GetYT> mc_rtc::gui::plot::XY (const std::string & name, GetXT get_x_fn, GetYT get_y_fn, Color color, Style style = Style::Solid, Side side = Side::Left)
Helper to create an impl::Ordinate.
References mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style(), and XY().
Referenced by XY().
XY() [2/2]
template<typename GetXT , typename GetYT , typename GetColor > impl::AbscissaOrdinateWithColor<GetXT, GetYT, GetColor> mc_rtc::gui::plot::XY (const std::string & name, GetXT get_x_fn, GetYT get_y_fn, GetColor get_color_fn, Style style = Style::Solid, Side side = Side::Left)
Helper to create an impl::OrdinateWithColor.
References mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style(), and XY().
Y() [1/2]
template<typename GetT > impl::Ordinate<GetT> mc_rtc::gui::plot::Y (const std::string & name, GetT get_fn, Color color, Style style = Style::Solid, Side side = Side::Left)
Helper to create an impl::Ordinate.
References mc_rtc::gui::plot::impl::Ordinate< GetT >::side(), and mc_rtc::gui::plot::impl::Ordinate< GetT >::style().
Y() [2/2]
template<typename GetT , typename GetColor > impl::OrdinateWithColor<GetT, GetColor> mc_rtc::gui::plot::Y (const std::string & name, GetT get_fn, GetColor get_color, Style style = Style::Solid, Side side = Side::Left)
Helper to create an impl::OrdinateWithColor.
References mc_rtc::gui::plot::impl::Ordinate< GetT >::side(), and mc_rtc::gui::plot::impl::Ordinate< GetT >::style().