mc_filter::utils Namespace Reference
mc_filter::utils Namespace Reference
Functions
double clamp (double value, double lower, double upper)
Clamp a value in a given interval.
void clampInPlace (double &value, double lower, double upper)
Clamp a value in-place in a given interval.
double clampAndWarn (double value, double lower, double upper, const std::string &label)
Clamp a value in a given interval, issuing a warning when bounds are hit.
void clampInPlaceAndWarn (double &value, double lower, double upper, const std::string &label)
Clamp value in-place in a given interval, issuing a warning when bounds are hit.
template<typename VectorT >
VectorT clamp (const VectorT &v, double lower, double upper)
Clamps each component of a vector in a given interval.
template<typename VectorT >
VectorT clamp (const VectorT &v, const VectorT &lower, const VectorT &upper)
Clamps each component of a vector in a given interval with vector bounds.
template<typename VectorT >
VectorT clampAndWarn (const VectorT &v, const VectorT &lower, const VectorT &upper, const std::string &label)
Clamps each component of a vector in a given interval with vector bounds issuing a warning when bounds are hit.
template<typename VectorT >
void clampInPlace (VectorT &v, const VectorT &lower, const VectorT &upper)
Clamps each component of a vector in a given interval.
template<typename VectorT >
void clampInPlace (VectorT &v, double lower, double upper)
Clamps in-place each component of a vector in a given interval.
template<typename VectorT >
void clampInPlaceAndWarn (VectorT &vector, const VectorT &lower, const VectorT &upper, const std::string &label)
Clamps in-place each component of a vector in a given interval, issuing a warning when bounds are hit.
Function Documentation
clamp() [1/3]
double mc_filter::utils::clamp (double value, double lower, double upper) inline
Clamp a value in a given interval.
Parameters
value Value to clamp.
lower Lower bound.
upper Upper bound.
Returns
clamped value
Referenced by clamp(), and clampInPlace().
clamp() [2/3]
template<typename VectorT > VectorT mc_filter::utils::clamp (const VectorT & v, double lower, double upper) inline
Clamps each component of a vector in a given interval.
The same lower and upper bounds will be used for each element of the vector.
Parameters
v Vector of values
lower Lower bound
upper Upper bound
VectorT must meet the following requirements:
Read-write element access operator(size_t)
The value type of VectorT must meet the requirements of std::max and std::min
See also
clamp(const VectorT& v, const VectorT & lower, const VectorT & upper)
References clamp().
clamp() [3/3]
template<typename VectorT > VectorT mc_filter::utils::clamp (const VectorT & v, const VectorT & lower, const VectorT & upper) inline
Clamps each component of a vector in a given interval with vector bounds.
VectorT requirements:
See also
VectorT clamp(const VectorT& v, double lower, double upper)
References clamp().
clampAndWarn() [1/2]
double mc_filter::utils::clampAndWarn (double value, double lower, double upper, const std::string & label) inline
Clamp a value in a given interval, issuing a warning when bounds are hit.
See also
clamp(double value, double lower, double upper)
Returns
clamped value
References mc_rtc::log::warning().
Referenced by clampAndWarn(), and clampInPlaceAndWarn().
clampAndWarn() [2/2]
template<typename VectorT > VectorT mc_filter::utils::clampAndWarn (const VectorT & v, const VectorT & lower, const VectorT & upper, const std::string & label) inline
Clamps each component of a vector in a given interval with vector bounds issuing a warning when bounds are hit.
See also
clamp(const VectorT& v, const VectorT & lower, const VectorT & upper)
References clampAndWarn(), and mc_rbdyn::details::to_string().
clampInPlace() [1/3]
void mc_filter::utils::clampInPlace (double & value, double lower, double upper) inline
Clamp a value in-place in a given interval.
See also
clamp(double value, double lower, double upper)
References clamp().
Referenced by mc_filter::LeakyIntegrator< Eigen::Vector3d >::add(), mc_filter::ExponentialMovingAverage< Eigen::Vector3d >::append(), and mc_filter::StationaryOffset< Eigen::Vector3d >::update().
clampInPlace() [2/3]
template<typename VectorT > void mc_filter::utils::clampInPlace (VectorT & v, const VectorT & lower, const VectorT & upper) inline
Clamps each component of a vector in a given interval.
See also
clamp(const VectorT& v, const VectorT & lower, const VectorT & upper)
References clamp().
clampInPlace() [3/3]
template<typename VectorT > void mc_filter::utils::clampInPlace (VectorT & v, double lower, double upper) inline
Clamps in-place each component of a vector in a given interval.
See also
clamp(const VectorT& v, double lower, double upper)
References clamp().
clampInPlaceAndWarn() [1/2]
void mc_filter::utils::clampInPlaceAndWarn (double & value, double lower, double upper, const std::string & label) inline
Clamp value in-place in a given interval, issuing a warning when bounds are hit.
See also
clampAndWarn(double value, double lower, double upper, const std::string & label)
References clampAndWarn().
Referenced by clampInPlaceAndWarn(), and mc_tasks::lipm_stabilizer::ZMPCC::configure().
clampInPlaceAndWarn() [2/2]
template<typename VectorT > void mc_filter::utils::clampInPlaceAndWarn (VectorT & vector, const VectorT & lower, const VectorT & upper, const std::string & label) inline
Clamps in-place each component of a vector in a given interval, issuing a warning when bounds are hit.
See also
clampInPlace(VectorT& v, const VectorT & lower, const VectorT & upper)
References clampInPlaceAndWarn(), and mc_rbdyn::details::to_string().