mc_rbdyn Namespace Reference
mc_rbdyn Namespace Reference
Namespaces
detail
details
lipm_stabilizer
Classes
struct Base
This struct represents a base for the creation of a robot.
struct BodySensor
This structure defines a body sensor, that is a sensor that provides dynamic information about a body.
struct Collision
struct CompoundJointConstraintDescription
Describe a compound joint constraint.
struct Contact
struct CylindricalSurface
struct Device
This struct represents a generic device attached to a robot.
struct DevicePtrVector
Holds a vector of unique pointers.
struct Flexibility
This structure holds a flexible joint, if such a joint is part of a robot, then the following dynamic constraint will be applied for the flexible joint torques:
struct ForceSensor
This struct is intended to hold static information about a force sensor and the current reading of said sensor.
struct GripperSurface
struct Mimic
Stores mimic joint information.
struct PlanarSurface
struct Plane
struct PolygonInterpolator
struct QuadraticGenerator
struct Robot
class RobotLoader
Load RobotModule instances from shared libraries.
struct RobotModule
struct Robots
struct Springs
Holds data regarding springs in a robot.
struct Surface
struct VisualMap
Holds a map from body's names to visual representations.
Typedefs
typedef std::vector< BodySensor, Eigen::aligned_allocator< BodySensor > > BodySensorVector
using CompoundJointConstraintDescriptionVector = std::vector< CompoundJointConstraintDescription, Eigen::aligned_allocator< CompoundJointConstraintDescription > >
using DevicePtr = std::unique_ptr< Device >
using Sensor = Device
using SensorPtr = DevicePtr
typedef std::shared_ptr< RobotModule > RobotModulePtr
using RobotModuleVector = std::vector< RobotModule, Eigen::aligned_allocator< RobotModule > >
typedef std::shared_ptr< Surface > SurfacePtr
Functions
MC_RBDYN_DLLAPI std::ostream & operator<< (std::ostream &os, const Collision &c)
MC_RBDYN_DLLAPI std::vector< sva::PTransformd > computePoints (const mc_rbdyn::Surface &robotSurface, const mc_rbdyn::Surface &envSurface, const sva::PTransformd &X_es_rs)
MC_RBDYN_DLLAPI sva::PTransformd planar (const double &T, const double &B, const double &N_rot)
MC_RBDYN_DLLAPI sva::PTransformd cylindrical (const double &T, const double &T_rot)
MC_RBDYN_DLLAPI void planarParam (const sva::PTransformd &X_es_rs, double &T, double &B, double &N_rot)
MC_RBDYN_DLLAPI void cylindricalParam (const sva::PTransformd &X_es_rs, double &T, double &T_rot)
MC_RBDYN_DLLAPI std::vector< double > jointParam (const Surface &r1Surface, const Surface &r2Surface, const sva::PTransformd &X_es_rs)
MC_RBDYN_DLLAPI std::vector< Plane > planes_from_polygon (const std::shared_ptr< geos::geom::Geometry > &geometry)
MC_RBDYN_DLLAPI std::vector< Eigen::Vector3d > points_from_polygon (std::shared_ptr< geos::geom::Geometry > geometry)
MC_RBDYN_DLLAPI const mc_rbdyn::Robot & robotFromConfig (const mc_rtc::Configuration &config, const mc_rbdyn::Robots &robots, const std::string &prefix, bool required=false, const std::string &robotIndexKey="robotIndex", const std::string &robotNameKey="robot", const std::string &defaultRobotName="")
Obtains a reference to a loaded robot from configuration (using robotName or robotIndex)
std::string MC_RBDYN_DLLAPI robotNameFromConfig (const mc_rtc::Configuration &config, const mc_rbdyn::Robots &robots, const std::string &prefix="", bool required=false, const std::string &robotIndexKey="robotIndex", const std::string &robotNameKey="robot", const std::string &defaultRobotName="")
Helper to obtain the robot name from configuration.
unsigned int MC_RBDYN_DLLAPI robotIndexFromConfig (const mc_rtc::Configuration &config, const mc_rbdyn::Robots &robots, const std::string &prefix="", bool required=false, const std::string &robotIndexKey="robotIndex", const std::string &robotNameKey="robot", const std::string &defaultRobotName="")
Helper to obtain the robot index from configuration.
RobotModule::bounds_t MC_RBDYN_DLLAPI urdf_limits_to_bounds (const rbd::parsers::Limits &limits)
Converts limits provided by RBDyn parsers to bounds.
RobotModule::bounds_t MC_RTC_DEPRECATED MC_RBDYN_DLLAPI urdf_limits_to_bounds (const mc_rbdyn_urdf::Limits &limits)
MC_RBDYN_DLLAPI std::shared_ptr< Robots > loadRobot (const RobotModule &module, sva::PTransformd *base=nullptr, const std::string &baseName="")
MC_RBDYN_DLLAPI MC_RTC_DEPRECATED std::shared_ptr< Robots > loadRobot (const RobotModule &module, const std::string &surfaceDir, sva::PTransformd *base=nullptr, const std::string &baseName="")
MC_RBDYN_DLLAPI std::shared_ptr< Robots > loadRobots (const std::vector< std::shared_ptr< RobotModule >> &modules)
MC_RBDYN_DLLAPI MC_RTC_DEPRECATED std::shared_ptr< Robots > loadRobots (const std::vector< std::shared_ptr< RobotModule >> &modules, const std::vector< std::string > &surfaceDirs)
MC_RBDYN_DLLAPI std::shared_ptr< Robots > loadRobotAndEnv (const RobotModule &module, const RobotModule &envModule, sva::PTransformd *base=nullptr, const std::string &baseName="")
MC_RBDYN_DLLAPI MC_RTC_DEPRECATED std::shared_ptr< Robots > loadRobotAndEnv (const RobotModule &module, const std::string &surfaceDir, const RobotModule &envModule, const std::string &envSurfaceDir, sva::PTransformd *base=nullptr, const std::string &baseName="")
MC_RBDYN_DLLAPI std::shared_ptr< Robots > loadRobotFromUrdf (const std::string &name, const std::string &urdf, bool withVirtualLinks=true, const std::vector< std::string > &filteredLinks={}, bool fixed=false, sva::PTransformd *base=nullptr, const std::string &baseName="")
Eigen::Matrix3d rpyToMat (const double &r, const double &p, const double &y)
Rotation matrix from roll-pitch-yaw angles.
Eigen::Matrix3d rpyToMat (const Eigen::Vector3d &rpy)
Rotation matrix from roll-pitch-yaw angles.
sva::PTransformd rpyToPT (const Eigen::Vector3d &rpy)
Plucker transfrom from roll-pitch-yaw angles.
sva::PTransformd rpyToPT (const double &r, const double &p, const double &y)
Plucker transfrom from roll-pitch-yaw angles.
Eigen::Vector3d rpyFromMat (const Eigen::Matrix3d &E)
Roll-pitch-yaw from rotation matrix.
Eigen::Vector3d rpyFromQuat (const Eigen::Quaterniond &quat)
Roll-pitch-yaw from unit quaternion.
MC_RBDYN_DLLAPI sch::S_Object * surface_to_sch (const mc_rbdyn::Surface &surface, const double &depth=0.01, const unsigned int &slice=8)
MC_RBDYN_DLLAPI sch::S_Object * sch_polyhedron (const std::vector< sva::PTransformd > &points)
MC_RBDYN_DLLAPI sch::S_Object * planar_hull (const mc_rbdyn::PlanarSurface &surface, const double &depth)
MC_RBDYN_DLLAPI sch::S_Object * cylindrical_hull (const mc_rbdyn::CylindricalSurface &surface, const unsigned int &slice)
MC_RBDYN_DLLAPI sch::S_Object * gripper_hull (const mc_rbdyn::GripperSurface &surface, const double &depth)
MC_RBDYN_DLLAPI std::vector< std::shared_ptr< Surface > > readRSDFFromDir (const std::string &dirname)
Eigen::Vector3d MC_RBDYN_DLLAPI zmp (const sva::ForceVecd &netTotalWrench, const Eigen::Vector3d &plane_p, const Eigen::Vector3d &plane_n, double minimalNetNormalForce=1.)
Actual ZMP computation from net total wrench and the ZMP plane.
Eigen::Vector3d MC_RBDYN_DLLAPI zmp (const sva::ForceVecd &netTotalWrench, const sva::PTransformd &zmpFrame, double minimalNetNormalForce=1.)
ZMP computation from net total wrench and a frame.
Detailed Description
Interface used to load robots
Typedef Documentation
BodySensorVector
typedef std::vector<BodySensor, Eigen::aligned_allocator<BodySensor> > mc_rbdyn::BodySensorVector
CompoundJointConstraintDescriptionVector
using mc_rbdyn::CompoundJointConstraintDescriptionVector = typedef std::vector<CompoundJointConstraintDescription, Eigen::aligned_allocator<CompoundJointConstraintDescription> >
DevicePtr
using mc_rbdyn::DevicePtr = typedef std::unique_ptr<Device>
RobotModulePtr
typedef std::shared_ptr<RobotModule> mc_rbdyn::RobotModulePtr
RobotModuleVector
using mc_rbdyn::RobotModuleVector = typedef std::vector<RobotModule, Eigen::aligned_allocator<RobotModule> >
Sensor
using mc_rbdyn::Sensor = typedef Device
SensorPtr
using mc_rbdyn::SensorPtr = typedef DevicePtr
SurfacePtr
typedef std::shared_ptr<Surface> mc_rbdyn::SurfacePtr
Function Documentation
computePoints()
MC_RBDYN_DLLAPI std::vector<sva::PTransformd> mc_rbdyn::computePoints (const mc_rbdyn::Surface & robotSurface, const mc_rbdyn::Surface & envSurface, const sva::PTransformd & X_es_rs)
cylindrical()
MC_RBDYN_DLLAPI sva::PTransformd mc_rbdyn::cylindrical (const double & T, const double & T_rot)
cylindrical_hull()
MC_RBDYN_DLLAPI sch::S_Object* mc_rbdyn::cylindrical_hull (const mc_rbdyn::CylindricalSurface & surface, const unsigned int & slice)
cylindricalParam()
MC_RBDYN_DLLAPI void mc_rbdyn::cylindricalParam (const sva::PTransformd & X_es_rs, double & T, double & T_rot)
gripper_hull()
MC_RBDYN_DLLAPI sch::S_Object* mc_rbdyn::gripper_hull (const mc_rbdyn::GripperSurface & surface, const double & depth)
jointParam()
MC_RBDYN_DLLAPI std::vector<double> mc_rbdyn::jointParam (const Surface & r1Surface, const Surface & r2Surface, const sva::PTransformd & X_es_rs)
loadRobot() [1/2]
MC_RBDYN_DLLAPI std::shared_ptr<Robots> mc_rbdyn::loadRobot (const RobotModule & module, sva::PTransformd * base = nullptr, const std::string & baseName = "")
Referenced by mc_control::MCController::datastore().
loadRobot() [2/2]
MC_RBDYN_DLLAPI MC_RTC_DEPRECATED std::shared_ptr<Robots> mc_rbdyn::loadRobot (const RobotModule & module, const std::string & surfaceDir, sva::PTransformd * base = nullptr, const std::string & baseName = "")
loadRobotAndEnv() [1/2]
MC_RBDYN_DLLAPI std::shared_ptr<Robots> mc_rbdyn::loadRobotAndEnv (const RobotModule & module, const RobotModule & envModule, sva::PTransformd * base = nullptr, const std::string & baseName = "")
loadRobotAndEnv() [2/2]
MC_RBDYN_DLLAPI MC_RTC_DEPRECATED std::shared_ptr<Robots> mc_rbdyn::loadRobotAndEnv (const RobotModule & module, const std::string & surfaceDir, const RobotModule & envModule, const std::string & envSurfaceDir, sva::PTransformd * base = nullptr, const std::string & baseName = "")
loadRobotFromUrdf()
MC_RBDYN_DLLAPI std::shared_ptr<Robots> mc_rbdyn::loadRobotFromUrdf (const std::string & name, const std::string & urdf, bool withVirtualLinks = true, const std::vector< std::string > & filteredLinks = {}, bool fixed = false, sva::PTransformd * base = nullptr, const std::string & baseName = "")
loadRobots() [1/2]
MC_RBDYN_DLLAPI std::shared_ptr<Robots> mc_rbdyn::loadRobots (const std::vector< std::shared_ptr< RobotModule >> & modules)
loadRobots() [2/2]
MC_RBDYN_DLLAPI MC_RTC_DEPRECATED std::shared_ptr<Robots> mc_rbdyn::loadRobots (const std::vector< std::shared_ptr< RobotModule >> & modules, const std::vector< std::string > & surfaceDirs)
operator<<()
MC_RBDYN_DLLAPI std::ostream& mc_rbdyn::operator<< (std::ostream & os, const Collision & c)
Referenced by mc_rbdyn::Collision::isNone().
planar()
MC_RBDYN_DLLAPI sva::PTransformd mc_rbdyn::planar (const double & T, const double & B, const double & N_rot)
planar_hull()
MC_RBDYN_DLLAPI sch::S_Object* mc_rbdyn::planar_hull (const mc_rbdyn::PlanarSurface & surface, const double & depth)
planarParam()
MC_RBDYN_DLLAPI void mc_rbdyn::planarParam (const sva::PTransformd & X_es_rs, double & T, double & B, double & N_rot)
planes_from_polygon()
MC_RBDYN_DLLAPI std::vector<Plane> mc_rbdyn::planes_from_polygon (const std::shared_ptr< geos::geom::Geometry > & geometry)
points_from_polygon()
MC_RBDYN_DLLAPI std::vector<Eigen::Vector3d> mc_rbdyn::points_from_polygon (std::shared_ptr< geos::geom::Geometry > geometry)
readRSDFFromDir()
MC_RBDYN_DLLAPI std::vector<std::shared_ptr<Surface> > mc_rbdyn::readRSDFFromDir (const std::string & dirname)
rpyFromMat()
Eigen::Vector3d mc_rbdyn::rpyFromMat (const Eigen::Matrix3d & E) inline
Roll-pitch-yaw from rotation matrix.
Parameters
R Rotation matrix.
Returns
rpy Vector of roll-pitch-yaw angles (Euler sequence (0, 1, 2)).
Adapted from formula (289) of "Representing attitude: Euler angles, unit quaternions, and rotation vectors".
Referenced by rpyFromQuat().
rpyFromQuat()
Eigen::Vector3d mc_rbdyn::rpyFromQuat (const Eigen::Quaterniond & quat) inline
Roll-pitch-yaw from unit quaternion.
Parameters
quat Input unit quaternion.
Returns
rpy Vector of roll-pitch-yaw angles (Euler sequence (0, 1, 2)).
Be careful that Eigen's conversion to rotation matrices is the OPPOSITE of that from "Representing attitude: Euler angles, unit quaternions, and rotation vectors", i.e. we need to transpose/flip signs from Equation (290) of this paper.
References rpyFromMat().
rpyToMat() [1/2]
Eigen::Matrix3d mc_rbdyn::rpyToMat (const double & r, const double & p, const double & y) inline
Rotation matrix from roll-pitch-yaw angles.
Parameters
r Roll angle.
p Pitch angle.
y Yaw angle.
Returns
E Rotation matrix.
Referenced by rpyToMat(), and rpyToPT().
rpyToMat() [2/2]
Eigen::Matrix3d mc_rbdyn::rpyToMat (const Eigen::Vector3d & rpy) inline
Rotation matrix from roll-pitch-yaw angles.
Parameters
rpy Vector of roll-pitch-yaw angles.
Returns
E Rotation matrix.
References rpyToMat().
rpyToPT() [1/2]
sva::PTransformd mc_rbdyn::rpyToPT (const Eigen::Vector3d & rpy) inline
Plucker transfrom from roll-pitch-yaw angles.
Parameters
rpy Vector of roll-pitch-yaw angles.
Returns
X Plucker transform with no translation.
References rpyToMat().
rpyToPT() [2/2]
sva::PTransformd mc_rbdyn::rpyToPT (const double & r, const double & p, const double & y) inline
Plucker transfrom from roll-pitch-yaw angles.
Parameters
r Roll angle.
p Pitch angle.
y Yaw angle.
Returns
X Plucker transform with no translation.
References rpyToMat().
sch_polyhedron()
MC_RBDYN_DLLAPI sch::S_Object* mc_rbdyn::sch_polyhedron (const std::vector< sva::PTransformd > & points)
surface_to_sch()
MC_RBDYN_DLLAPI sch::S_Object* mc_rbdyn::surface_to_sch (const mc_rbdyn::Surface & surface, const double & depth = 0.01, const unsigned int & slice = 8)
urdf_limits_to_bounds() [1/2]
RobotModule::bounds_t MC_RBDYN_DLLAPI mc_rbdyn::urdf_limits_to_bounds (const rbd::parsers::Limits & limits)
Converts limits provided by RBDyn parsers to bounds.
Parameters
limits Limits as provided by RBDyn parsers
urdf_limits_to_bounds() [2/2]
RobotModule::bounds_t MC_RTC_DEPRECATED MC_RBDYN_DLLAPI mc_rbdyn::urdf_limits_to_bounds (const mc_rbdyn_urdf::Limits & limits)
Deprecated:
{Use rbd::parsers version instead}
zmp() [1/2]
Eigen::Vector3d MC_RBDYN_DLLAPI mc_rbdyn::zmp (const sva::ForceVecd & netTotalWrench, const Eigen::Vector3d & plane_p, const Eigen::Vector3d & plane_n, double minimalNetNormalForce = 1.)
Actual ZMP computation from net total wrench and the ZMP plane.
Parameters
netTotalWrench Total wrench for all links in contact
plane_p Arbitrary point on the ZMP plane
plane_n Normal to the ZMP plane (normalized)
minimalNetNormalForce[N] Mininal force above which the ZMP computation is considered valid. Must be >0 (prevents a divide by zero).
Returns
zmp expressed in the requested plane
Exceptions
To prevent dividing by zero, throws if the projected force is below minimalNetNormalForce newton. This is highly unlikely to happen and would likely indicate indicate that you are computing a ZMP from invalid forces (such as with the robot in the air).
Referenced by mc_tasks::lipm_stabilizer::StabilizerTask::leftFootRatio().
zmp() [2/2]
Eigen::Vector3d MC_RBDYN_DLLAPI mc_rbdyn::zmp (const sva::ForceVecd & netTotalWrench, const sva::PTransformd & zmpFrame, double minimalNetNormalForce = 1.)
ZMP computation from net total wrench and a frame.
See zmpDoc
Parameters
netTotalWrench
zmpFrame Frame used for ZMP computation. The convention here is that the contact frame should have its z-axis pointing in the normal direction of the contact towards the robot.
Exceptions
To prevent dividing by zero, throws if the projected force is below minimalNetNormalForce newton. This is highly unlikely to happen and would likely indicate indicate that you are computing a ZMP from invalid forces (such as with the robot in the air).
Returns
ZMP expressed in the plane defined by the zmpFrame frame.