mc_rtc Namespace Reference
mc_rtc Namespace Reference
This file holds all mc_rtc::Configuration based serialization operation for mc_rbdyn objects.
Namespaces
constants
gui
internal
io
log
Classes
struct Configuration
Simplify access to values hold within a JSON file.
struct ConfigurationArrayIterator
struct ConfigurationLoader
This structure should be specialized to implement serialization for a new type.
struct ConfigurationLoader< mc_control::fsm::Contact >
struct ConfigurationLoader< mc_rbdyn::CompoundJointConstraintDescription >
struct ConfigurationLoader< mc_rbdyn::Contact >
struct ConfigurationLoader< mc_rbdyn::lipm_stabilizer::FDQPWeights >
Read force distribution QP weights from configuration.
struct ConfigurationLoader< mc_rbdyn::lipm_stabilizer::SafetyThresholds >
Read-write stabilizer safety thresholds from configuration.
struct ConfigurationLoader< mc_rbdyn::lipm_stabilizer::StabilizerConfiguration >
struct ConfigurationLoader< mc_rbdyn::lipm_stabilizer::ZMPCCConfiguration >
Read force distribution QP weights from configuration.
struct ConfigurationLoader< mc_rbdyn::RobotModule >
struct ConfigurationLoader< mc_rbdyn::RobotModulePtr >
struct ConfigurationLoader< mc_rtc::gui::ArrowConfig >
struct ConfigurationLoader< mc_rtc::gui::Color >
struct ConfigurationLoader< mc_rtc::gui::ForceConfig >
struct ConfigurationLoader< mc_rtc::gui::LineConfig >
struct ConfigurationLoader< mc_rtc::gui::PointConfig >
struct ConfigurationLoader< mc_tasks::lipm_stabilizer::ContactState >
struct ConfigurationLoader< void >
struct DataStore
Generic data store.
class Loader
General wrapper for ltdl functionnalities.
class LoaderException
Exception thrown by loader interface.
struct LoaderSandboxData
Holds sandbox data.
struct Logger
Logs controller data to disk.
class LTDLHandle
Wrapper around lt_dlhandle.
struct MessagePackBuilder
Helper class to build a MessagePack message.
class ObjectLoader
ltdl wrapper for factory-like classes
struct RobotPublisher
This structure is able to publish a Robot's state to ROS.
struct ROSBridge
Allows to access ROS functionalities within mc_rtc without explicit ROS dependencies.
Typedefs
using LTDLHandlePtr = std::shared_ptr< LTDLHandle >
Functions
template<typename T >
std::vector< T > fromVectorOrElement (const mc_rtc::Configuration &config, const std::string &key, const std::vector< T > &defaultVec)
Attempts to convert a read a vector or single element as a vector, use default value if it fails.
template<typename T >
std::vector< T > fromVectorOrElement (const mc_rtc::Configuration &config, const std::string &key)
Attempts to convert a read a vector or single element as a vector.
template<typename T , typename FunT , typename... Args>
T * no_sandbox_function_call (FunT create_fn, const Args &... args)
Calls a function without sandboxing.
template<typename T , typename FunT , typename... Args>
T * sandbox_function_call (FunT create_fn, const Args &... args)
Calls a function in a sandbox.
template<typename T >
std::string type_name ()
Return a human-readable type name.
Variables
struct MC_RTC_UTILS_DLLAPI ConfigurationArrayIterator
struct MC_RTC_UTILS_DLLAPI Configuration
constexpr auto OUT_NONE = "\033[00m"
constexpr auto OUT_BLUE = "\033[01;34m"
constexpr auto OUT_GREEN = "\033[01;32m"
constexpr auto OUT_PURPLE = "\033[01;35m"
constexpr auto OUT_RED = "\033[01;31m"
Detailed Description
This file holds all mc_rtc::Configuration based serialization operation for mc_rbdyn objects.
This file contains classes that are used to configure the visual styles of various elements in the GUI.
This header contains the base block of all elements in the GUI system.
This file contains some utility template metaprogramming functions for the GUI.
Interface used to load observers
For the implementation details of specific elements look into their dedicated header
Typedef Documentation
LTDLHandlePtr
using mc_rtc::LTDLHandlePtr = typedef std::shared_ptr<LTDLHandle>
Function Documentation
fromVectorOrElement() [1/2]
template<typename T > std::vector<T> mc_rtc::fromVectorOrElement (const mc_rtc::Configuration & config, const std::string & key, const std::vector< T > & defaultVec)
Attempts to convert a read a vector or single element as a vector, use default value if it fails.
Example:
configVector: ["String1", "String2"]
configString: "String"
The following are valid
auto conf = mc_rtc::Configuration{};
conf.add("configVector", {"String1", "String2"})
conf.add("configString", "String1");
auto v1 = fromVectorOrElement<std::string>(conf("configVector"));
auto v2 = fromVectorOrElement<std::string>(conf("configString"));
Template Parameters
T Type of the element to convert toward
Parameters
config Configuration object from which to convert. This should contain either a vector of elements convertible to T ([T, T, ...]) or a single T element.
key Name of the element to read
Returns
Vector containing all elements in the configuration vector or the single item. If it fails, return defaultVec.
References mc_rtc::Configuration::has(), and mc_rtc::Configuration::Exception::silence().
fromVectorOrElement() [2/2]
template<typename T > std::vector<T> mc_rtc::fromVectorOrElement (const mc_rtc::Configuration & config, const std::string & key)
Attempts to convert a read a vector or single element as a vector.
Variant of fromVectorOrElement(const mc_rtc::Configuration & config, const std::string & key, const std::vector<T> & defaultVec)
Exceptions
mc_rtc::Configuration::Exception If the key is not found or the configuration is neither convertible as std::vector<T> or T.
References mc_rtc::log::critical(), MC_RTC_UTILS_DLLAPI, and mc_rtc::Configuration::Exception::silence().
no_sandbox_function_call()
template<typename T , typename FunT , typename... Args> T * mc_rtc::no_sandbox_function_call (FunT create_fn, const Args &... args)
Calls a function without sandboxing.
Only catches exceptions
Template Parameters
T Return type of the function
FunT Type of the create function
Args Arguments passed to the creation function
sandbox_function_call()
template<typename T , typename FunT , typename... Args> T* mc_rtc::sandbox_function_call (FunT create_fn, const Args &... args)
Calls a function in a sandbox.
Allows a function call to fail horribly without crashing the main program, allowing us to survive the event, report and throw.
Only works on Linux.
Template Parameters
T Return type of the function
FunT Type of the create function
Args Arguments passed to the creation function
References mc_rtc::LoaderSandboxData< T >::complete, mc_rtc::LoaderSandboxData< T >::fn, and mc_rtc::LoaderSandboxData< T >::ret.
type_name()
template<typename T > std::string mc_rtc::type_name ()
Return a human-readable type name.
Only use for displaying messages as the name is not guaranteed to be the same across compilers and invokation
References mc_rtc::internal::demangle().
Variable Documentation
Configuration
struct MC_RTC_UTILS_DLLAPI mc_rtc::Configuration
Referenced by mc_rtc::Configuration::operator std::array< T, N >(), mc_rtc::Configuration::operator std::map< std::string, T, C, A >(), mc_rtc::Configuration::operator std::pair< T1, T2 >(), mc_rtc::Configuration::operator std::set< T, C, A >(), mc_rtc::Configuration::operator std::unordered_set< T, H, E, A >(), mc_rtc::Configuration::operator std::vector< T, A >(), mc_rtc::Configuration::operator T(), and mc_rtc::Configuration::push().
ConfigurationArrayIterator
struct MC_RTC_UTILS_DLLAPI mc_rtc::ConfigurationArrayIterator
OUT_BLUE
constexpr auto mc_rtc::OUT_BLUE = "\033[01;34m"
OUT_GREEN
constexpr auto mc_rtc::OUT_GREEN = "\033[01;32m"
OUT_NONE
constexpr auto mc_rtc::OUT_NONE = "\033[00m"
OUT_PURPLE
constexpr auto mc_rtc::OUT_PURPLE = "\033[01;35m"
OUT_RED
constexpr auto mc_rtc::OUT_RED = "\033[01;31m"