mc_control::MCController Class Reference
mc_control::MCController Class Reference
MCController is the base class to implement all controllers.
#include <mc_control/MCController.h>
Classes
struct DeprecatedAnchorFrame
Helper to make the anchor frame compile-time deprecation warning clearer.
Public Member Functions
virtual ~MCController ()
virtual bool run ()
This function is called at each time step of the process driving the robot (i.e.
virtual void createObserverPipelines (const mc_rtc::Configuration &config)
Create state observation pipelines from configuration.
virtual bool runObserverPipelines ()
This function is called before the run() function at each time step of the process driving the robot (i.e.
virtual bool resetObserverPipelines ()
Reset the observers.
bool hasObserverPipeline (const std::string &name) const
Whether this controller contains a pipeline with the provided name.
bool hasObserverPipeline () const
True if this controller has at least one state observation pipeline.
const std::vector< mc_observers::ObserverPipeline > & observerPipelines () const
Provides const access to the state observation pipelines defined in this controller.
std::vector< mc_observers::ObserverPipeline > & observerPipelines ()
Non-const variant.
const mc_observers::ObserverPipeline & observerPipeline (const std::string &name) const
Provides const access to a state-observation pipeline.
mc_observers::ObserverPipeline & observerPipeline (const std::string &name)
Non-const variant.
const mc_observers::ObserverPipeline & observerPipeline () const
Provides const access to the main observer pipeline (first pipeline)
mc_observers::ObserverPipeline & observerPipeline ()
Non-const variant.
bool run (mc_solver::FeedbackType fType)
Can be called in derived class instead of run to use a feedback strategy different from the default one.
virtual void stop ()
This function is called when the controller is stopped.
virtual const mc_solver::QPResultMsg & send (const double &t)
Gives access to the result of the QP execution.
virtual void reset (const ControllerResetData &reset_data)
Reset the controller with data provided by ControllerResetData.
const mc_rbdyn::Robot & robot () const
Return the main robot (first robot provided in the constructor)
const mc_rbdyn::Robot & env () const
Return the env "robot".
const mc_rbdyn::Robots & robots () const
Return the mc_rbdyn::Robots controlled by this controller.
mc_rbdyn::Robots & robots ()
Non-const variant of robots().
const mc_rbdyn::Robot & robot (const std::string &name) const
Return the mc_rbdyn::Robot controlled by this controller.
mc_rbdyn::Robot & robot (const std::string &name)
Non-const variant of robot(name).
mc_rbdyn::Robot & robot ()
Non-const variant of robot().
mc_rbdyn::Robot & env ()
Non-const variant of env().
const mc_solver::QPSolver & solver () const
Return the mc_solver::QPSolver instance attached to this controller.
mc_solver::QPSolver & solver ()
Non-const variant of solver().
mc_rtc::Logger & logger ()
Returns mc_rtc::Logger instance.
std::shared_ptr< mc_rtc::gui::StateBuilder > gui ()
Returns mc_rtc::gui::StateBuilder ptr.
mc_rtc::DataStore & datastore ()
Provides access to the shared datastore.
const mc_rtc::DataStore & datastore () const
Provides access to the shared datastore (const)
const mc_rbdyn::Robots & realRobots () const
Return the mc_rbdyn::Robots real robots instance.
mc_rbdyn::Robots & realRobots ()
Non-const variant of realRobots().
const mc_rbdyn::Robot & realRobot () const
Return the main mc_rbdyn::Robot real robot instance.
mc_rbdyn::Robot & realRobot ()
Non-const variant of realRobot().
const mc_rbdyn::Robot & realRobot (const std::string &name) const
Return the mc_rbdyn::Robot controlled by this controller.
mc_rbdyn::Robot & realRobot (const std::string &name)
Non-const variant of realRobot(name).
virtual void supported_robots (std::vector< std::string > &out) const
Returns a list of robots supported by the controller.
mc_rbdyn::Robot & loadRobot (mc_rbdyn::RobotModulePtr rm, const std::string &name)
Load an additional robot into the controller (and its corresponding realRobot instance)
void removeRobot (const std::string &name)
Remove a robot from the controller.
mc_rtc::Configuration & config ()
Access or modify controller configuration.
const mc_rtc::Configuration & config () const
Access controller configuration (const)
Gripper & gripper (const std::string &robot, const std::string &gripper)
Access a gripper by robot's name and gripper's name.
template<typename T = void>
void anchorFrame (const sva::PTransformd &)
template<typename T = void>
void anchorFrameReal (const sva::PTransformd &)
template<typename T = void>
const sva::PTransformd & anchorFrame () const
template<typename T = void>
const sva::PTransformd & anchorFrameReal () const
Public Attributes
const double timeStep
Controller timestep.
mc_solver::ContactConstraint contactConstraint
Contact constraint for the main robot.
mc_solver::DynamicsConstraint dynamicsConstraint
Dynamics constraints for the main robot.
mc_solver::KinematicsConstraint kinematicsConstraint
Kinematics constraints for the main robot.
mc_solver::CollisionsConstraint selfCollisionConstraint
Self collisions constraint for the main robot.
std::unique_ptr< mc_solver::CompoundJointConstraint > compoundJointConstraint
Compound joint constraint for the main robot.
std::shared_ptr< mc_tasks::PostureTask > postureTask
Posture task for the main robot.
std::string name_
Protected Member Functions
MCController (std::shared_ptr< mc_rbdyn::RobotModule > robot, double dt)
Builds a controller base with an empty environment.
MCController (std::shared_ptr< mc_rbdyn::RobotModule > robot, double dt, const mc_rtc::Configuration &config)
MCController (const std::vector< std::shared_ptr< mc_rbdyn::RobotModule >> &robot_modules, double dt)
Builds a multi-robot controller base.
MCController (const std::vector< std::shared_ptr< mc_rbdyn::RobotModule >> &robot_modules, double dt, const mc_rtc::Configuration &config)
Builds a multi-robot controller base.
mc_rbdyn::Robot & loadRobot (mc_rbdyn::RobotModulePtr rm, const std::string &name, mc_rbdyn::Robots &robots, bool updateNrVars=true)
Load an additional robot into the controller.
Protected Attributes
std::shared_ptr< mc_solver::QPSolver > qpsolver
QP solver.
std::vector< mc_observers::ObserverPipeline > observerPipelines_
State observation pipelines for this controller.
std::shared_ptr< mc_rtc::Logger > logger_
Logger provided by MCGlobalController.
std::shared_ptr< mc_rtc::gui::StateBuilder > gui_
GUI state builder.
mc_rtc::Configuration config_
Keep track of the configuration of the controller.
mc_rtc::DataStore datastore_
DataStore to share variables/objects between different parts of the framework (states...)
Friends
struct MCGlobalController
Detailed Description
MCController is the base class to implement all controllers.
It assumes that at least two robots are provided. The first is considered as the "main" robot. Some common constraints and a posture task are defined (but not added to the solver) for this robot
Constructor & Destructor Documentation
~MCController()
virtual mc_control::MCController::~MCController () virtual
MCController() [1/4]
mc_control::MCController::MCController (std::shared_ptr< mc_rbdyn::RobotModule > robot, double dt) protected
Builds a controller base with an empty environment.
Parameters
robot Pointer to the main RobotModule
dt Controller timestep your controller
MCController() [2/4]
mc_control::MCController::MCController (std::shared_ptr< mc_rbdyn::RobotModule > robot, double dt, const mc_rtc::Configuration & config) protected
MCController() [3/4]
mc_control::MCController::MCController (const std::vector< std::shared_ptr< mc_rbdyn::RobotModule >> & robot_modules, double dt) protected
Builds a multi-robot controller base.
Parameters
robots Collection of robot modules used by the controller
dt Timestep of the controller
MCController() [4/4]
mc_control::MCController::MCController (const std::vector< std::shared_ptr< mc_rbdyn::RobotModule >> & robot_modules, double dt, const mc_rtc::Configuration & config) protected
Builds a multi-robot controller base.
Parameters
robots Collection of robot modules used by the controller
dt Timestep of the controller
config Controller configuration
Member Function Documentation
anchorFrame() [1/2]
template<typename T = void> void mc_control::MCController::anchorFrame (const sva::PTransformd &) inline
Deprecated:
The observer's anchor frame is now provided by a callback on the datastore.
For further information, please refer to the observer's tutorial: https://jrl-umi3218.github.io/mc_rtc/tutorials/recipes/observers.html
anchorFrame() [2/2]
template<typename T = void> const sva::PTransformd& mc_control::MCController::anchorFrame () const inline
Deprecated:
The observer's anchor frame is now provided by a callback on the datastore.
For further information, please refer to the observer's tutorial: https://jrl-umi3218.github.io/mc_rtc/tutorials/recipes/observers.html
anchorFrameReal() [1/2]
template<typename T = void> void mc_control::MCController::anchorFrameReal (const sva::PTransformd &) inline
Deprecated:
The observer's anchor frame is now provided by a callback on the datastore.
For further information, please refer to the observer's tutorial: https://jrl-umi3218.github.io/mc_rtc/tutorials/recipes/observers.html
anchorFrameReal() [2/2]
template<typename T = void> const sva::PTransformd& mc_control::MCController::anchorFrameReal () const inline
Deprecated:
The observer's anchor frame is now provided by a callback on the datastore.
For further information, please refer to the observer's tutorial: https://jrl-umi3218.github.io/mc_rtc/tutorials/recipes/observers.html
References mc_rbdyn::loadRobot().
config() [1/2]
mc_rtc::Configuration& mc_control::MCController::config () inline
Access or modify controller configuration.
config() [2/2]
const mc_rtc::Configuration& mc_control::MCController::config () const inline
Access controller configuration (const)
createObserverPipelines()
virtual void mc_control::MCController::createObserverPipelines (const mc_rtc::Configuration & config) virtual
Create state observation pipelines from configuration.
Please refer to the ObserverPipelines JSON Schema for supported configuration options.
See also
mc_observers::ObserverPipeline
datastore() [1/2]
mc_rtc::DataStore& mc_control::MCController::datastore () inline
Provides access to the shared datastore.
datastore() [2/2]
const mc_rtc::DataStore& mc_control::MCController::datastore () const inline
Provides access to the shared datastore (const)
References mc_rbdyn::loadRobot().
env() [1/2]
const mc_rbdyn::Robot& mc_control::MCController::env () const
Return the env "robot".
Note
In multi-robot scenarios, the env robot is either:
The first robot with zero dof
The last robot provided at construction
env() [2/2]
mc_rbdyn::Robot& mc_control::MCController::env ()
Non-const variant of env().
gripper()
Gripper& mc_control::MCController::gripper (const std::string & robot, const std::string & gripper)
Access a gripper by robot's name and gripper's name.
Parameters
robot Name of the robot
gripper Name of the gripper
Exceptions
If the robot's name is not valid or the gripper's name is not valid
gui()
std::shared_ptr<mc_rtc::gui::StateBuilder> mc_control::MCController::gui () inline
Returns mc_rtc::gui::StateBuilder ptr.
hasObserverPipeline() [1/2]
bool mc_control::MCController::hasObserverPipeline (const std::string & name) const
Whether this controller contains a pipeline with the provided name.
Parameters
name Name of the pipeline
hasObserverPipeline() [2/2]
bool mc_control::MCController::hasObserverPipeline () const
True if this controller has at least one state observation pipeline.
loadRobot() [1/2]
mc_rbdyn::Robot& mc_control::MCController::loadRobot (mc_rbdyn::RobotModulePtr rm, const std::string & name)
Load an additional robot into the controller (and its corresponding realRobot instance)
Parameters
rm RobotModule used to load the robot
name Name of the robot
Returns
The loaded control robot. You may access the corresponding real robot through realRobots().robot(name)
loadRobot() [2/2]
mc_rbdyn::Robot& mc_control::MCController::loadRobot (mc_rbdyn::RobotModulePtr rm, const std::string & name, mc_rbdyn::Robots & robots, bool updateNrVars = true) protected
Load an additional robot into the controller.
Parameters
name Name of the robot
rm RobotModule used to load the robot
robots Robots in which this robot will be loaded
updateNrVars When true, update the number of variables in the QP problem.
Returns
The loaded robot
logger()
mc_rtc::Logger& mc_control::MCController::logger ()
Returns mc_rtc::Logger instance.
observerPipeline() [1/4]
const mc_observers::ObserverPipeline& mc_control::MCController::observerPipeline (const std::string & name) const
Provides const access to a state-observation pipeline.
Exceptions
if no pipeline with that name exist
observerPipeline() [2/4]
mc_observers::ObserverPipeline& mc_control::MCController::observerPipeline (const std::string & name)
Non-const variant.
observerPipeline() [3/4]
const mc_observers::ObserverPipeline& mc_control::MCController::observerPipeline () const
Provides const access to the main observer pipeline (first pipeline)
Exceptions
if this controller does not have any pipeline
observerPipeline() [4/4]
mc_observers::ObserverPipeline& mc_control::MCController::observerPipeline ()
Non-const variant.
observerPipelines() [1/2]
const std::vector<mc_observers::ObserverPipeline>& mc_control::MCController::observerPipelines () const
Provides const access to the state observation pipelines defined in this controller.
observerPipelines() [2/2]
std::vector<mc_observers::ObserverPipeline>& mc_control::MCController::observerPipelines ()
Non-const variant.
realRobot() [1/4]
const mc_rbdyn::Robot& mc_control::MCController::realRobot () const
Return the main mc_rbdyn::Robot real robot instance.
realRobot() [2/4]
mc_rbdyn::Robot& mc_control::MCController::realRobot ()
Non-const variant of realRobot().
realRobot() [3/4]
const mc_rbdyn::Robot& mc_control::MCController::realRobot (const std::string & name) const
Return the mc_rbdyn::Robot controlled by this controller.
Exceptions
std::runtime_error if the robot does not exist
realRobot() [4/4]
mc_rbdyn::Robot& mc_control::MCController::realRobot (const std::string & name)
Non-const variant of realRobot(name).
realRobots() [1/2]
const mc_rbdyn::Robots& mc_control::MCController::realRobots () const
Return the mc_rbdyn::Robots real robots instance.
realRobots() [2/2]
mc_rbdyn::Robots& mc_control::MCController::realRobots ()
Non-const variant of realRobots().
removeRobot()
void mc_control::MCController::removeRobot (const std::string & name)
Remove a robot from the controller.
Parameters
name Name of the robot to remove
reset()
virtual void mc_control::MCController::reset (const ControllerResetData & reset_data) virtual
Reset the controller with data provided by ControllerResetData.
This is called at two possible points during a simulation/live execution:
Actual start
Switch from a previous (MCController-like) controller In the first case, the data comes from the simulation/controller. In the second case, the data comes from the previous MCController instance.
Parameters
reset_data Contains information allowing to reset the controller properly
Note
The default implementation reset the main robot's state to that provided by reset_data (with a null speed/acceleration). It maintains the contacts as they were set by the controller previously.
Exceptions
if the main robot is not supported (see supported_robots())
Reimplemented in mc_control::fsm::Controller, and mc_control::MCPythonController.
resetObserverPipelines()
virtual bool mc_control::MCController::resetObserverPipelines () virtual
Reset the observers.
This function is called after the reset() function.
Returns
True when all observers have been succesfully reset.
robot() [1/4]
const mc_rbdyn::Robot& mc_control::MCController::robot () const
Return the main robot (first robot provided in the constructor)
Referenced by mc_control::fsm::Controller::running().
robot() [2/4]
const mc_rbdyn::Robot& mc_control::MCController::robot (const std::string & name) const
Return the mc_rbdyn::Robot controlled by this controller.
Exceptions
std::runtime_error if the robot does not exist
robot() [3/4]
mc_rbdyn::Robot& mc_control::MCController::robot (const std::string & name)
Non-const variant of robot(name).
robot() [4/4]
mc_rbdyn::Robot& mc_control::MCController::robot ()
Non-const variant of robot().
robots() [1/2]
const mc_rbdyn::Robots& mc_control::MCController::robots () const
Return the mc_rbdyn::Robots controlled by this controller.
robots() [2/2]
mc_rbdyn::Robots& mc_control::MCController::robots ()
Non-const variant of robots().
run() [1/2]
virtual bool mc_control::MCController::run () virtual
This function is called at each time step of the process driving the robot (i.e.
simulation or robot's controller). This function is the most likely to be overriden for complex controller behaviours.
Returns
True if the solver succeeded, false otherwise
Note
This is meant to run in real-time hence some precaution should apply (e.g. no i/o blocking calls, no thread instantiation and such)
The default implementation does the bare minimum (i.e. call run on QPSolver) It is recommended to use it in your override.
Reimplemented in mc_control::fsm::Controller, and mc_control::MCPythonController.
run() [2/2]
bool mc_control::MCController::run (mc_solver::FeedbackType fType)
Can be called in derived class instead of run to use a feedback strategy different from the default one.
Parameters
fType Type of feedback used in the solver
runObserverPipelines()
virtual bool mc_control::MCController::runObserverPipelines () virtual
This function is called before the run() function at each time step of the process driving the robot (i.e.
simulation or robot's controller). The default behaviour is to call the run() function of each loaded observer and update the realRobot instance when desired.
This is meant to run in real-time hence some precaution should apply (e.g. no i/o blocking calls, no thread instantiation and such)
Note
Some estimators are likely to require extra information from the control. Each observer has access to the MCController instance, and may access all information available from it (robots, etc). In addition some observers may require additional information that is not part of the MCController instance. In that case, it may be provided though the Datastore (see each observer's documentation for specific requirements).
If the default pipeline behaviour does not suit you, you may override this method.
Returns
true if all observers ran as expected, false otherwise
send()
virtual const mc_solver::QPResultMsg& mc_control::MCController::send (const double & t) virtual
Gives access to the result of the QP execution.
Parameters
t Unused at the moment
solver() [1/2]
const mc_solver::QPSolver& mc_control::MCController::solver () const
Return the mc_solver::QPSolver instance attached to this controller.
solver() [2/2]
mc_solver::QPSolver& mc_control::MCController::solver ()
Non-const variant of solver().
stop()
virtual void mc_control::MCController::stop () virtual
This function is called when the controller is stopped.
The default implementation does nothing.
For example, it can be overriden to signal threads launched by the controller to pause.
supported_robots()
virtual void mc_control::MCController::supported_robots (std::vector< std::string > & out) const virtual
Returns a list of robots supported by the controller.
Parameters
out Vector of supported robots designed by name (as returned by RobotModule::name())
Note
Default implementation returns an empty list which indicates that all robots are supported.
If the list is not empty, only the robots in that list are allowed to be used with the controller. The main robot will be checked against the list of supported robots upon call to reset(), and an exception will be thrown if the robot is not supported.
Friends And Related Function Documentation
MCGlobalController
friend struct MCGlobalController friend
Member Data Documentation
compoundJointConstraint
std::unique_ptr<mc_solver::CompoundJointConstraint> mc_control::MCController::compoundJointConstraint
Compound joint constraint for the main robot.
config_
mc_rtc::Configuration mc_control::MCController::config_ protected
Keep track of the configuration of the controller.
contactConstraint
mc_solver::ContactConstraint mc_control::MCController::contactConstraint
Contact constraint for the main robot.
datastore_
mc_rtc::DataStore mc_control::MCController::datastore_ protected
DataStore to share variables/objects between different parts of the framework (states...)
dynamicsConstraint
mc_solver::DynamicsConstraint mc_control::MCController::dynamicsConstraint
Dynamics constraints for the main robot.
gui_
std::shared_ptr<mc_rtc::gui::StateBuilder> mc_control::MCController::gui_ protected
GUI state builder.
kinematicsConstraint
mc_solver::KinematicsConstraint mc_control::MCController::kinematicsConstraint
Kinematics constraints for the main robot.
logger_
std::shared_ptr<mc_rtc::Logger> mc_control::MCController::logger_ protected
Logger provided by MCGlobalController.
name_
std::string mc_control::MCController::name_
observerPipelines_
std::vector<mc_observers::ObserverPipeline> mc_control::MCController::observerPipelines_ protected
State observation pipelines for this controller.
postureTask
std::shared_ptr<mc_tasks::PostureTask> mc_control::MCController::postureTask
Posture task for the main robot.
qpsolver
std::shared_ptr<mc_solver::QPSolver> mc_control::MCController::qpsolver protected
QP solver.
selfCollisionConstraint
mc_solver::CollisionsConstraint mc_control::MCController::selfCollisionConstraint
Self collisions constraint for the main robot.
timeStep
const double mc_control::MCController::timeStep
Controller timestep.