mc_filter::LowPass< T > Struct Template Reference
mc_filter::LowPass< T > Struct Template Reference
Low-pass filter from series of velocity measurements.
#include <mc_filter/LowPass.h>
Public Member Functions
LowPass (double dt, double period=0)
Constructor with cutoff period.
double cutoffPeriod () const
Get cutoff period.
void cutoffPeriod (double period)
Set cutoff period.
void reset (const T &value)
Reset position to an initial rest value.
void update (const T &newValue)
Update velocity estimate from new position value.
const T & eval () const
Get filtered velocity.
double dt () const
Protected Attributes
double dt_ = 0.005
Detailed Description
template<typename T>
struct mc_filter::LowPass< T >
Low-pass filter from series of velocity measurements.
Expects T to have:
T::Zero() static method (e.g Eigen::Vector3d, etc)
Constructor & Destructor Documentation
LowPass()
template<typename T> mc_filter::LowPass< T >::LowPass (double dt, double period = 0) inline
Constructor with cutoff period.
Parameters
dt Sampling period.
period Cutoff period.
Member Function Documentation
cutoffPeriod() [1/2]
template<typename T> double mc_filter::LowPass< T >::cutoffPeriod () const inline
Get cutoff period.
cutoffPeriod() [2/2]
template<typename T> void mc_filter::LowPass< T >::cutoffPeriod (double period) inline
Set cutoff period.
Parameters
period New cutoff period.
Note
period is explicitely enforced to respect the Nyquist–Shannon sampling theorem, that is T is at least 2*timestep.
dt()
template<typename T> double mc_filter::LowPass< T >::dt () const inline
Referenced by mc_filter::LowPassFiniteDifferences< T >::update().
eval()
template<typename T> const T& mc_filter::LowPass< T >::eval () const inline
Get filtered velocity.
reset()
template<typename T> void mc_filter::LowPass< T >::reset (const T & value) inline
Reset position to an initial rest value.
Parameters
pos New position.
Referenced by mc_filter::LowPass< sva::MotionVecd >::LowPass(), mc_filter::LowPassFiniteDifferences< T >::LowPassFiniteDifferences(), and mc_filter::LowPassFiniteDifferences< T >::reset().
update()
template<typename T> void mc_filter::LowPass< T >::update (const T & newValue) inline
Update velocity estimate from new position value.
Parameters
newPos New observed position.
Referenced by mc_filter::LowPassFiniteDifferences< T >::update().
Member Data Documentation
dt_
template<typename T> double mc_filter::LowPass< T >::dt_ = 0.005 protected
Referenced by mc_filter::LowPass< sva::MotionVecd >::cutoffPeriod(), mc_filter::LowPass< sva::MotionVecd >::dt(), and mc_filter::LowPass< sva::MotionVecd >::update().