mc_rbdyn::Device Struct Reference
mc_rbdyn::Device Struct Reference abstract
This struct represents a generic device attached to a robot.
#include <mc_rbdyn/Device.h>
Public Member Functions
Device (const std::string &name, const std::string &parent, const sva::PTransformd &X_p_s)
virtual ~Device () noexcept=default
const std::string & name () const
Returns the name of the sensor.
const std::string & type () const
Returns the type of the sensor.
const std::string & parent () const
Returns the parent body of the sensor.
const sva::PTransformd & X_p_s () const
Returns the transformation from the parent body to the sensor.
sva::PTransformd X_0_s (const mc_rbdyn::Robot &robot) const
Returns the sensor position in the inertial frame (convenience function)
virtual DevicePtr clone () const =0
Protected Attributes
std::string type_
Type of sensor as string.
std::string name_
Name of the sensor.
std::string parent_
Parent body of the sensor.
sva::PTransformd X_p_s_
Transformation from the parent body frame to the sensor frame.
Detailed Description
This struct represents a generic device attached to a robot.
This is a barebone interface meant to be derived by a concrete device implementation
Constructor & Destructor Documentation
Device()
mc_rbdyn::Device::Device (const std::string & name, const std::string & parent, const sva::PTransformd & X_p_s)
~Device()
virtual mc_rbdyn::Device::~Device () virtual default noexcept
Member Function Documentation
clone()
virtual DevicePtr mc_rbdyn::Device::clone () const pure virtual
Implemented in mc_rbdyn::ForceSensor, and mc_rbdyn::BodySensor.
name()
const std::string& mc_rbdyn::Device::name () const inline
Returns the name of the sensor.
parent()
const std::string& mc_rbdyn::Device::parent () const inline
Returns the parent body of the sensor.
Referenced by mc_rbdyn::BodySensor::parentBody(), and mc_rbdyn::ForceSensor::parentBody().
type()
const std::string& mc_rbdyn::Device::type () const inline
Returns the type of the sensor.
X_0_s()
sva::PTransformd mc_rbdyn::Device::X_0_s (const mc_rbdyn::Robot & robot) const
Returns the sensor position in the inertial frame (convenience function)
Referenced by mc_rbdyn::ForceSensor::X_0_f().
X_p_s()
const sva::PTransformd& mc_rbdyn::Device::X_p_s () const inline
Returns the transformation from the parent body to the sensor.
Referenced by mc_rbdyn::BodySensor::X_b_s(), and mc_rbdyn::ForceSensor::X_p_f().
Member Data Documentation
name_
std::string mc_rbdyn::Device::name_ protected
Name of the sensor.
parent_
std::string mc_rbdyn::Device::parent_ protected
Parent body of the sensor.
type_
std::string mc_rbdyn::Device::type_ protected
Type of sensor as string.
X_p_s_
sva::PTransformd mc_rbdyn::Device::X_p_s_ protected
Transformation from the parent body frame to the sensor frame.