mc_rbdyn::lipm_stabilizer::StabilizerConfiguration Struct Reference
mc_rbdyn::lipm_stabilizer::StabilizerConfiguration Struct Reference
Configuration of the LIPMStabilizer.
#include <mc_rbdyn/lipm_stabilizer/StabilizerConfiguration.h>
Public Member Functions
void load (const mc_rtc::Configuration &config)
mc_rtc::Configuration save () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW FDQPWeights fdqpWeights
double friction = 0.7
Friction coefficient.
std::string leftFootSurface
Surface name for the left foot.
std::string rightFootSurface
Surface name for the right foot.
Eigen::Vector2d copAdmittance = Eigen::Vector2d::Zero()
Admittance gains for foot damping control.
sva::MotionVecd copMaxVel {{0.3, 0.3, 0.3}, {0.1, 0.1, 0.1}}
Maximal velocity of the cop tasks.
ZMPCCConfiguration zmpcc
Configuration of ZMPCC (CoM admittance)
double dfzAdmittance = 1e-4
Admittance for foot force difference control.
double dfzDamping = 0.
Damping term in foot force difference control.
double dcmPropGain = 1.
Proportional gain on DCM error.
double dcmIntegralGain = 5.
Integral gain on DCM error.
double dcmDerivGain = 0.
Derivative gain on DCM error.
double dcmIntegratorTimeConstant
Time window for exponential moving average filter of the DCM integrator.
double dcmDerivatorTimeConstant = 1.
Time window for the stationary offset filter of the DCM derivator.
std::vector< std::string > comActiveJoints
Joints used by CoM IK task.
Eigen::Vector3d comStiffness = {1000., 1000., 100.}
Stiffness of CoM IK task.
double comWeight = 1000.
Weight of CoM IK task.
double comHeight = 0.84
Desired height of the CoM.
std::string torsoBodyName
Name of the torso body.
double torsoPitch = 0
Target world pitch angle for the torso.
double torsoStiffness = 10
Stiffness of the torso task.
double torsoWeight = 100
Weight of the torso task.
double pelvisStiffness = 10
Stiffness of the pelvis task.
double pelvisWeight = 100
Weight of the torso task.
sva::MotionVecd contactDamping
Damping coefficients of the contacts CoP tasks.
sva::MotionVecd contactStiffness = {{1, 1, 1}, {1, 1, 1}}
Stiffness coefficients of the contacts CoP tasks.
double contactWeight = 100000.
Weight of contact IK tasks.
double vdcFrequency = 1.
Frequency used in double-support vertical drift compensation.
double vdcStiffness = 1000.
Stiffness used in single-support vertical drift compensation.
Detailed Description
Configuration of the LIPMStabilizer.
This configuration is meant to be overriden from the RobotModule, and the user YAML configuration of the stabilizer task.
Note
Developper note: Do not change the default gains here, it is likely that robot modules and users do not override every single parameter value, and modifying their default might have serious consequences.
Member Function Documentation
load()
void mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::load (const mc_rtc::Configuration & config) inline
References mc_rtc::Configuration::has().
Referenced by mc_rtc::ConfigurationLoader< mc_rbdyn::lipm_stabilizer::StabilizerConfiguration >::load().
save()
mc_rtc::Configuration mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::save () const inline
References mc_rtc::Configuration::add().
Referenced by mc_rtc::ConfigurationLoader< mc_rbdyn::lipm_stabilizer::StabilizerConfiguration >::save().
Member Data Documentation
comActiveJoints
std::vector<std::string> mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::comActiveJoints
Joints used by CoM IK task.
comHeight
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::comHeight = 0.84
Desired height of the CoM.
comStiffness
Eigen::Vector3d mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::comStiffness = {1000., 1000., 100.}
Stiffness of CoM IK task.
comWeight
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::comWeight = 1000.
Weight of CoM IK task.
contactDamping
sva::MotionVecd mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::contactDamping
Initial value:
{{300, 300, 300},
                                 {300, 300, 300}}
Damping coefficients of the contacts CoP tasks.
contactStiffness
sva::MotionVecd mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::contactStiffness = {{1, 1, 1}, {1, 1, 1}}
Stiffness coefficients of the contacts CoP tasks.
contactWeight
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::contactWeight = 100000.
Weight of contact IK tasks.
copAdmittance
Eigen::Vector2d mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::copAdmittance = Eigen::Vector2d::Zero()
Admittance gains for foot damping control.
copMaxVel
sva::MotionVecd mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::copMaxVel {{0.3, 0.3, 0.3}, {0.1, 0.1, 0.1}}
Maximal velocity of the cop tasks.
dcmDerivatorTimeConstant
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dcmDerivatorTimeConstant = 1.
Time window for the stationary offset filter of the DCM derivator.
dcmDerivGain
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dcmDerivGain = 0.
Derivative gain on DCM error.
dcmIntegralGain
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dcmIntegralGain = 5.
Integral gain on DCM error.
dcmIntegratorTimeConstant
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dcmIntegratorTimeConstant
Initial value:
=
      15.
Time window for exponential moving average filter of the DCM integrator.
dcmPropGain
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dcmPropGain = 1.
Proportional gain on DCM error.
dfzAdmittance
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dfzAdmittance = 1e-4
Admittance for foot force difference control.
dfzDamping
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::dfzDamping = 0.
Damping term in foot force difference control.
fdqpWeights
EIGEN_MAKE_ALIGNED_OPERATOR_NEW FDQPWeights mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::fdqpWeights
friction
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::friction = 0.7
Friction coefficient.
Same for both feet
leftFootSurface
std::string mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::leftFootSurface
Surface name for the left foot.
Origin should be at foot's center
pelvisStiffness
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::pelvisStiffness = 10
Stiffness of the pelvis task.
pelvisWeight
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::pelvisWeight = 100
Weight of the torso task.
Should be much lower than CoM and Contacts
rightFootSurface
std::string mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::rightFootSurface
Surface name for the right foot.
Origin should be at foot's center
torsoBodyName
std::string mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::torsoBodyName
Name of the torso body.
torsoPitch
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::torsoPitch = 0
Target world pitch angle for the torso.
torsoStiffness
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::torsoStiffness = 10
Stiffness of the torso task.
torsoWeight
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::torsoWeight = 100
Weight of the torso task.
Should be much lower than CoM and Contacts
vdcFrequency
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::vdcFrequency = 1.
Frequency used in double-support vertical drift compensation.
vdcStiffness
double mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::vdcStiffness = 1000.
Stiffness used in single-support vertical drift compensation.
zmpcc
ZMPCCConfiguration mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::zmpcc
Configuration of ZMPCC (CoM admittance)