mc_rbdyn::Robot Struct Reference
mc_rbdyn::Robot Struct Reference
#include <mc_rbdyn/Robot.h>
Public Types
using S_ObjectPtr = std::shared_ptr< sch::S_Object >
using convex_pair_t = std::pair< std::string, S_ObjectPtr >
Public Member Functions
Robot (Robot &&)=default
Robot & operator= (Robot &&)=default
const std::string & name () const
Returns the name of the robot.
const RobotModule & module () const
Retrieve the associated RobotModule.
bool hasJoint (const std::string &name) const
Returns true if the robot has a joint named name.
bool hasBody (const std::string &name) const
Returns true if the robot has a body named name.
bool hasSurface (const std::string &surface) const
Check if a surface surface exists.
mc_rbdyn::Surface & surface (const std::string &sName)
Access a surface by its name sName.
const mc_rbdyn::Surface & surface (const std::string &sName) const
Access a surface by its name sName (const)
sva::PTransformd surfacePose (const std::string &sName) const
Get the pose of a surface frame with respect to the inertial frame.
mc_rbdyn::Surface & copySurface (const std::string &sName, const std::string &name)
Copy an existing surface with a new name.
void addSurface (mc_rbdyn::SurfacePtr surface, bool doNotReplace=true)
Adds a surface with a new name.
const std::map< std::string, mc_rbdyn::SurfacePtr > & surfaces () const
Returns all available surfaces.
std::vector< std::string > availableSurfaces () const
Returns a list of available surfaces.
bool hasConvex (const std::string &name) const
Check if a convex name exists.
convex_pair_t & convex (const std::string &cName)
Access a convex named cName.
const convex_pair_t & convex (const std::string &cName) const
Access a convex named cName (const)
const std::map< std::string, convex_pair_t > & convexes () const
Access all convexes available in this robot.
void addConvex (const std::string &name, const std::string &body, S_ObjectPtr convex, const sva::PTransformd &X_b_c=sva::PTransformd::Identity())
Add a convex online.
void removeConvex (const std::string &name)
Remove a given convex.
const sva::PTransformd & bodyTransform (const std::string &bName) const
Access transformation from body bName to original base.
const sva::PTransformd & bodyTransform (int bodyIndex) const
Access body transform by index.
const std::vector< sva::PTransformd > & bodyTransforms () const
Access body transform vector.
const sva::PTransformd & collisionTransform (const std::string &cName) const
Access transformation between the collision mesh and the body.
void loadRSDFFromDir (const std::string &surfaceDir)
Load surfaces from the directory surfaceDir.
std::map< std::string, std::vector< double > > stance () const
Return the robot's default stance (e.g.
unsigned int robotIndex () const
Access the robot's index in robots()
void forwardKinematics ()
Apply forward kinematics to the robot.
void forwardKinematics (rbd::MultiBodyConfig &mbc) const
Apply forward kinematics to mbc using the robot's mb()
void forwardVelocity ()
Apply forward velocity to the robot.
void forwardVelocity (rbd::MultiBodyConfig &mbc) const
Apply forward velocity to mbc using the robot's mb()
void forwardAcceleration (const sva::MotionVecd &A_0=sva::MotionVecd(Eigen::Vector6d::Zero()))
Apply forward acceleration to the robot.
void forwardAcceleration (rbd::MultiBodyConfig &mbc, const sva::MotionVecd &A_0=sva::MotionVecd(Eigen::Vector6d::Zero())) const
Apply forward acceleration to mbc using the robot's mb()
void eulerIntegration (double step)
Apply Euler integration to the robot using step timestep.
void eulerIntegration (rbd::MultiBodyConfig &mbc, double step) const
Apply Euler integration to mbc using the robot's mb() and step timestep.
const sva::PTransformd & posW () const
Return the robot's global pose.
void posW (const sva::PTransformd &pt)
Set the robot's global pose.
void velW (const sva::MotionVecd &vel)
Update the robot's floating base velocity.
const sva::MotionVecd & velW () const
Return the robot's floating base velocity expressed in the inertial frame.
void accW (const sva::MotionVecd &acc)
Update the robot's floating base acceleration.
const sva::MotionVecd accW () const
Return the robot's floating base acceleration expressed in the inertial frame.
mc_control::Gripper & gripper (const std::string &gripper)
Access a gripper by name.
const std::unordered_map< std::string, mc_control::GripperPtr > & grippersByName () const
const std::vector< mc_control::GripperRef > & grippers () const
Access all grippers.
Body sensors
These functions are related to force sensors
BodySensor & bodySensor ()
Return the first BodySensor in the robot.
const BodySensor & bodySensor () const
Return the first BodySensor in the robot (const)
bool hasBodySensor (const std::string &name) const
Return true if the robot has a body sensor named name.
bool bodyHasBodySensor (const std::string &body) const
Return true if the specified body has a body sensor attached to it.
BodySensor & bodySensor (const std::string &name)
Return a specific BobySensor by name.
const BodySensor & bodySensor (const std::string &name) const
Return a specific BodySensor by name (const)
BodySensor & bodyBodySensor (const std::string &name)
Return a specific BodySensor by body name.
const BodySensor & bodyBodySensor (const std::string &name) const
Return a specific BodySensor by body name (const)
BodySensorVector & bodySensors ()
Return all body sensors.
const BodySensorVector & bodySensors () const
Return all body sensors (const)
Returns the joint index of joint named
Exceptions
If the joint does not exist within the robot.
unsigned int jointIndexByName (const std::string &name) const
int jointIndexInMBC (size_t jointIndex) const
Returns the joint index in the mbc of the joint with index jointIndex in refJointOrder.
Returns the body index of joint named
Exceptions
If the body does not exist within the robot.
unsigned int bodyIndexByName (const std::string &name) const
rbd::MultiBody & mb ()
Access MultiBody representation of the robot.
const rbd::MultiBody & mb () const
Access MultiBody representation of the robot (const)
rbd::MultiBodyConfig & mbc ()
Access MultiBodyConfig of the robot's mb()
const rbd::MultiBodyConfig & mbc () const
Access MultiBodyConfig of the robot's mb() (const)
rbd::MultiBodyGraph & mbg ()
Access MultiBodyGraph that generated the robot's mb()
const rbd::MultiBodyGraph & mbg () const
Access MultiBodyGraph that generated the robot's mb() (const)
const std::vector< std::vector< double > > & q () const
Equivalent to robot.mbc().q (const)
const std::vector< std::vector< double > > & alpha () const
Equivalent to robot.mbc().alpha (const)
const std::vector< std::vector< double > > & alphaD () const
Equivalent to robot.mbc().alphaD (const)
const std::vector< std::vector< double > > & jointTorque () const
Equivalent to robot.mbc().jointTorque (const)
const std::vector< sva::PTransformd > & bodyPosW () const
Equivalent to robot.mbc().bodyPosW (const)
const std::vector< sva::MotionVecd > & bodyVelW () const
Equivalent to robot.mbc().bodyVelW (const)
const std::vector< sva::MotionVecd > & bodyVelB () const
Equivalent to robot.mbc().bodyVelB (const)
const std::vector< sva::MotionVecd > & bodyAccB () const
Equivalent to robot.mbc().bodyAccB (const)
std::vector< std::vector< double > > & q ()
Equivalent to robot.mbc().q.
std::vector< std::vector< double > > & alpha ()
Equivalent to robot.mbc().alpha.
std::vector< std::vector< double > > & alphaD ()
Equivalent to robot.mbc().alphaD.
std::vector< std::vector< double > > & jointTorque ()
Equivalent to robot.mbc().jointTorque.
std::vector< sva::PTransformd > & bodyPosW ()
Equivalent to robot.mbc().bodyPosW.
std::vector< sva::MotionVecd > & bodyVelW ()
Equivalent to robot.mbc().bodyVelW.
std::vector< sva::MotionVecd > & bodyVelB ()
Equivalent to robot.mbc().bodyVelB.
std::vector< sva::MotionVecd > & bodyAccB ()
Equivalent to robot.mbc().bodyAccB.
const sva::PTransformd & bodyPosW (const std::string &name) const
Access the position of body name in world coordinates.
sva::PTransformd X_b1_b2 (const std::string &b1, const std::string &b2) const
Relative transformation X_b1_b2 from body b1 to body b2.
const sva::MotionVecd & bodyVelW (const std::string &name) const
Access the velocity of body name in world coordinates.
const sva::MotionVecd & bodyVelB (const std::string &name) const
Access the velocity of body name in body coordinates.
const sva::MotionVecd & bodyAccB (const std::string &name) const
Access the acceleration of body name in body coordinates.
Eigen::Vector3d com () const
Compute and returns the current robot's CoM.
Eigen::Vector3d comVelocity () const
Compute and returns the current robot's CoM velocity.
Eigen::Vector3d comAcceleration () const
Compute and returns the current robot's CoM acceleration.
sva::ForceVecd surfaceWrench (const std::string &surfaceName) const
Compute the gravity-free wrench in surface frame.
sva::ForceVecd bodyWrench (const std::string &bodyName) const
Compute the gravity-free wrench in body frame.
Eigen::Vector2d cop (const std::string &surfaceName, double min_pressure=0.5) const
Compute the cop in surface frame computed from gravity-free force measurements.
Eigen::Vector3d copW (const std::string &surfaceName, double min_pressure=0.5) const
Compute the cop in inertial frame compute from gravity-free force measurements.
sva::ForceVecd netWrench (const std::vector< std::string > &sensorNames) const
Computes net total wrench from a list of sensors.
Eigen::Vector3d zmp (const sva::ForceVecd &netTotalWrench, const Eigen::Vector3d &plane_p, const Eigen::Vector3d &plane_n, double minimalNetNormalForce=1.) const
Actual ZMP computation from net total wrench and the ZMP plane.
Eigen::Vector3d zmp (const sva::ForceVecd &netTotalWrench, const sva::PTransformd &zmpFrame, double minimalNetNormalForce=1.) const
ZMP computation from net total wrench and a frame.
Eigen::Vector3d zmp (const std::vector< std::string > &sensorNames, const Eigen::Vector3d &plane_p, const Eigen::Vector3d &plane_n, double minimalNetNormalForce=1.) const
Computes the ZMP from sensor names and a plane.
Eigen::Vector3d zmp (const std::vector< std::string > &sensorNames, const sva::PTransformd &zmpFrame, double minimalNetNormalForce=1.) const
Computes the ZMP from sensor names and a frame.
const std::vector< std::vector< double > > & ql () const
Access the robot's angular lower limits (const)
const std::vector< std::vector< double > > & qu () const
Access the robot's angular upper limits (const)
const std::vector< std::vector< double > > & vl () const
Access the robot's angular lower velocity limits (const)
const std::vector< std::vector< double > > & vu () const
Access the robot's angular upper velocity limits (const)
const std::vector< std::vector< double > > & al () const
Access the robot's angular lower acceleration limits (const)
const std::vector< std::vector< double > > & au () const
Access the robot's angular upper acceleration limits (const)
const std::vector< std::vector< double > > & tl () const
Access the robot's angular lower torque limits (const)
const std::vector< std::vector< double > > & tu () const
Access the robot's angular upper torque limits (const)
const std::vector< std::vector< double > > & tdl () const
Access the robot's angular lower torque-derivative limits (const)
const std::vector< std::vector< double > > & tdu () const
Access the robot's angular upper torque-derivative limits (const)
std::vector< std::vector< double > > & ql ()
Access the robot's angular lower limits.
std::vector< std::vector< double > > & qu ()
Access the robot's angular upper limits.
std::vector< std::vector< double > > & vl ()
Access the robot's angular lower velocity limits.
std::vector< std::vector< double > > & vu ()
Access the robot's angular upper velocity limits.
std::vector< std::vector< double > > & al ()
Access the robot's angular lower acceleration limits.
std::vector< std::vector< double > > & au ()
Access the robot's angular upper acceleration limits.
std::vector< std::vector< double > > & tl ()
Access the robot's angular lower torque limits.
std::vector< std::vector< double > > & tu ()
Access the robot's angular upper torque limits.
std::vector< std::vector< double > > & tdl ()
Access the robot's angular lower torque-derivative limits.
std::vector< std::vector< double > > & tdu ()
Access the robot's angular upper torque-derivative limits.
const std::vector< Flexibility > & flexibility () const
Return the flexibilities of the robot (const)
std::vector< Flexibility > & flexibility ()
Return the flexibilities of the robot.
void zmpTarget (const Eigen::Vector3d &zmp)
Set the target zmp defined with respect to base-link.
const Eigen::Vector3d & zmpTarget () const
Returns the target zmp.
double mass () const
Compute and returns the mass of the robot.
Joint sensors
These functions give information about joints' status
const std::vector< double > & encoderValues () const
Return the encoder values.
void encoderValues (const std::vector< double > &encoderValues)
Set the encoder values.
const std::vector< double > & encoderVelocities () const
Return the encoder velocities.
void encoderVelocities (const std::vector< double > &encoderVelocities)
Set the encoder velocities.
const std::vector< double > & flexibilityValues () const
Return the flexibilities values.
void flexibilityValues (const std::vector< double > &flexibilityValues)
Set the flexibilities values.
const std::vector< double > & jointTorques () const
Return the joint torques from sensors.
void jointTorques (const std::vector< double > &jointTorques)
Set joint torques from sensors.
const std::vector< std::string > & refJointOrder () const
Return the reference joint order for this robot.
Force sensors
These functions are related to force sensors
bool hasForceSensor (const std::string &name) const
Check if a force sensor exists.
bool bodyHasForceSensor (const std::string &body) const
Check if the body has a force sensor directly attached to it.
bool surfaceHasForceSensor (const std::string &surface) const
Checks if the surface has a force sensor directly attached to it.
bool bodyHasIndirectForceSensor (const std::string &body) const
Check if the body has a force sensor attached to it (directly or indirectly)
bool surfaceHasIndirectForceSensor (const std::string &surface) const
Check if the surface has a force sensor attached to it (directly or indirectly)
ForceSensor & forceSensor (const std::string &name)
Return a force sensor by name.
const ForceSensor & forceSensor (const std::string &name) const
Const variant.
ForceSensor & bodyForceSensor (const std::string &body)
Return a force sensor attached to the provided body.
const ForceSensor & bodyForceSensor (const std::string &body) const
Const variant.
ForceSensor & surfaceForceSensor (const std::string &surfaceName)
Return a force sensor attached to the provided surface.
const ForceSensor & surfaceForceSensor (const std::string &surfaceName) const
Const variant.
ForceSensor & indirectBodyForceSensor (const std::string &body)
Return a force sensor directly or indirectly attached to a body.
const ForceSensor & indirectBodyForceSensor (const std::string &body) const
Const variant.
ForceSensor & indirectSurfaceForceSensor (const std::string &surface)
Return a force sensor directly or indirectly attached to a surface.
const ForceSensor & indirectSurfaceForceSensor (const std::string &surface) const
Const variant.
std::vector< ForceSensor > & forceSensors ()
Returns all force sensors.
const std::vector< ForceSensor > & forceSensors () const
Returns all force sensors (const)
Devices
These functions are related to generic devices handling
template<typename T >
bool hasDevice (const std::string &name) const
Returns true if a generic device of type T and named name exists in the robot.
template<typename T >
bool hasSensor (const std::string &name) const
Alias for.
template<typename T >
const T & device (const std::string &name) const
Get a generic device of type T named name.
template<typename T >
T & device (const std::string &name)
Non-const variant.
template<typename T >
const T & sensor (const std::string &name) const
Alias for.
template<typename T >
T & sensor (const std::string &name)
Alias for.
void addDevice (DevicePtr device)
Add a generic device to the robot.
void addSensor (SensorPtr sensor)
Alias for.
Protected Member Functions
Robot (const std::string &name, Robots &robots, unsigned int robots_idx, bool loadFiles, const sva::PTransformd *base=nullptr, const std::string &baseName="")
Invoked by Robots parent instance after mb/mbc/mbg/RobotModule are stored.
void copy (Robots &robots, const std::string &copyName, unsigned int robots_idx, const Base &base) const
Copy existing Robot with a new base.
void copy (Robots &robots, const std::string &copyName, unsigned int robots_idx) const
Copy existing Robot.
void fixSurfaces ()
Used to set the surfaces' X_b_s correctly.
void fixCollisionTransforms ()
Used to set the collision transforms correctly.
std::string findIndirectForceSensorBodyName (const std::string &bodyName) const
Finds the name of the body to which a force sensor is attached, starting from the provided body and going up the kinematic tree.
Friends
struct Robots
Member Typedef Documentation
convex_pair_t
using mc_rbdyn::Robot::convex_pair_t = std::pair<std::string, S_ObjectPtr>
S_ObjectPtr
using mc_rbdyn::Robot::S_ObjectPtr = std::shared_ptr<sch::S_Object>
Constructor & Destructor Documentation
Robot() [1/2]
mc_rbdyn::Robot::Robot (Robot &&) default
Robot() [2/2]
mc_rbdyn::Robot::Robot (const std::string & name, Robots & robots, unsigned int robots_idx, bool loadFiles, const sva::PTransformd * base = nullptr, const std::string & baseName = "") protected
Invoked by Robots parent instance after mb/mbc/mbg/RobotModule are stored.
When loadFiles is set to false, the convex and surfaces files are not loaded. This is used when copying one robot into another.
Member Function Documentation
accW() [1/2]
void mc_rbdyn::Robot::accW (const sva::MotionVecd & acc)
Update the robot's floating base acceleration.
Parameters
vel New floating base acceleration in the inertial frame.
Note
This function takes care of calling rbd::forwardAcceleration
accW() [2/2]
const sva::MotionVecd mc_rbdyn::Robot::accW () const
Return the robot's floating base acceleration expressed in the inertial frame.
addConvex()
void mc_rbdyn::Robot::addConvex (const std::string & name, const std::string & body, S_ObjectPtr convex, const sva::PTransformd & X_b_c = sva::PTransformd::Identity())
Add a convex online.
This has no effect if name is already a convex of the robot
Parameters
name Name of the convex
body Name of the convex's parent body
convex sch::Object object representing the convex
X_b_c Transformation fro the convex's parent body to the convex
addDevice()
void mc_rbdyn::Robot::addDevice (DevicePtr device)
Add a generic device to the robot.
addSensor()
void mc_rbdyn::Robot::addSensor (SensorPtr sensor) inline
Alias for.
See also
addDevice
addSurface()
void mc_rbdyn::Robot::addSurface (mc_rbdyn::SurfacePtr surface, bool doNotReplace = true)
Adds a surface with a new name.
al() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::al () const
Access the robot's angular lower acceleration limits (const)
al() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::al ()
Access the robot's angular lower acceleration limits.
alpha() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::alpha () const
Equivalent to robot.mbc().alpha (const)
alpha() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::alpha ()
Equivalent to robot.mbc().alpha.
alphaD() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::alphaD () const
Equivalent to robot.mbc().alphaD (const)
alphaD() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::alphaD ()
Equivalent to robot.mbc().alphaD.
au() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::au () const
Access the robot's angular upper acceleration limits (const)
au() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::au ()
Access the robot's angular upper acceleration limits.
availableSurfaces()
std::vector<std::string> mc_rbdyn::Robot::availableSurfaces () const
Returns a list of available surfaces.
bodyAccB() [1/3]
const std::vector<sva::MotionVecd>& mc_rbdyn::Robot::bodyAccB () const
Equivalent to robot.mbc().bodyAccB (const)
bodyAccB() [2/3]
std::vector<sva::MotionVecd>& mc_rbdyn::Robot::bodyAccB ()
Equivalent to robot.mbc().bodyAccB.
bodyAccB() [3/3]
const sva::MotionVecd& mc_rbdyn::Robot::bodyAccB (const std::string & name) const
Access the acceleration of body name in body coordinates.
Exceptions
If the body doest not exist within the robot
bodyBodySensor() [1/2]
BodySensor& mc_rbdyn::Robot::bodyBodySensor (const std::string & name)
Return a specific BodySensor by body name.
Parameters
name Name of the body
Exceptions
If there is no sensor attached to the body
bodyBodySensor() [2/2]
const BodySensor& mc_rbdyn::Robot::bodyBodySensor (const std::string & name) const
Return a specific BodySensor by body name (const)
bodyForceSensor() [1/2]
ForceSensor& mc_rbdyn::Robot::bodyForceSensor (const std::string & body)
Return a force sensor attached to the provided body.
Parameters
body Name of the body to which the sensor is attached
Returns
The attached sensor
Exceptions
If no sensor is directly attached to this body
See also
ForceSensor & indirectBodyForceSensor(const std::string & body); To get a sensor directly or indirectly attached to the body.
bodyForceSensor() [2/2]
const ForceSensor& mc_rbdyn::Robot::bodyForceSensor (const std::string & body) const
Const variant.
bodyHasBodySensor()
bool mc_rbdyn::Robot::bodyHasBodySensor (const std::string & body) const
Return true if the specified body has a body sensor attached to it.
Parameters
body Body to query
bodyHasForceSensor()
bool mc_rbdyn::Robot::bodyHasForceSensor (const std::string & body) const
Check if the body has a force sensor directly attached to it.
Parameters
body Name of the body to which the sensor is directly attached
See also
bodyHasIndirectForceSensor(const std::string &) if you wish to check whether a sensor is indirectly attached to a body
Returns
True if the body has a force sensor attached to it, false otherwise
bodyHasIndirectForceSensor()
bool mc_rbdyn::Robot::bodyHasIndirectForceSensor (const std::string & body) const
Check if the body has a force sensor attached to it (directly or indirectly)
Parameters
body Name of the body to which the sensor is (directly or indirectly) attached
Returns
True if the body has a force sensor attached to it, false otherwise
bodyIndexByName()
unsigned int mc_rbdyn::Robot::bodyIndexByName (const std::string & name) const
bodyPosW() [1/3]
const std::vector<sva::PTransformd>& mc_rbdyn::Robot::bodyPosW () const
Equivalent to robot.mbc().bodyPosW (const)
bodyPosW() [2/3]
std::vector<sva::PTransformd>& mc_rbdyn::Robot::bodyPosW ()
Equivalent to robot.mbc().bodyPosW.
bodyPosW() [3/3]
const sva::PTransformd& mc_rbdyn::Robot::bodyPosW (const std::string & name) const
Access the position of body name in world coordinates.
Exceptions
If the body does not exist within the robot
bodySensor() [1/4]
BodySensor& mc_rbdyn::Robot::bodySensor ()
Return the first BodySensor in the robot.
If the robot does not have body sensors, it returns a default (invalid) one
bodySensor() [2/4]
const BodySensor& mc_rbdyn::Robot::bodySensor () const
Return the first BodySensor in the robot (const)
bodySensor() [3/4]
BodySensor& mc_rbdyn::Robot::bodySensor (const std::string & name)
Return a specific BobySensor by name.
Parameters
name Name of the sensor
Exceptions
If the sensor does not exist
bodySensor() [4/4]
const BodySensor& mc_rbdyn::Robot::bodySensor (const std::string & name) const
Return a specific BodySensor by name (const)
bodySensors() [1/2]
BodySensorVector& mc_rbdyn::Robot::bodySensors ()
Return all body sensors.
bodySensors() [2/2]
const BodySensorVector& mc_rbdyn::Robot::bodySensors () const
Return all body sensors (const)
bodyTransform() [1/2]
const sva::PTransformd& mc_rbdyn::Robot::bodyTransform (const std::string & bName) const
Access transformation from body bName to original base.
This can be used to correct transformations that were stored with the original base. Usually the robot's base is the original base so these transforms are identity.
bodyTransform() [2/2]
const sva::PTransformd& mc_rbdyn::Robot::bodyTransform (int bodyIndex) const
Access body transform by index.
bodyTransforms()
const std::vector<sva::PTransformd>& mc_rbdyn::Robot::bodyTransforms () const
Access body transform vector.
bodyVelB() [1/3]
const std::vector<sva::MotionVecd>& mc_rbdyn::Robot::bodyVelB () const
Equivalent to robot.mbc().bodyVelB (const)
bodyVelB() [2/3]
std::vector<sva::MotionVecd>& mc_rbdyn::Robot::bodyVelB ()
Equivalent to robot.mbc().bodyVelB.
bodyVelB() [3/3]
const sva::MotionVecd& mc_rbdyn::Robot::bodyVelB (const std::string & name) const
Access the velocity of body name in body coordinates.
Exceptions
If the body doest not exist within the robot
bodyVelW() [1/3]
const std::vector<sva::MotionVecd>& mc_rbdyn::Robot::bodyVelW () const
Equivalent to robot.mbc().bodyVelW (const)
bodyVelW() [2/3]
std::vector<sva::MotionVecd>& mc_rbdyn::Robot::bodyVelW ()
Equivalent to robot.mbc().bodyVelW.
bodyVelW() [3/3]
const sva::MotionVecd& mc_rbdyn::Robot::bodyVelW (const std::string & name) const
Access the velocity of body name in world coordinates.
Exceptions
If the body doest not exist within the robot
bodyWrench()
sva::ForceVecd mc_rbdyn::Robot::bodyWrench (const std::string & bodyName) const
Compute the gravity-free wrench in body frame.
Note
If the body is indirectly attached to the sensor (i.e there are joints in-between), then the kinematic transformation will be taken into account but the effect of bodies in-between is not accounted for in the returned wrench.
Parameters
bodyName A body attached to a force sensor
Returns
Measured wrench in body frame
Exceptions
If no sensor is attached to this surface
collisionTransform()
const sva::PTransformd& mc_rbdyn::Robot::collisionTransform (const std::string & cName) const
Access transformation between the collision mesh and the body.
com()
Eigen::Vector3d mc_rbdyn::Robot::com () const
Compute and returns the current robot's CoM.
comAcceleration()
Eigen::Vector3d mc_rbdyn::Robot::comAcceleration () const
Compute and returns the current robot's CoM acceleration.
comVelocity()
Eigen::Vector3d mc_rbdyn::Robot::comVelocity () const
Compute and returns the current robot's CoM velocity.
convex() [1/2]
convex_pair_t& mc_rbdyn::Robot::convex (const std::string & cName)
Access a convex named cName.
Returns
a pair giving the convex's parent body and the sch::Object object
convex() [2/2]
const convex_pair_t& mc_rbdyn::Robot::convex (const std::string & cName) const
Access a convex named cName (const)
convexes()
const std::map<std::string, convex_pair_t>& mc_rbdyn::Robot::convexes () const
Access all convexes available in this robot.
Returns
a map where keys are the convex name and values are those returned by convex
cop()
Eigen::Vector2d mc_rbdyn::Robot::cop (const std::string & surfaceName, double min_pressure = 0.5) const
Compute the cop in surface frame computed from gravity-free force measurements.
Parameters
surfaceName A surface attached to a force sensor
min_pressure Minimum pressure in N (default 0.5N).
Returns
Measured cop in surface frame
CoP if pressure >= min_pressure
Zero otherwise
Exceptions
If no sensor is attached to this surface
copW()
Eigen::Vector3d mc_rbdyn::Robot::copW (const std::string & surfaceName, double min_pressure = 0.5) const
Compute the cop in inertial frame compute from gravity-free force measurements.
Parameters
surfaceName A surface attached to a force sensor
min_pressure Minimum pressure in N (default 0.5N).
Returns
Measured cop in inertial frame
CoP if pressure >= min_pressure
Zero otherwise
Exceptions
If no sensor is attached to this surface
copy() [1/2]
void mc_rbdyn::Robot::copy (Robots & robots, const std::string & copyName, unsigned int robots_idx, const Base & base) const protected
Copy existing Robot with a new base.
Exceptions
std::runtime_error if a robot named <copyName> already exists
copy() [2/2]
void mc_rbdyn::Robot::copy (Robots & robots, const std::string & copyName, unsigned int robots_idx) const protected
Copy existing Robot.
Exceptions
std::runtime_error if a robot named <copyName> already exists
copySurface()
mc_rbdyn::Surface& mc_rbdyn::Robot::copySurface (const std::string & sName, const std::string & name)
Copy an existing surface with a new name.
device() [1/2]
template<typename T > const T& mc_rbdyn::Robot::device (const std::string & name) const
Get a generic device of type T named name.
The reference returned by this function is remains valid
Parameters
name Name of the device
Template Parameters
T type of the device requested
Exceptions
If the device does not exist or does not have the right type
device() [2/2]
template<typename T > T& mc_rbdyn::Robot::device (const std::string & name) inline
Non-const variant.
encoderValues() [1/2]
const std::vector<double>& mc_rbdyn::Robot::encoderValues () const
Return the encoder values.
encoderValues() [2/2]
void mc_rbdyn::Robot::encoderValues (const std::vector< double > & encoderValues)
Set the encoder values.
encoderVelocities() [1/2]
const std::vector<double>& mc_rbdyn::Robot::encoderVelocities () const
Return the encoder velocities.
encoderVelocities() [2/2]
void mc_rbdyn::Robot::encoderVelocities (const std::vector< double > & encoderVelocities)
Set the encoder velocities.
eulerIntegration() [1/2]
void mc_rbdyn::Robot::eulerIntegration (double step)
Apply Euler integration to the robot using step timestep.
eulerIntegration() [2/2]
void mc_rbdyn::Robot::eulerIntegration (rbd::MultiBodyConfig & mbc, double step) const
Apply Euler integration to mbc using the robot's mb() and step timestep.
findIndirectForceSensorBodyName()
std::string mc_rbdyn::Robot::findIndirectForceSensorBodyName (const std::string & bodyName) const protected
Finds the name of the body to which a force sensor is attached, starting from the provided body and going up the kinematic tree.
Parameters
bodyName Name of the body to which the sensor is attached
Returns
Body name to which the sensor is attached when found. Empty string otherwise
fixCollisionTransforms()
void mc_rbdyn::Robot::fixCollisionTransforms () protected
Used to set the collision transforms correctly.
fixSurfaces()
void mc_rbdyn::Robot::fixSurfaces () protected
Used to set the surfaces' X_b_s correctly.
flexibility() [1/2]
const std::vector<Flexibility>& mc_rbdyn::Robot::flexibility () const
Return the flexibilities of the robot (const)
flexibility() [2/2]
std::vector<Flexibility>& mc_rbdyn::Robot::flexibility ()
Return the flexibilities of the robot.
flexibilityValues() [1/2]
const std::vector<double>& mc_rbdyn::Robot::flexibilityValues () const
Return the flexibilities values.
flexibilityValues() [2/2]
void mc_rbdyn::Robot::flexibilityValues (const std::vector< double > & flexibilityValues)
Set the flexibilities values.
forceSensor() [1/2]
ForceSensor& mc_rbdyn::Robot::forceSensor (const std::string & name)
Return a force sensor by name.
Parameters
name Name of the sensor
Returns
The sensor named name
Exceptions
If no sensor with this name exists
forceSensor() [2/2]
const ForceSensor& mc_rbdyn::Robot::forceSensor (const std::string & name) const
Const variant.
forceSensors() [1/2]
std::vector<ForceSensor>& mc_rbdyn::Robot::forceSensors ()
Returns all force sensors.
forceSensors() [2/2]
const std::vector<ForceSensor>& mc_rbdyn::Robot::forceSensors () const
Returns all force sensors (const)
forwardAcceleration() [1/2]
void mc_rbdyn::Robot::forwardAcceleration (const sva::MotionVecd & A_0 = sva::MotionVecd(Eigen::Vector6d::Zero()))
Apply forward acceleration to the robot.
forwardAcceleration() [2/2]
void mc_rbdyn::Robot::forwardAcceleration (rbd::MultiBodyConfig & mbc, const sva::MotionVecd & A_0 = sva::MotionVecd(Eigen::Vector6d::Zero())) const
Apply forward acceleration to mbc using the robot's mb()
forwardKinematics() [1/2]
void mc_rbdyn::Robot::forwardKinematics ()
Apply forward kinematics to the robot.
forwardKinematics() [2/2]
void mc_rbdyn::Robot::forwardKinematics (rbd::MultiBodyConfig & mbc) const
Apply forward kinematics to mbc using the robot's mb()
forwardVelocity() [1/2]
void mc_rbdyn::Robot::forwardVelocity ()
Apply forward velocity to the robot.
forwardVelocity() [2/2]
void mc_rbdyn::Robot::forwardVelocity (rbd::MultiBodyConfig & mbc) const
Apply forward velocity to mbc using the robot's mb()
gripper()
mc_control::Gripper& mc_rbdyn::Robot::gripper (const std::string & gripper)
Access a gripper by name.
Parameters
gripper Gripper name
Exceptions
If the gripper does not exist within this robot
grippers()
const std::vector<mc_control::GripperRef>& mc_rbdyn::Robot::grippers () const inline
Access all grippers.
References MC_RBDYN_DLLAPI, mc_rbdyn::robotFromConfig(), mc_rbdyn::robotIndexFromConfig(), and mc_rbdyn::robotNameFromConfig().
grippersByName()
const std::unordered_map<std::string, mc_control::GripperPtr>& mc_rbdyn::Robot::grippersByName () const inline
hasBody()
bool mc_rbdyn::Robot::hasBody (const std::string & name) const
Returns true if the robot has a body named name.
hasBodySensor()
bool mc_rbdyn::Robot::hasBodySensor (const std::string & name) const
Return true if the robot has a body sensor named name.
Parameters
name Name of the body sensor
hasConvex()
bool mc_rbdyn::Robot::hasConvex (const std::string & name) const
Check if a convex name exists.
Returns
True if the convex exists, false otherwise
hasDevice()
template<typename T > bool mc_rbdyn::Robot::hasDevice (const std::string & name) const
Returns true if a generic device of type T and named name exists in the robot.
Parameters
name Name of the device
Template Parameters
T Type of device requested
hasForceSensor()
bool mc_rbdyn::Robot::hasForceSensor (const std::string & name) const
Check if a force sensor exists.
Parameters
name Name of the sensor
Returns
True if the sensor exists, false otherwise
hasJoint()
bool mc_rbdyn::Robot::hasJoint (const std::string & name) const
Returns true if the robot has a joint named name.
Referenced by mc_tasks::MetaTask::ensureHasJoints().
hasSensor()
template<typename T > bool mc_rbdyn::Robot::hasSensor (const std::string & name) const inline
Alias for.
See also
hasDevice
hasSurface()
bool mc_rbdyn::Robot::hasSurface (const std::string & surface) const
Check if a surface surface exists.
Returns
True if the surface exists, false otherwise
indirectBodyForceSensor() [1/2]
ForceSensor& mc_rbdyn::Robot::indirectBodyForceSensor (const std::string & body)
Return a force sensor directly or indirectly attached to a body.
When the sensor is not directly attached to the body, look up the kinematic chain until the root until a sensor is found.
Returns
The sensor to which the body is indirectly attached
Exceptions
If no sensor is found between the body and the root
indirectBodyForceSensor() [2/2]
const ForceSensor& mc_rbdyn::Robot::indirectBodyForceSensor (const std::string & body) const
Const variant.
indirectSurfaceForceSensor() [1/2]
ForceSensor& mc_rbdyn::Robot::indirectSurfaceForceSensor (const std::string & surface)
Return a force sensor directly or indirectly attached to a surface.
When the sensor is not directly attached to the surface, look up the kinematic chain until the root until a sensor is found.
Parameters
surface Name of surface indirectly attached to the sensor
Returns
The sensor to which the surface is indirectly attached
Exceptions
If no sensor is found between the surface and the root
indirectSurfaceForceSensor() [2/2]
const ForceSensor& mc_rbdyn::Robot::indirectSurfaceForceSensor (const std::string & surface) const
Const variant.
jointIndexByName()
unsigned int mc_rbdyn::Robot::jointIndexByName (const std::string & name) const
jointIndexInMBC()
int mc_rbdyn::Robot::jointIndexInMBC (size_t jointIndex) const
Returns the joint index in the mbc of the joint with index jointIndex in refJointOrder.
Note
Joint indices can be -1 for joints present in refJointOrder but not in the robot's mbc (such as filtered joints in some robot modules)
Parameters
jointIndex Joint index in refJointOrder
Returns
joint index in the mbc
Exceptions
If jointIndex >= refJointOrder.size()
jointTorque() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::jointTorque () const
Equivalent to robot.mbc().jointTorque (const)
jointTorque() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::jointTorque ()
Equivalent to robot.mbc().jointTorque.
jointTorques() [1/2]
const std::vector<double>& mc_rbdyn::Robot::jointTorques () const
Return the joint torques from sensors.
jointTorques() [2/2]
void mc_rbdyn::Robot::jointTorques (const std::vector< double > & jointTorques)
Set joint torques from sensors.
loadRSDFFromDir()
void mc_rbdyn::Robot::loadRSDFFromDir (const std::string & surfaceDir)
Load surfaces from the directory surfaceDir.
mass()
double mc_rbdyn::Robot::mass () const
Compute and returns the mass of the robot.
mb() [1/2]
rbd::MultiBody& mc_rbdyn::Robot::mb ()
Access MultiBody representation of the robot.
mb() [2/2]
const rbd::MultiBody& mc_rbdyn::Robot::mb () const
Access MultiBody representation of the robot (const)
mbc() [1/2]
rbd::MultiBodyConfig& mc_rbdyn::Robot::mbc ()
Access MultiBodyConfig of the robot's mb()
mbc() [2/2]
const rbd::MultiBodyConfig& mc_rbdyn::Robot::mbc () const
Access MultiBodyConfig of the robot's mb() (const)
mbg() [1/2]
rbd::MultiBodyGraph& mc_rbdyn::Robot::mbg ()
Access MultiBodyGraph that generated the robot's mb()
mbg() [2/2]
const rbd::MultiBodyGraph& mc_rbdyn::Robot::mbg () const
Access MultiBodyGraph that generated the robot's mb() (const)
module()
const RobotModule& mc_rbdyn::Robot::module () const
Retrieve the associated RobotModule.
name()
const std::string& mc_rbdyn::Robot::name () const
Returns the name of the robot.
Note
To rename a robot, use Robots::rename(const std::string &, const std::string &)
Referenced by mc_tasks::MetaTask::ensureHasJoints().
netWrench()
sva::ForceVecd mc_rbdyn::Robot::netWrench (const std::vector< std::string > & sensorNames) const
Computes net total wrench from a list of sensors.
Parameters
sensorNames Names of all sensors used to compute the net wrench
Returns
Net total wrench (without gravity) in the inertial frame
operator=()
Robot& mc_rbdyn::Robot::operator= (Robot &&) default
posW() [1/2]
const sva::PTransformd& mc_rbdyn::Robot::posW () const
Return the robot's global pose.
posW() [2/2]
void mc_rbdyn::Robot::posW (const sva::PTransformd & pt)
Set the robot's global pose.
This is mostly meant for initialization purposes. In other scenarios there might be more things to do to properly move a robot (e.g. update contacts, set speed to zero).
Parameters
pt The new global pose
Exceptions
If joint(0) is neither free flyer nor fixed
Note
This function takes care of calling rbd::forwardKinematics
q() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::q () const
Equivalent to robot.mbc().q (const)
q() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::q ()
Equivalent to robot.mbc().q.
ql() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::ql () const
Access the robot's angular lower limits (const)
ql() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::ql ()
Access the robot's angular lower limits.
qu() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::qu () const
Access the robot's angular upper limits (const)
qu() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::qu ()
Access the robot's angular upper limits.
refJointOrder()
const std::vector<std::string>& mc_rbdyn::Robot::refJointOrder () const
Return the reference joint order for this robot.
removeConvex()
void mc_rbdyn::Robot::removeConvex (const std::string & name)
Remove a given convex.
Using this function while the given convex is involved in a collision is not safe and will very likely result in a crash.
This has no effect if name is not a convex of the robot.
Parameters
name Name of the convex
robotIndex()
unsigned int mc_rbdyn::Robot::robotIndex () const
Access the robot's index in robots()
sensor() [1/2]
template<typename T > const T& mc_rbdyn::Robot::sensor (const std::string & name) const inline
Alias for.
See also
device
sensor() [2/2]
template<typename T > T& mc_rbdyn::Robot::sensor (const std::string & name) inline
Alias for.
See also
device
stance()
std::map<std::string, std::vector<double> > mc_rbdyn::Robot::stance () const
Return the robot's default stance (e.g.
half-sitting for humanoid)
surface() [1/2]
mc_rbdyn::Surface& mc_rbdyn::Robot::surface (const std::string & sName)
Access a surface by its name sName.
surface() [2/2]
const mc_rbdyn::Surface& mc_rbdyn::Robot::surface (const std::string & sName) const
Access a surface by its name sName (const)
surfaceForceSensor() [1/2]
ForceSensor& mc_rbdyn::Robot::surfaceForceSensor (const std::string & surfaceName)
Return a force sensor attached to the provided surface.
Parameters
surface Name of the surface to which the sensor is attached
Returns
The attached sensor
Exceptions
If no sensor is directly attached to this surface
See also
ForceSensor & indirectBodyForceSensor(const std::string & surface); To get a sensor directly or indirectly attached to the surface.
surfaceForceSensor() [2/2]
const ForceSensor& mc_rbdyn::Robot::surfaceForceSensor (const std::string & surfaceName) const
Const variant.
surfaceHasForceSensor()
bool mc_rbdyn::Robot::surfaceHasForceSensor (const std::string & surface) const
Checks if the surface has a force sensor directly attached to it.
Parameters
surface Name of the surface to which the sensor is directly attached
See also
surfaceHasIndirectForceSensor(const std::string &) if you wish to check whether a sensor is indirectly attached to a body
Returns
True if the surface has a force sensor attached to it, false otherwise
surfaceHasIndirectForceSensor()
bool mc_rbdyn::Robot::surfaceHasIndirectForceSensor (const std::string & surface) const
Check if the surface has a force sensor attached to it (directly or indirectly)
Parameters
surface Name of the surface to which the sensor is directly attached
Returns
True if the surface has a force sensor attached to it, false otherwise
surfacePose()
sva::PTransformd mc_rbdyn::Robot::surfacePose (const std::string & sName) const
Get the pose of a surface frame with respect to the inertial frame.
Parameters
sName Name of surface frame.
surfaces()
const std::map<std::string, mc_rbdyn::SurfacePtr>& mc_rbdyn::Robot::surfaces () const
Returns all available surfaces.
surfaceWrench()
sva::ForceVecd mc_rbdyn::Robot::surfaceWrench (const std::string & surfaceName) const
Compute the gravity-free wrench in surface frame.
Note
If the surface is indirectly attached to the sensor (i.e there are joints in-between), then the kinematic transformation will be taken into account but the effect of bodies in-between is not accounted for in the returned wrench.
Parameters
surfaceName A surface attached to a force sensor
Returns
Measured wrench in surface frame
Exceptions
If no sensor is attached to this surface
tdl() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::tdl () const
Access the robot's angular lower torque-derivative limits (const)
tdl() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::tdl ()
Access the robot's angular lower torque-derivative limits.
tdu() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::tdu () const
Access the robot's angular upper torque-derivative limits (const)
tdu() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::tdu ()
Access the robot's angular upper torque-derivative limits.
tl() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::tl () const
Access the robot's angular lower torque limits (const)
tl() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::tl ()
Access the robot's angular lower torque limits.
tu() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::tu () const
Access the robot's angular upper torque limits (const)
tu() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::tu ()
Access the robot's angular upper torque limits.
velW() [1/2]
void mc_rbdyn::Robot::velW (const sva::MotionVecd & vel)
Update the robot's floating base velocity.
Parameters
vel New floating base velocity in the inertial frame.
Note
This function takes care of calling rbd::forwardVelocity
velW() [2/2]
const sva::MotionVecd& mc_rbdyn::Robot::velW () const
Return the robot's floating base velocity expressed in the inertial frame.
vl() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::vl () const
Access the robot's angular lower velocity limits (const)
vl() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::vl ()
Access the robot's angular lower velocity limits.
vu() [1/2]
const std::vector<std::vector<double> >& mc_rbdyn::Robot::vu () const
Access the robot's angular upper velocity limits (const)
vu() [2/2]
std::vector<std::vector<double> >& mc_rbdyn::Robot::vu ()
Access the robot's angular upper velocity limits.
X_b1_b2()
sva::PTransformd mc_rbdyn::Robot::X_b1_b2 (const std::string & b1, const std::string & b2) const
Relative transformation X_b1_b2 from body b1 to body b2.
Parameters
b1 name of first body
b2 name of second body
Exceptions
If b1 or b2 does not exist within the robot
zmp() [1/4]
Eigen::Vector3d mc_rbdyn::Robot::zmp (const sva::ForceVecd & netTotalWrench, const Eigen::Vector3d & plane_p, const Eigen::Vector3d & plane_n, double minimalNetNormalForce = 1.) const
Actual ZMP computation from net total wrench and the ZMP plane.
Parameters
netTotalWrench Total wrench for all links in contact
plane_p Arbitrary point on the ZMP plane
plane_n Normal to the ZMP plane (normalized)
minimalNetNormalForce[N] Mininal force above which the ZMP computation is considered valid. Must be >0 (prevents a divide by zero).
Returns
zmp expressed in the requested plane
Exceptions
To prevent dividing by zero, throws if the projected force is below minimalNetNormalForce newton. This is highly unlikely to happen and would likely indicate indicate that you are computing a ZMP from invalid forces (such as with the robot in the air).
See also
Eigen::Vector3d mc_rbdyn::zmp(const sva::ForceVecd & netTotalWrench, const Eigen::Vector3d & plane_p, const Eigen::Vector3d & plane_n, double minimalNetNormalForce)
zmp() [2/4]
Eigen::Vector3d mc_rbdyn::Robot::zmp (const sva::ForceVecd & netTotalWrench, const sva::PTransformd & zmpFrame, double minimalNetNormalForce = 1.) const
ZMP computation from net total wrench and a frame.
See zmpDoc
See also
Eigen::Vector3d mc_rbdyn::zmp(const sva::ForceVecd & netTotalWrench, const sva::PTransformd & zmpFrame, double minimalNetNormalForce) const;
Parameters
netTotalWrench
zmpFrame Frame used for ZMP computation. The convention here is that the contact frame should have its z-axis pointing in the normal direction of the contact towards the robot.
Returns
ZMP expressed in the plane defined by the zmpFrame frame.
zmp() [3/4]
Eigen::Vector3d mc_rbdyn::Robot::zmp (const std::vector< std::string > & sensorNames, const Eigen::Vector3d & plane_p, const Eigen::Vector3d & plane_n, double minimalNetNormalForce = 1.) const
Computes the ZMP from sensor names and a plane.
See zmpDoc
Parameters
sensorNames Names of all sensors attached to a link in contact with the environment
zmp() [4/4]
Eigen::Vector3d mc_rbdyn::Robot::zmp (const std::vector< std::string > & sensorNames, const sva::PTransformd & zmpFrame, double minimalNetNormalForce = 1.) const
Computes the ZMP from sensor names and a frame.
See zmpDoc
Parameters
sensorNames Names of all sensors attached to a link in contact with the environment
zmpTarget() [1/2]
void mc_rbdyn::Robot::zmpTarget (const Eigen::Vector3d & zmp)
Set the target zmp defined with respect to base-link.
This target is intended to be used by an external stabilizer such as Kawada's
Parameters
zmp Note that usually the ZMP is a 2-vector assuming a perfectly flat ground. The convention here is that the ground is at (tz=0). Therefore the target zmp should be defined as (ZMPx, ZMPy, -zbaselink)
zmpTarget() [2/2]
const Eigen::Vector3d& mc_rbdyn::Robot::zmpTarget () const
Returns the target zmp.
Returns
Target ZMP. See zmpTarget(Eigen::Vector3d) for details.
Friends And Related Function Documentation
Robots
friend struct Robots friend