mc_rbdyn::ForceSensor Struct Reference
mc_rbdyn::ForceSensor Struct Reference
This struct is intended to hold static information about a force sensor and the current reading of said sensor.
#include <mc_rbdyn/ForceSensor.h>
Public Member Functions
ForceSensor ()
Default constructor, this does not represent a valid force sensor.
ForceSensor (const std::string &name, const std::string &parentBodyName, const sva::PTransformd &X_p_f)
Construct a valid force sensor based on static information, this force sensor can then be used to provide sensing information to the robot.
ForceSensor (const ForceSensor &fs)
ForceSensor & operator= (const ForceSensor &fs)
ForceSensor (ForceSensor &&)=default
ForceSensor & operator= (ForceSensor &&)=default
~ForceSensor () noexcept override
Destructor.
const std::string & parentBody () const
Return the sensor's parent body.
const sva::PTransformd & X_p_f () const
Return the transformation from the parent body to the sensor (model)
sva::PTransformd X_0_f (const mc_rbdyn::Robot &robot) const
Return the sensor pose in the inertial frame (convenience function)
const sva::ForceVecd & wrench () const
Return the current wrench.
const Eigen::Vector3d & force () const
Return the force reading.
const Eigen::Vector3d & couple () const
Return the couple reading.
void wrench (const sva::ForceVecd &wrench)
Set the current wrench expressed in sensor frame.
sva::ForceVecd wrenchWithoutGravity (const mc_rbdyn::Robot &robot) const
Return a gravity-free wrench in sensor frame.
sva::ForceVecd worldWrench (const mc_rbdyn::Robot &robot) const
Return measured wrench in the inertial frame.
sva::ForceVecd worldWrenchWithoutGravity (const mc_rbdyn::Robot &robot) const
Return measured gravity-free wrench in the inertial frame.
DevicePtr clone () const override
Perform a device copy.
Calibration
These functions are related to the sensor's calibration
void loadCalibrator (const std::string &calib_file, const Eigen::Vector3d &gravity={0., 0., 9.81})
Load data from a file, using a gravity vector.
void resetCalibrator ()
Reset the force calibration to its default values such that the calibrator has no effect on the sensor wrench.
const sva::PTransformd & X_fsmodel_fsactual () const
Return the local rotation associated to the sensor, i.e.
const sva::PTransformd X_fsactual_parent () const
Return the transform from the parent body to the real force sensor.
double mass () const
Return the mass of the sensor.
const sva::ForceVecd & offset () const
Return the sensor offset.
Public Member Functions inherited from mc_rbdyn::Device
Device (const std::string &name)
Build a device not specifically attached to the robot.
Device (const std::string &name, const std::string &parent, const sva::PTransformd &X_p_s)
Build a device attached to a specific body of the robot.
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=default
Device & operator= (Device &&)=default
virtual ~Device () noexcept=default
const std::string & name () const
Returns the name of the sensor.
const std::string & type () const
Returns the type of the sensor.
const std::string & parent () const
Returns the parent body of the sensor.
void parent (const std::string &p)
Change the parent body of the sensor.
const sva::PTransformd & X_p_d () const
Returns the transformation from the parent body to the device.
const sva::PTransformd & X_p_s () const
Returns the transformation from the parent body to the sensor.
void X_p_d (const sva::PTransformd &pt)
Change the parent to device transformation.
void X_p_s (const sva::PTransformd &pt)
Change the parent to sensor transformation.
sva::PTransformd X_0_d (const mc_rbdyn::Robot &robot) const
Returns the deviec position in the inertial frame (convenience function)
sva::PTransformd X_0_s (const mc_rbdyn::Robot &robot) const
Returns the sensor position in the inertial frame (convenience function)
Additional Inherited Members
Protected Attributes inherited from mc_rbdyn::Device
std::string type_
Type of sensor as string.
std::string name_
Name of the sensor.
std::string parent_
Parent body of the sensor.
sva::PTransformd X_p_s_
Transformation from the parent body frame to the sensor frame.
Detailed Description
This struct is intended to hold static information about a force sensor and the current reading of said sensor.
If the appropriate data is provided, a gravity-free reading can be provided.
Constructor & Destructor Documentation
ForceSensor() [1/4]
mc_rbdyn::ForceSensor::ForceSensor ()
Default constructor, this does not represent a valid force sensor.
ForceSensor() [2/4]
mc_rbdyn::ForceSensor::ForceSensor (const std::string & name, const std::string & parentBodyName, const sva::PTransformd & X_p_f)
Construct a valid force sensor based on static information, this force sensor can then be used to provide sensing information to the robot.
However, filtering will have no effect
Parameters
name Name of the sensor
parentBodyName Name of the sensor's parent body
X_p_f Model transformation from the parent body to the model (not real) sensor frame
ForceSensor() [3/4]
mc_rbdyn::ForceSensor::ForceSensor (const ForceSensor & fs)
ForceSensor() [4/4]
mc_rbdyn::ForceSensor::ForceSensor (ForceSensor &&) default
~ForceSensor()
mc_rbdyn::ForceSensor::~ForceSensor () override noexcept
Destructor.
Member Function Documentation
clone()
DevicePtr mc_rbdyn::ForceSensor::clone () const override virtual
Perform a device copy.
Implements mc_rbdyn::Device.
couple()
const Eigen::Vector3d& mc_rbdyn::ForceSensor::couple () const inline
Return the couple reading.
Shortcut for wrench().couple()
force()
const Eigen::Vector3d& mc_rbdyn::ForceSensor::force () const inline
Return the force reading.
Shortcut for wrench().force()
loadCalibrator()
void mc_rbdyn::ForceSensor::loadCalibrator (const std::string & calib_file, const Eigen::Vector3d & gravity = {0., 0., 9.81})
Load data from a file, using a gravity vector.
The file should contain 13 parameters in that order: mass (1), rpy for X_f_ds (3), position for X_p_vb (3), wrench offset (6).
Parameters
calib_file Calibration file, the file should exist
gravity Gravity vector, defaults to Z
mass()
double mc_rbdyn::ForceSensor::mass () const
Return the mass of the sensor.
offset()
const sva::ForceVecd& mc_rbdyn::ForceSensor::offset () const
Return the sensor offset.
operator=() [1/2]
ForceSensor& mc_rbdyn::ForceSensor::operator= (const ForceSensor & fs)
operator=() [2/2]
ForceSensor& mc_rbdyn::ForceSensor::operator= (ForceSensor &&) default
parentBody()
const std::string& mc_rbdyn::ForceSensor::parentBody () const inline
Return the sensor's parent body.
References mc_rbdyn::Device::parent().
resetCalibrator()
void mc_rbdyn::ForceSensor::resetCalibrator ()
Reset the force calibration to its default values such that the calibrator has no effect on the sensor wrench.
worldWrench()
sva::ForceVecd mc_rbdyn::ForceSensor::worldWrench (const mc_rbdyn::Robot & robot) const
Return measured wrench in the inertial frame.
Parameters
robot Robot that the sensor belongs to
Returns
w_0 Spatial force vector of measured wrench
worldWrenchWithoutGravity()
sva::ForceVecd mc_rbdyn::ForceSensor::worldWrenchWithoutGravity (const mc_rbdyn::Robot & robot) const
Return measured gravity-free wrench in the inertial frame.
Parameters
robot Robot that the sensor belongs to
Returns
w_0 Spatial force vector of measured wrench
wrench() [1/2]
const sva::ForceVecd& mc_rbdyn::ForceSensor::wrench () const inline
Return the current wrench.
wrench() [2/2]
void mc_rbdyn::ForceSensor::wrench (const sva::ForceVecd & wrench) inline
Set the current wrench expressed in sensor frame.
Parameters
wrench New wrench reading
References mc_rtc::constants::gravity.
wrenchWithoutGravity()
sva::ForceVecd mc_rbdyn::ForceSensor::wrenchWithoutGravity (const mc_rbdyn::Robot & robot) const
Return a gravity-free wrench in sensor frame.
Parameters
robot Robot that the sensor belongs to
Returns
A gravity-free reading of the wrench
X_0_f()
sva::PTransformd mc_rbdyn::ForceSensor::X_0_f (const mc_rbdyn::Robot & robot) const inline
Return the sensor pose in the inertial frame (convenience function)
References mc_rbdyn::Device::X_0_s().
X_fsactual_parent()
const sva::PTransformd mc_rbdyn::ForceSensor::X_fsactual_parent () const
Return the transform from the parent body to the real force sensor.
X_fsmodel_fsactual()
const sva::PTransformd& mc_rbdyn::ForceSensor::X_fsmodel_fsactual () const
Return the local rotation associated to the sensor, i.e.
the error between the model forceSensor and real one
X_p_f()
const sva::PTransformd& mc_rbdyn::ForceSensor::X_p_f () const inline
Return the transformation from the parent body to the sensor (model)
References mc_rbdyn::Device::X_p_s().