mc_rbdyn::RobotLoader Class Reference
mc_rbdyn::RobotLoader Class Reference
Load RobotModule instances from shared libraries.
#include <mc_rbdyn/RobotLoader.h>
Static Public Member Functions
template<typename... Args>
static mc_rbdyn::RobotModulePtr get_robot_module (const std::string &name, const Args &... args)
Return a RobotModule constructed with the provided Args.
static void update_robot_module_path (const std::vector< std::string > &paths)
Add additional directories to the robot module path.
static void clear ()
Remove all loaded libraries.
static bool has_robot (const std::string &name)
Check if a robot is available.
static void enable_sandboxing (bool enable_sandbox)
Enable robot's creation sandboxing.
static void set_verbosity (bool verbose)
static std::vector< std::string > available_robots ()
Returns a list of available robots.
static void load_aliases (const std::string &fname)
Load aliases.
Detailed Description
Load RobotModule instances from shared libraries.
Member Function Documentation
available_robots()
static std::vector<std::string> mc_rbdyn::RobotLoader::available_robots () static
Returns a list of available robots.
clear()
static void mc_rbdyn::RobotLoader::clear () inline static
Remove all loaded libraries.
enable_sandboxing()
static void mc_rbdyn::RobotLoader::enable_sandboxing (bool enable_sandbox) inline static
Enable robot's creation sandboxing.
Parameters
enable_sandbox If true, robot's create call are sandboxed
get_robot_module()
template<typename... Args> static mc_rbdyn::RobotModulePtr mc_rbdyn::RobotLoader::get_robot_module (const std::string & name, const Args &... args) inline static
Return a RobotModule constructed with the provided Args.
Parameters
name The module name
args The arguments provided to the module creation function
Note
It is the responsability of the caller to make sure that the signature of the module creation fits that declared by the module
References mc_rtc::log::error(), mc_rtc::log::info(), and mc_rbdyn::details::to_string().
has_robot()
static bool mc_rbdyn::RobotLoader::has_robot (const std::string & name) inline static
Check if a robot is available.
Parameters
name Robot name
load_aliases()
static void mc_rbdyn::RobotLoader::load_aliases (const std::string & fname) static
Load aliases.
An aliases file should be a map of alias to param vector
Parameters
fname A JSON or YAML containing aliases
set_verbosity()
static void mc_rbdyn::RobotLoader::set_verbosity (bool verbose) inline static
update_robot_module_path()
static void mc_rbdyn::RobotLoader::update_robot_module_path (const std::vector< std::string > & paths) static
Add additional directories to the robot module path.
Parameters
paths Directories to be added to the module path