mc_rtc::Configuration Struct Reference
mc_rtc::Configuration Struct Reference
Simplify access to values hold within a JSON file.
#include <mc_rtc/Configuration.h>
Classes
struct Exception
Exception thrown by this class when something bad occurs.
Public Member Functions
MC_RTC_DEPRECATED bool isMember (const std::string &key) const
Deprecated, see has.
bool has (const std::string &key) const
Check if the key is part of the conf.
operator bool () const
Cast to bool.
operator int () const
Cast to int.
operator unsigned int () const
Cast to unsigned int.
operator int64_t () const
Cast to int64_t.
operator uint64_t () const
Cast to uint64_t.
operator double () const
Cast to double.
operator std::string () const
Cast to a string.
operator Eigen::Vector2d () const
Retrieve as a Eigen::Vector2d instance.
operator Eigen::Vector3d () const
Retrieve as a Eigen::Vector3d instance.
operator Eigen::Vector6d () const
Retrieve as a Eigen::Vector6d instance.
operator Eigen::VectorXd () const
Retrieve as a Eigen::VectorXd instance.
operator Eigen::Quaterniond () const
Retrieve as a Eigen::Quaterniond instance.
operator Eigen::Matrix3d () const
Retrieve as a Eigen::Matrix3d instance.
operator Eigen::Matrix6d () const
Retrieve as a Eigen::Matrix6d instance.
operator Eigen::MatrixXd () const
Retrieve as a Eigen::MatrixXd instance.
operator sva::PTransformd () const
Retrieve as an sva::PTransformd.
operator sva::ForceVecd () const
Retrieve as an sva::ForceVecd.
operator sva::MotionVecd () const
Retrieve as an sva::MotionVecd.
template<class T , class A >
operator std::vector< T, A > () const
Retrieve a vector instance.
template<class T , std::size_t N>
operator std::array< T, N > () const
Retrieve an array instance.
template<class T1 , class T2 >
operator std::pair< T1, T2 > () const
Retrieve a pair instance.
template<typename T , class C , class A >
operator std::map< std::string, T, C, A > () const
Retrieve a string-indexed map instance.
template<typename T , typename C = std::less<T>, typename A = std::allocator<T>>
operator std::set< T, C, A > () const
Retrieve a set of objects.
template<typename T , typename H = std::hash<T>, typename E = std::equal_to<T>, typename A = std::allocator<T>>
operator std::unordered_set< T, H, E, A > () const
Retrieve an unordered set of objects.
template<typename T , typename std::enable_if< internal::has_configuration_load_object< T >::value, int >::type = 0>
operator T () const
User-defined conversions.
Configuration ()
Creates an empty configuration.
Configuration (const std::string &path)
Constructor using a file path.
Configuration (const char *path)
Constructor using a file path (C-style string)
void load (const std::string &path)
Load more data into the configuration.
void load (const mc_rtc::Configuration &config)
Load data from another Configuration object.
void loadData (const std::string &data)
Load data from a JSON string.
void loadYAMLData (const std::string &data)
Load data from a YAML string.
void save (const std::string &path, bool pretty=true) const
Save the configuration to a file.
std::string dump (bool pretty=false, bool yaml=false) const
Dump the configuration into a string.
size_t toMessagePack (std::vector< char > &data) const
Convert to MessagePack.
void toMessagePack (MessagePackBuilder &builder) const
Append to an existing MessagePackBuilder.
Configuration operator() (const std::string &key) const
Returns a Entry value stored within the configuration.
bool empty () const
Returns true if the underlying array or underlying object is empty.
size_t size () const
If the stored value is an array, returns its size, otherwise returns 0.
Configuration operator[] (size_t i) const
If the stored value is an array, return a Configuration element for the i-th element.
template<typename T >
T at (size_t i, const T &v) const
Retrieve a given value from a JSON array.
template<typename T >
void operator() (const std::string &key, T &v) const
Retrieve and store a given value stored within the configuration.
template<typename T >
T operator() (const std::string &key, const T &v) const
Retrieve a given value stored within the configuration with a default value.
bool operator== (const char *rhs) const
Non-template version for C-style strings comparison.
template<typename T >
bool operator== (const T &rhs) const
Compare stored values with given value.
void add_null (const std::string &key)
Add a null element to the configuration.
void add (const std::string &key, bool value)
Add a bool element to the Configuration.
void add (const std::string &key, int value)
Add a int element to the Configuration.
void add (const std::string &key, unsigned int value)
Add a unsigned int element to the Configuration.
void add (const std::string &key, int64_t value)
Add a int64_t element to the Configuration.
void add (const std::string &key, uint64_t value)
Add a uint64_t element to the Configuration.
void add (const std::string &key, double value)
Add a double element to the Configuration.
void add (const std::string &key, const std::string &value)
Add a std::string element to the Configuration.
void add (const std::string &key, const char *value)
Add a const char* element to the Configuration, Behaves like std::string.
void add (const std::string &key, const Eigen::Vector2d &value)
Add a Eigen::Vector2d element to the Configuration.
void add (const std::string &key, const Eigen::Vector3d &value)
Add a Eigen::Vector3d element to the Configuration.
void add (const std::string &key, const Eigen::Vector6d &value)
Add a Eigen::Vector6d element to the Configuration.
void add (const std::string &key, const Eigen::VectorXd &value)
Add a Eigen::VectorXd element to the Configuration.
void add (const std::string &key, const Eigen::Quaterniond &value)
Add a Eigen::Quaterniond element to the Configuration.
void add (const std::string &key, const Eigen::Matrix3d &value)
Add a Eigen::Matrix3d element to the Configuration.
void add (const std::string &key, const Eigen::Matrix6d &value)
Add a Eigen::Matrix6d element to the Configuration.
void add (const std::string &key, const Eigen::MatrixXd &value)
Add an Eigen::MatrixXd element to the Configuration.
void add (const std::string &key, const sva::PTransformd &value)
Add an sva::PTransformd element to the Configuration.
void add (const std::string &key, const sva::ForceVecd &value)
Add an sva::ForceVecd element to the Configuration.
void add (const std::string &key, const sva::MotionVecd &value)
Add an sva::MotionVecd element to the Configuration.
void add (const std::string &key, const Configuration &value)
Add another Configuration to the Configuration.
Configuration add (const std::string &key)
Create an empty object in the Configuration.
Configuration array (const std::string &key, size_t size=0)
Create an empty array in the Configuration.
void push_null ()
Insert a null value into an array.
void push (bool value)
Insert a bool element into an array.
void push (int value)
Insert a int element into an array.
void push (unsigned int value)
Insert a unsigned int element into an array.
void push (int64_t value)
Insert a int64_t element int64_to an array.
void push (uint64_t value)
Insert a uint64_t element into an array.
void push (double value)
Insert a double element into an array.
void push (const std::string &value)
Insert a std::string element into an array.
void push (const char *value)
Insert a const char * element into an array Behaves like push(std::string)
void push (const Eigen::Vector2d &value)
Insert a Eigen::Vector2d element into an array.
void push (const Eigen::Vector3d &value)
Insert a Eigen::Vector3d element into an array.
void push (const Eigen::Vector6d &value)
Insert a Eigen::Vector6d element into an array.
void push (const Eigen::VectorXd &value)
Insert a Eigen::VectorXd element into an array.
void push (const Eigen::Quaterniond &value)
Insert a Eigen::Quaterniond element into an array.
void push (const Eigen::Matrix3d &value)
Insert a Eigen::Matrix3d element into an array.
void push (const Eigen::Matrix6d &value)
Insert a Eigen::Matrix6d element into an array.
void push (const Eigen::MatrixXd &value)
Insert a Eigen::MatrixXd element into an array.
void push (const sva::PTransformd &value)
Insert an sva::PTransformd element into an array.
void push (const sva::ForceVecd &value)
Insert an sva::ForceVecd element into an array.
void push (const sva::MotionVecd &value)
Insert an sva::MotionVecd element into an array.
void push (const Configuration &value)
Push a Configuration element into an array.
Configuration array (size_t reserve=0)
Push an empty array.
Configuration object ()
Push an empty object.
template<typename T , typename... Args, typename std::enable_if< internal::has_configuration_save_object< T, Args... >::value, int >::type = 0>
void push (const T &value, Args &&... args)
User-defined conversion.
template<typename T , typename A = std::allocator<T>, typename... Args>
void add (const std::string &key, const std::vector< T, A > &value, Args &&... args)
Add a vector into the JSON document.
template<typename T , std::size_t N, typename... Args>
void add (const std::string &key, const std::array< T, N > &value, Args &&... args)
Add an array into the JSON document.
template<typename T1 , typename T2 , typename... Args>
void add (const std::string &key, const std::pair< T1, T2 > &value, Args &&... args)
Add a pair into the JSON document.
template<typename T , class C = std::less<std::string>, class A = std::allocator<std::pair<const std::string, T>>, typename... Args>
void add (const std::string &key, const std::map< std::string, T, C, A > &value, Args &&... args)
Add string-indexed map into the JSON document.
template<typename T , typename C = std::less<T>, typename A = std::allocator<T>, typename... Args>
void add (const std::string &key, const std::set< T, C, A > &value, Args &&... args)
Add a set into the JSON document.
template<typename T , typename H = std::hash<T>, typename E = std::equal_to<T>, typename A = std::allocator<T>, typename... Args>
void add (const std::string &key, const std::unordered_set< T, H, E, A > &value, Args &&... args)
Add an unordered set into the JSON document.
template<typename T , typename... Args, typename std::enable_if< internal::has_configuration_save_object< T, Args... >::value, int >::type = 0>
void add (const std::string &key, const T &value, Args &&... args)
User-defined conversion.
template<typename T , typename A = std::allocator<T>, typename... Args>
void push (const std::vector< T, A > &value, Args &&... args)
Push a vector into the JSON document.
template<typename T , std::size_t N, typename... Args>
void push (const std::array< T, N > &value, Args &&... args)
Push an array into the JSON document.
template<typename T1 , typename T2 , typename... Args>
void push (const std::pair< T1, T2 > &value, Args &&... args)
Push a pair into the JSON document.
template<typename T , class C = std::less<std::string>, class A = std::allocator<std::pair<const std::string, T>>, typename... Args>
void push (const std::map< std::string, T, C, A > &value, Args &&... args)
Push a string-indexed map into the JSON document.
template<typename T , typename C = std::less<T>, typename A = std::allocator<T>, typename... Args>
void push (const std::set< T, C, A > &value, Args &&... args)
Push a set into the JSON document.
template<typename T , typename H = std::hash<T>, typename E = std::equal_to<T>, typename A = std::allocator<T>, typename... Args>
void push (const std::unordered_set< T, H, E, A > &value, Args &&... args)
Push an unordered set into the JSON document.
bool remove (const std::string &key)
Remove a given element.
std::vector< std::string > keys () const
Returns the keys of the JSON objects.
ConfigurationArrayIterator begin () const
ConfigurationArrayIterator end () const
template<>
void MC_RTC_UTILS_DLLAPI operator() (const std::string &key, std::string &v) const
Specialized version to lift ambiguity.
Static Public Member Functions
static Configuration rootArray ()
Returns a Configuration with an array as root entry.
static Configuration fromData (const std::string &data)
Static constructor to load from JSON data.
static Configuration fromData (const char *data)
Static constructor to load from JSON data (C overload)
static Configuration fromYAMLData (const std::string &data)
Static constructor to load from YAML data.
static Configuration fromYAMLData (const char *data)
Static constructor to load from YAML data (C overload)
static Configuration fromMessagePack (const char *data, size_t size)
Static constructor to load from MessagePack data.
Detailed Description
Simplify access to values hold within a JSON file.
Configuration values can be accessed using a key system, type conversion are ensured by the class.
Constructor & Destructor Documentation
Configuration() [1/3]
mc_rtc::Configuration::Configuration ()
Creates an empty configuration.
Configuration() [2/3]
mc_rtc::Configuration::Configuration (const std::string & path)
Constructor using a file path.
Parameters
path Path to the configuration file
Configuration() [3/3]
mc_rtc::Configuration::Configuration (const char * path)
Constructor using a file path (C-style string)
Parameters
path Path to the configuration file
Member Function Documentation
add() [1/28]
void mc_rtc::Configuration::add (const std::string & key, bool value)
Add a bool element to the Configuration.
Overrides the existing value if it holds one for the given key.
Parameters
key Key of the element
value Value of the element
Referenced by add(), push(), mc_rtc::ConfigurationLoader< mc_rbdyn::lipm_stabilizer::ZMPCCConfiguration >::save(), mc_rtc::ConfigurationLoader< mc_rbdyn::CompoundJointConstraintDescription >::save(), mc_rtc::ConfigurationLoader< mc_rbdyn::lipm_stabilizer::FDQPWeights >::save(), mc_rtc::ConfigurationLoader< mc_rbdyn::lipm_stabilizer::SafetyThresholds >::save(), mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::save(), mc_rtc::gui::LineConfig::saveConfig(), mc_rtc::gui::ArrowConfig::saveConfig(), mc_rtc::gui::ForceConfig::saveConfig(), mc_rtc::gui::PointConfig::saveConfig(), and mc_control::ControllerClient::send_request().
add() [2/28]
void mc_rtc::Configuration::add (const std::string & key, int value)
Add a int element to the Configuration.
See also
add(const std::string&, bool)
add() [3/28]
void mc_rtc::Configuration::add (const std::string & key, unsigned int value)
Add a unsigned int element to the Configuration.
See also
add(const std::string&, bool)
add() [4/28]
void mc_rtc::Configuration::add (const std::string & key, int64_t value)
Add a int64_t element to the Configuration.
See also
add(const std::string&, bool)
add() [5/28]
void mc_rtc::Configuration::add (const std::string & key, uint64_t value)
Add a uint64_t element to the Configuration.
See also
add(const std::string&, bool)
add() [6/28]
void mc_rtc::Configuration::add (const std::string & key, double value)
Add a double element to the Configuration.
See also
add(const std::string&, bool)
add() [7/28]
void mc_rtc::Configuration::add (const std::string & key, const std::string & value)
Add a std::string element to the Configuration.
See also
add(const std::string&, bool)
add() [8/28]
void mc_rtc::Configuration::add (const std::string & key, const char * value)
Add a const char* element to the Configuration, Behaves like std::string.
See also
add(const std::string&, bool)
add() [9/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::Vector2d & value)
Add a Eigen::Vector2d element to the Configuration.
See also
add(const std::string&, bool)
add() [10/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::Vector3d & value)
Add a Eigen::Vector3d element to the Configuration.
See also
add(const std::string&, bool)
add() [11/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::Vector6d & value)
Add a Eigen::Vector6d element to the Configuration.
See also
add(const std::string&, bool)
add() [12/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::VectorXd & value)
Add a Eigen::VectorXd element to the Configuration.
See also
add(const std::string&, bool)
add() [13/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::Quaterniond & value)
Add a Eigen::Quaterniond element to the Configuration.
See also
add(const std::string&, bool)
add() [14/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::Matrix3d & value)
Add a Eigen::Matrix3d element to the Configuration.
See also
add(const std::string&, bool)
add() [15/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::Matrix6d & value)
Add a Eigen::Matrix6d element to the Configuration.
See also
add(const std::string&, bool)
add() [16/28]
void mc_rtc::Configuration::add (const std::string & key, const Eigen::MatrixXd & value)
Add an Eigen::MatrixXd element to the Configuration.
See also
add(const std::string&, bool)
add() [17/28]
void mc_rtc::Configuration::add (const std::string & key, const sva::PTransformd & value)
Add an sva::PTransformd element to the Configuration.
See also
add(const std::string&, bool)
add() [18/28]
void mc_rtc::Configuration::add (const std::string & key, const sva::ForceVecd & value)
Add an sva::ForceVecd element to the Configuration.
See also
add(const std::string&, bool)
add() [19/28]
void mc_rtc::Configuration::add (const std::string & key, const sva::MotionVecd & value)
Add an sva::MotionVecd element to the Configuration.
See also
add(const std::string&, bool)
add() [20/28]
void mc_rtc::Configuration::add (const std::string & key, const Configuration & value)
Add another Configuration to the Configuration.
See also
add(const std::string&, bool)
add() [21/28]
Configuration mc_rtc::Configuration::add (const std::string & key)
Create an empty object in the Configuration.
Overwrite existing content if any.
Parameters
key Key to add
add() [22/28]
template<typename T , typename A = std::allocator<T>, typename... Args> void mc_rtc::Configuration::add (const std::string & key, const std::vector< T, A > & value, Args &&... args) inline
Add a vector into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Vector of elements to add
References push().
add() [23/28]
template<typename T , std::size_t N, typename... Args> void mc_rtc::Configuration::add (const std::string & key, const std::array< T, N > & value, Args &&... args) inline
Add an array into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Array of elements to add
References push().
add() [24/28]
template<typename T1 , typename T2 , typename... Args> void mc_rtc::Configuration::add (const std::string & key, const std::pair< T1, T2 > & value, Args &&... args) inline
Add a pair into the JSON document.
Overwrite existing content if any.
Parameters
key Key of the element
value Pair to add
References push().
add() [25/28]
template<typename T , class C = std::less<std::string>, class A = std::allocator<std::pair<const std::string, T>>, typename... Args> void mc_rtc::Configuration::add (const std::string & key, const std::map< std::string, T, C, A > & value, Args &&... args) inline
Add string-indexed map into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Map of elements to add
References add().
add() [26/28]
template<typename T , typename C = std::less<T>, typename A = std::allocator<T>, typename... Args> void mc_rtc::Configuration::add (const std::string & key, const std::set< T, C, A > & value, Args &&... args) inline
Add a set into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Set of elements to add
References push().
add() [27/28]
template<typename T , typename H = std::hash<T>, typename E = std::equal_to<T>, typename A = std::allocator<T>, typename... Args> void mc_rtc::Configuration::add (const std::string & key, const std::unordered_set< T, H, E, A > & value, Args &&... args) inline
Add an unordered set into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Set of elements to add
References push().
add() [28/28]
template<typename T , typename... Args, typename std::enable_if< internal::has_configuration_save_object< T, Args... >::value, int >::type = 0> void mc_rtc::Configuration::add (const std::string & key, const T & value, Args &&... args) inline
User-defined conversion.
Requires the existence of: mc_rtc::Configuration mc_rtc::ConfigurationLoader<T>::save(const T&, Args ... args);
Parameters
key Key of the element
value Value to add
add_null()
void mc_rtc::Configuration::add_null (const std::string & key)
Add a null element to the configuration.
Overrides the existing value if it holds one for the given key
Parameters
key Key of the element
array() [1/2]
Configuration mc_rtc::Configuration::array (const std::string & key, size_t size = 0)
Create an empty array in the Configuration.
Overwrite existing content if any.
Parameters
key Key to add
size Size that is reserved for the array
array() [2/2]
Configuration mc_rtc::Configuration::array (size_t reserve = 0)
Push an empty array.
See also
push(bool);
at()
template<typename T > T mc_rtc::Configuration::at (size_t i, const T & v) const inline
Retrieve a given value from a JSON array.
Returns the default value if the index is too high or if the underlying value does not match the requested type.
Parameters
i Index to retrieve
v The default value
References mc_rtc::Configuration::Exception::silence().
Referenced by mc_rtc::gui::Color::fromConfig().
begin()
ConfigurationArrayIterator mc_rtc::Configuration::begin () const
dump()
std::string mc_rtc::Configuration::dump (bool pretty = false, bool yaml = false) const
Dump the configuration into a string.
Parameters
pretty Writes a human-readable string, defaults to false
yaml Writes YAML instead of JSON, defaults to false
empty()
bool mc_rtc::Configuration::empty () const
Returns true if the underlying array or underlying object is empty.
end()
ConfigurationArrayIterator mc_rtc::Configuration::end () const
fromData() [1/2]
static Configuration mc_rtc::Configuration::fromData (const std::string & data) static
Static constructor to load from JSON data.
Parameters
data JSON data to load
fromData() [2/2]
static Configuration mc_rtc::Configuration::fromData (const char * data) static
Static constructor to load from JSON data (C overload)
Parameters
data JSON data to load
fromMessagePack()
static Configuration mc_rtc::Configuration::fromMessagePack (const char * data, size_t size) static
Static constructor to load from MessagePack data.
Parameters
data MessagePack data to load
size Size of data
Referenced by mc_rtc::gui::plot::PolygonDescription::fromMessagePack(), and mc_rtc::gui::ArrowConfig::fromMessagePack().
fromYAMLData() [1/2]
static Configuration mc_rtc::Configuration::fromYAMLData (const std::string & data) static
Static constructor to load from YAML data.
Parameters
data YAML data to load
fromYAMLData() [2/2]
static Configuration mc_rtc::Configuration::fromYAMLData (const char * data) static
Static constructor to load from YAML data (C overload)
Parameters
data YAML data to load
has()
bool mc_rtc::Configuration::has (const std::string & key) const
Check if the key is part of the conf.
Parameters
key The key to test
Returns
True if key is part of the configuration
Referenced by mc_rtc::gui::LineConfig::fromConfig(), mc_rtc::fromVectorOrElement(), mc_rtc::ConfigurationLoader< mc_rbdyn::lipm_stabilizer::ZMPCCConfiguration >::load(), and mc_rbdyn::lipm_stabilizer::StabilizerConfiguration::load().
isMember()
MC_RTC_DEPRECATED bool mc_rtc::Configuration::isMember (const std::string & key) const
Deprecated, see has.
Parameters
key The key to test
Returns
True if key is part of the configuration
keys()
std::vector<std::string> mc_rtc::Configuration::keys () const
Returns the keys of the JSON objects.
Returns an empty vector if the underlying JSON object is not an object
load() [1/2]
void mc_rtc::Configuration::load (const std::string & path)
Load more data into the configuration.
For any key existing in both objects:
(*this)(key) is overwritten for values and arrays
config(key) is loaded into (*this)(key) for objects
Parameters
path Path to the configuration file
load() [2/2]
void mc_rtc::Configuration::load (const mc_rtc::Configuration & config)
Load data from another Configuration object.
For any key existing in both objects:
(*this)(key) is overwritten for values and arrays
if config(key) and (*this)(key) are objects, config(key) is loaded into (*this)(key)
otherwise, config(key) overwrites (*this)(key)
Parameters
config The configuration object
loadData()
void mc_rtc::Configuration::loadData (const std::string & data)
Load data from a JSON string.
Same rules apply as ::load methods
Parameters
data JSON data to load
loadYAMLData()
void mc_rtc::Configuration::loadYAMLData (const std::string & data)
Load data from a YAML string.
Same rules apply as ::load methods
Parameters
data YAML data to load
object()
Configuration mc_rtc::Configuration::object ()
Push an empty object.
See also
push(bool);
operator bool()
mc_rtc::Configuration::operator bool () const
Cast to bool.
Exceptions
If the underlying value does not hold a boolean
operator double()
mc_rtc::Configuration::operator double () const
Cast to double.
Will actually convert any numeric entry into a double
Exceptions
If the underlying value does not hold a numeric value
operator Eigen::Matrix3d()
mc_rtc::Configuration::operator Eigen::Matrix3d () const
Retrieve as a Eigen::Matrix3d instance.
Exceptions
If the underlying value does not hold a numeric sequence of size 9
operator Eigen::Matrix6d()
mc_rtc::Configuration::operator Eigen::Matrix6d () const
Retrieve as a Eigen::Matrix6d instance.
Exceptions
If the underlying value does not hold a numeric sequence of size 36
operator Eigen::MatrixXd()
mc_rtc::Configuration::operator Eigen::MatrixXd () const
Retrieve as a Eigen::MatrixXd instance.
Exceptions
If the underlying value does not hold an array of array of numeric values
operator Eigen::Quaterniond()
mc_rtc::Configuration::operator Eigen::Quaterniond () const
Retrieve as a Eigen::Quaterniond instance.
Note
The sequence is normalized
Exceptions
If the underlying value does not hold a numeric sequence of size 4
operator Eigen::Vector2d()
mc_rtc::Configuration::operator Eigen::Vector2d () const
Retrieve as a Eigen::Vector2d instance.
Exceptions
If the underlying value does not hold a numeric sequence of size 2
operator Eigen::Vector3d()
mc_rtc::Configuration::operator Eigen::Vector3d () const
Retrieve as a Eigen::Vector3d instance.
Exceptions
If the underlying value does not hold a numeric sequence of size 3
operator Eigen::Vector6d()
mc_rtc::Configuration::operator Eigen::Vector6d () const
Retrieve as a Eigen::Vector6d instance.
Exceptions
If the underlying value does not hold a numeric sequence of size 6
operator Eigen::VectorXd()
mc_rtc::Configuration::operator Eigen::VectorXd () const
Retrieve as a Eigen::VectorXd instance.
If the underlying value holds an empty sequence, this functions returns an empty (size 0) vector
Exceptions
If the underlying value does not hold a numeric sequence
operator int()
mc_rtc::Configuration::operator int () const
Cast to int.
Strictly for int-typed entries
Exceptions
If the underlying value does not hold an int
operator int64_t()
mc_rtc::Configuration::operator int64_t () const
Cast to int64_t.
Strictly for int64_t-typed entries
Exceptions
If the underlying value does not hold an int64_t
operator std::array< T, N >()
template<class T , std::size_t N> mc_rtc::Configuration::operator std::array< T, N > () const inline
Retrieve an array instance.
Exceptions
If the underlying value does not hold an array of the correct size or if any member of the array does not meet the requirements of the array elements' type.
References mc_rtc::Configuration.
operator std::map< std::string, T, C, A >()
template<typename T , class C , class A > mc_rtc::Configuration::operator std::map< std::string, T, C, A > () const inline
Retrieve a string-indexed map instance.
Exceptions
If the underlying value is not an object or if the member of the object do not meet the requiremenent of the value type.
References mc_rtc::Configuration.
operator std::pair< T1, T2 >()
template<class T1 , class T2 > mc_rtc::Configuration::operator std::pair< T1, T2 > () const inline
Retrieve a pair instance.
Exceptions
If the underlying value does not hold an array of size 2 or if the member of the array do not meet the requirement of the pair type
References mc_rtc::Configuration.
operator std::set< T, C, A >()
template<typename T , typename C = std::less<T>, typename A = std::allocator<T>> mc_rtc::Configuration::operator std::set< T, C, A > () const inline
Retrieve a set of objects.
Exceptions
If the underlying value is not an array, if the member of the array do not meet the requirement of the set key type or if the elements in the array are not unique
References mc_rtc::Configuration.
operator std::string()
mc_rtc::Configuration::operator std::string () const
Cast to a string.
Note
You may need explicit casting in some cases, e.g. writing a = config("entry") where a is a std::string instance requires explicit casting to compile. Alternatively, in this scenario, one can use config("entry", a) without explicit casting.
Exceptions
If the underlying value does not hold a string
operator std::unordered_set< T, H, E, A >()
template<typename T , typename H = std::hash<T>, typename E = std::equal_to<T>, typename A = std::allocator<T>> mc_rtc::Configuration::operator std::unordered_set< T, H, E, A > () const inline
Retrieve an unordered set of objects.
Exceptions
If the underlying value is not an array, if the member of the array do not meet the requirement of the set key type or if the elements in the array are not unique
References mc_rtc::Configuration.
operator std::vector< T, A >()
template<class T , class A > mc_rtc::Configuration::operator std::vector< T, A > () const inline
Retrieve a vector instance.
Exceptions
If the underlying value does not hold an array or if any member of the array does not meeting the requirement of the vector elements' type
References mc_rtc::Configuration.
operator sva::ForceVecd()
mc_rtc::Configuration::operator sva::ForceVecd () const
Retrieve as an sva::ForceVecd.
Exceptions
If the underlying value is not an object with couple and force members
operator sva::MotionVecd()
mc_rtc::Configuration::operator sva::MotionVecd () const
Retrieve as an sva::MotionVecd.
Exceptions
If the underlying value is not an object with angular and linear members
operator sva::PTransformd()
mc_rtc::Configuration::operator sva::PTransformd () const
Retrieve as an sva::PTransformd.
Exceptions
If the underlying value is not an object with rotation and/or translation members
operator T()
template<typename T , typename std::enable_if< internal::has_configuration_load_object< T >::value, int >::type = 0> mc_rtc::Configuration::operator T () const inline
User-defined conversions.
Requires:
T mc_rtc::ConfigurationLoader<T>::load(const mc_rtc::Configuration &) should exist
References mc_rtc::Configuration, mc_rtc::ConfigurationLoader< T >::load(), and mc_rtc::ConfigurationLoader< T >::save().
operator uint64_t()
mc_rtc::Configuration::operator uint64_t () const
Cast to uint64_t.
Int entries that are strictly positive will be treated as uint64_t entries
Exceptions
If the underlying value does not hold an uint64_t
operator unsigned int()
mc_rtc::Configuration::operator unsigned int () const
Cast to unsigned int.
Int entries that are strictly positive will be treated as unsigned int entries
Exceptions
If the underlying value does not hold an unsigned int
operator()() [1/4]
Configuration mc_rtc::Configuration::operator() (const std::string & key) const
Returns a Entry value stored within the configuration.
Parameters
key The key used to store the value
Returns
The Entry value stored in the configuration in the key entry
Exceptions
If key is not stored in the Configuration
operator()() [2/4]
template<typename T > void mc_rtc::Configuration::operator() (const std::string & key, T & v) const inline
Retrieve and store a given value stored within the configuration.
If they key is not stored in the Configuration, the value is unchanged.
Parameters
key The key used to store the value
v The value to retrieve
References mc_rtc::Configuration::Exception::silence().
operator()() [3/4]
template<typename T > T mc_rtc::Configuration::operator() (const std::string & key, const T & v) const inline
Retrieve a given value stored within the configuration with a default value.
If the key is not stored in the Configuration or if the underyling value does not match the requested type, the default value is returned.
Parameters
key The key used to store the value
v The default value
References mc_rtc::Configuration::Exception::silence().
operator()() [4/4]
template<> void MC_RTC_UTILS_DLLAPI mc_rtc::Configuration::operator() (const std::string & key, std::string & v) const
Specialized version to lift ambiguity.
operator==() [1/2]
bool mc_rtc::Configuration::operator== (const char * rhs) const
Non-template version for C-style strings comparison.
Returns
True if the comparison matches, false otherwise.
operator==() [2/2]
template<typename T > bool mc_rtc::Configuration::operator== (const T & rhs) const inline
Compare stored values with given value.
Returns
True if the comparison matches, false otherwise.
operator[]()
Configuration mc_rtc::Configuration::operator[] (size_t i) const
If the stored value is an array, return a Configuration element for the i-th element.
Parameters
i Access i-th element
Exceptions
If i >= size()
push() [1/27]
void mc_rtc::Configuration::push (bool value)
Insert a bool element into an array.
Parameters
value Value to add
Exceptions
If the underlying Json value is not an array.
Referenced by add(), and push().
push() [2/27]
void mc_rtc::Configuration::push (int value)
Insert a int element into an array.
See also
push(bool);
push() [3/27]
void mc_rtc::Configuration::push (unsigned int value)
Insert a unsigned int element into an array.
See also
push(bool);
push() [4/27]
void mc_rtc::Configuration::push (int64_t value)
Insert a int64_t element int64_to an array.
See also
push(bool);
push() [5/27]
void mc_rtc::Configuration::push (uint64_t value)
Insert a uint64_t element into an array.
See also
push(bool);
push() [6/27]
void mc_rtc::Configuration::push (double value)
Insert a double element into an array.
See also
push(bool);
push() [7/27]
void mc_rtc::Configuration::push (const std::string & value)
Insert a std::string element into an array.
See also
push(bool);
push() [8/27]
void mc_rtc::Configuration::push (const char * value)
Insert a const char * element into an array Behaves like push(std::string)
See also
push(bool);
push() [9/27]
void mc_rtc::Configuration::push (const Eigen::Vector2d & value)
Insert a Eigen::Vector2d element into an array.
See also
push(bool);
push() [10/27]
void mc_rtc::Configuration::push (const Eigen::Vector3d & value)
Insert a Eigen::Vector3d element into an array.
See also
push(bool);
push() [11/27]
void mc_rtc::Configuration::push (const Eigen::Vector6d & value)
Insert a Eigen::Vector6d element into an array.
See also
push(bool);
push() [12/27]
void mc_rtc::Configuration::push (const Eigen::VectorXd & value)
Insert a Eigen::VectorXd element into an array.
See also
push(bool);
push() [13/27]
void mc_rtc::Configuration::push (const Eigen::Quaterniond & value)
Insert a Eigen::Quaterniond element into an array.
See also
push(bool);
push() [14/27]
void mc_rtc::Configuration::push (const Eigen::Matrix3d & value)
Insert a Eigen::Matrix3d element into an array.
See also
push(bool);
push() [15/27]
void mc_rtc::Configuration::push (const Eigen::Matrix6d & value)
Insert a Eigen::Matrix6d element into an array.
See also
push(bool);
push() [16/27]
void mc_rtc::Configuration::push (const Eigen::MatrixXd & value)
Insert a Eigen::MatrixXd element into an array.
See also
push(bool);
push() [17/27]
void mc_rtc::Configuration::push (const sva::PTransformd & value)
Insert an sva::PTransformd element into an array.
See also
push(bool)
push() [18/27]
void mc_rtc::Configuration::push (const sva::ForceVecd & value)
Insert an sva::ForceVecd element into an array.
See also
push(bool)
push() [19/27]
void mc_rtc::Configuration::push (const sva::MotionVecd & value)
Insert an sva::MotionVecd element into an array.
See also
push(bool)
push() [20/27]
void mc_rtc::Configuration::push (const Configuration & value)
Push a Configuration element into an array.
See also
push(bool);
push() [21/27]
template<typename T , typename... Args, typename std::enable_if< internal::has_configuration_save_object< T, Args... >::value, int >::type = 0> void mc_rtc::Configuration::push (const T & value, Args &&... args) inline
User-defined conversion.
Requires the existence of: mc_rtc::Configuration mc_rtc::ConfigurationLoader<T>::save(const T&, Args ...);
Parameters
key Key of the element
value Value to push
push() [22/27]
template<typename T , typename A = std::allocator<T>, typename... Args> void mc_rtc::Configuration::push (const std::vector< T, A > & value, Args &&... args) inline
Push a vector into the JSON document.
Parameters
value Vector of elements to add
References push().
push() [23/27]
template<typename T , std::size_t N, typename... Args> void mc_rtc::Configuration::push (const std::array< T, N > & value, Args &&... args) inline
Push an array into the JSON document.
Parameters
value Array of elements to add
References push().
push() [24/27]
template<typename T1 , typename T2 , typename... Args> void mc_rtc::Configuration::push (const std::pair< T1, T2 > & value, Args &&... args) inline
Push a pair into the JSON document.
Parameters
value Pair of elements to add
References push().
push() [25/27]
template<typename T , class C = std::less<std::string>, class A = std::allocator<std::pair<const std::string, T>>, typename... Args> void mc_rtc::Configuration::push (const std::map< std::string, T, C, A > & value, Args &&... args) inline
Push a string-indexed map into the JSON document.
Parameters
value Map of elements to add
References add().
push() [26/27]
template<typename T , typename C = std::less<T>, typename A = std::allocator<T>, typename... Args> void mc_rtc::Configuration::push (const std::set< T, C, A > & value, Args &&... args) inline
Push a set into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Set of elements to add
References push().
push() [27/27]
template<typename T , typename H = std::hash<T>, typename E = std::equal_to<T>, typename A = std::allocator<T>, typename... Args> void mc_rtc::Configuration::push (const std::unordered_set< T, H, E, A > & value, Args &&... args) inline
Push an unordered set into the JSON document.
Overwrites existing content if any.
Parameters
key Key of the element
value Set of elements to add
References mc_rtc::Configuration, and push().
push_null()
void mc_rtc::Configuration::push_null ()
Insert a null value into an array.
Exceptions
If the underlying Json value is not an array.
remove()
bool mc_rtc::Configuration::remove (const std::string & key)
Remove a given element.
Has no effect if the element is not present.
Parameters
key Element to remove
Returns
True if the element was removed, false otherwise.
rootArray()
static Configuration mc_rtc::Configuration::rootArray () static
Returns a Configuration with an array as root entry.
This is not valid standard JSON
Referenced by mc_rtc::gui::Color::saveConfig().
save()
void mc_rtc::Configuration::save (const std::string & path, bool pretty = true) const
Save the configuration to a file.
If the path extension is yaml or yml then save in YAML format
Parameters
path Path to the configuration file
pretty Writes a human-readable file, defaults to true
size()
size_t mc_rtc::Configuration::size () const
If the stored value is an array, returns its size, otherwise returns 0.
Returns
Size of the underlying array
toMessagePack() [1/2]
size_t mc_rtc::Configuration::toMessagePack (std::vector< char > & data) const
Convert to MessagePack.
Parameters
data Will hold the message data
Returns
The size of the message, this is different from data.size()
toMessagePack() [2/2]
void mc_rtc::Configuration::toMessagePack (MessagePackBuilder & builder) const
Append to an existing MessagePackBuilder.
The whole configuration will be stored in the MessagePack being built
Parameters
builder MessagePackBuilder instance