mc_rtc::Configuration::Exception Struct Reference
mc_rtc::Configuration::Exception Struct Reference
Exception thrown by this class when something bad occurs.
#include <mc_rtc/Configuration.h>
Public Member Functions
Exception (const std::string &msg)
Constructor.
~Exception () noexcept
virtual const char * what () const noexcept override
void silence () noexcept
Public Attributes
std::string msg
Detailed Description
Exception thrown by this class when something bad occurs.
Constructor & Destructor Documentation
Exception()
mc_rtc::Configuration::Exception::Exception (const std::string & msg)
Constructor.
Parameters
msg The message that will be returned by what()
~Exception()
mc_rtc::Configuration::Exception::~Exception () noexcept
Member Function Documentation
silence()
void mc_rtc::Configuration::Exception::silence () noexcept
Referenced by mc_rtc::Configuration::at(), mc_rtc::fromVectorOrElement(), and mc_rtc::Configuration::operator()().
what()
virtual const char* mc_rtc::Configuration::Exception::what () const override virtual noexcept
Member Data Documentation
msg
std::string mc_rtc::Configuration::Exception::msg