mc_rtc::Configuration::Exception Struct Reference
mc_rtc::Configuration::Exception Struct Reference
Exception thrown by this class when something bad occurs.
#include <mc_rtc/Configuration.h>
Public Member Functions
Exception (const std::string &msg, const Json &v)
Constructor.
Exception (const std::string &msg, const Configuration &c)
Constructor.
~Exception () noexcept
virtual const char * what () const noexcept override
Returns the error message.
void silence () const noexcept
Empty the error message.
const std::string & msg () const noexcept
Returns the error message.
Detailed Description
Exception thrown by this class when something bad occurs.
The exception message is generated when accessed via what() or msg(). It is printed when the exception is deleted and builds a path from the root of the document to the source of the error in order to help the user to find the source of the error. This operation can be expensive. If you do not need the message (e.g. you are attempting various conversions) then you should call silence() to prevent the generation of the message.
Constructor & Destructor Documentation
Exception() [1/2]
mc_rtc::Configuration::Exception::Exception (const std::string & msg, const Json & v)
Constructor.
Parameters
msg Exception message
v Json value that was the source of the exception
Exception() [2/2]
mc_rtc::Configuration::Exception::Exception (const std::string & msg, const Configuration & c) inline
Constructor.
Parameters
msg Exception message
c Configuration object that was the source of the exception
~Exception()
mc_rtc::Configuration::Exception::~Exception () noexcept
Member Function Documentation
msg()
const std::string& mc_rtc::Configuration::Exception::msg () const noexcept
Returns the error message.
silence()
void mc_rtc::Configuration::Exception::silence () const noexcept
Empty the error message.
Referenced by mc_rtc::Configuration::at(), mc_rtc::gui::Color::fromConfig(), mc_rtc::fromVectorOrElement(), and mc_rtc::Configuration::operator()().
what()
virtual const char* mc_rtc::Configuration::Exception::what () const override virtual noexcept
Returns the error message.