mc_filter::LowPassFiniteDifferences< T > Struct Template Reference
mc_filter::LowPassFiniteDifferences< T > Struct Template Reference
Low-pass velocity filter from series of position measurements.
#include <mc_filter/LowPassFiniteDifferences.h>
Public Types
using LowPassT = LowPass< T >
Public Member Functions
LowPassFiniteDifferences (double dt, double period)
Constructor with cutoff period.
void reset (const T &pos, const T &vel)
Reset filter to initial rest value.
void update (const T &newPos)
Update velocity estimate from new position value.
const T & prevValue () const
Public Member Functions inherited from mc_filter::LowPass< T >
LowPass (double dt, double period=0)
Constructor with cutoff period.
double cutoffPeriod () const
Get cutoff period.
void cutoffPeriod (double period)
Set cutoff period.
void reset (const T &value)
Reset position to an initial rest value.
void update (const T &newValue)
Update velocity estimate from new position value.
const T & eval () const
Get filtered velocity.
double dt () const
Protected Attributes
T prevValue_
Protected Attributes inherited from mc_filter::LowPass< T >
double dt_ = 0.005
Detailed Description
template<typename T>
struct mc_filter::LowPassFiniteDifferences< T >
Low-pass velocity filter from series of position measurements.
Expects T to have:
T::Zero() static method
Member Typedef Documentation
LowPassT
template<typename T > using mc_filter::LowPassFiniteDifferences< T >::LowPassT = LowPass<T>
Constructor & Destructor Documentation
LowPassFiniteDifferences()
template<typename T > mc_filter::LowPassFiniteDifferences< T >::LowPassFiniteDifferences (double dt, double period) inline
Constructor with cutoff period.
Parameters
dt Sampling period.
period Cutoff period.
References mc_filter::LowPass< T >::reset().
Member Function Documentation
prevValue()
template<typename T > const T& mc_filter::LowPassFiniteDifferences< T >::prevValue () const inline
References mc_filter::LowPassFiniteDifferences< T >::prevValue_.
reset()
template<typename T > void mc_filter::LowPassFiniteDifferences< T >::reset (const T & pos, const T & vel) inline
Reset filter to initial rest value.
Parameters
pos Initial position.
vel Initial velocity.
References mc_filter::LowPassFiniteDifferences< T >::prevValue_, and mc_filter::LowPass< T >::reset().
update()
template<typename T > void mc_filter::LowPassFiniteDifferences< T >::update (const T & newPos) inline
Update velocity estimate from new position value.
Parameters
newPos New observed position.
References mc_filter::LowPass< T >::dt(), mc_filter::LowPassFiniteDifferences< T >::prevValue_, and mc_filter::LowPass< T >::update().
Member Data Documentation
prevValue_
template<typename T > T mc_filter::LowPassFiniteDifferences< T >::prevValue_ protected
Referenced by mc_filter::LowPassFiniteDifferences< T >::prevValue(), mc_filter::LowPassFiniteDifferences< T >::reset(), and mc_filter::LowPassFiniteDifferences< T >::update().