mc_rtc::gui::ArrowROImpl< GetStart, GetEnd > Struct Template Reference
mc_rtc::gui::ArrowROImpl< GetStart, GetEnd > Struct Template Reference
Arrow should display an arrow from the point at the start to the point at the end.
#include <mc_rtc/gui/Arrow.h>
Public Member Functions
ArrowROImpl (const std::string &name, const ArrowConfig &config, GetStart get_start_fn, GetEnd get_end_fn)
ArrowROImpl ()
Invalid element.
void write (mc_rtc::MessagePackBuilder &builder, bool ro=true)
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Arrow
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetStart, typename GetEnd>
struct mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >
Arrow should display an arrow from the point at the start to the point at the end.
An ArrowConfig can be provided to specify how the arrow should be displayed
Template Parameters
GetStart Returns an Eigen::Vector3d representing the starting point
GetEnd Returns an Eigen::Vector3d representing the end point
Constructor & Destructor Documentation
ArrowROImpl() [1/2]
template<typename GetStart, typename GetEnd> mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::ArrowROImpl (const std::string & name, const ArrowConfig & config, GetStart get_start_fn, GetEnd get_end_fn) inline
ArrowROImpl() [2/2]
template<typename GetStart, typename GetEnd> mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::ArrowROImpl () inline
Invalid element.
Member Function Documentation
write()
template<typename GetStart, typename GetEnd> void mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write (mc_rtc::MessagePackBuilder & builder, bool ro = true) inline
References mc_rtc::MessagePackBuilder::write(), mc_rtc::gui::Element::write(), and mc_rtc::gui::ArrowConfig::write().
Referenced by mc_rtc::gui::ArrowImpl< GetStart, SetStart, GetEnd, SetEnd >::write().
write_size()
template<typename GetStart, typename GetEnd> static constexpr size_t mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write_size () inline static
References mc_rtc::gui::Element::write_size(), and mc_rtc::gui::ArrowConfig::write_size().
Member Data Documentation
type
template<typename GetStart, typename GetEnd> constexpr auto mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::type = Elements::Arrow static