mc_rtc::gui::ForceROImpl< GetForce, GetSurface > Struct Template Reference
mc_rtc::gui::ForceROImpl< GetForce, GetSurface > Struct Template Reference
Force should display a force vector in 3D environment.
#include <mc_rtc/gui/Force.h>
Public Member Functions
ForceROImpl (const std::string &name, const ForceConfig &config, GetForce get_force_fn, GetSurface get_surface_fn)
void write (mc_rtc::MessagePackBuilder &builder, bool ro=true)
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Force
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetForce, typename GetSurface>
struct mc_rtc::gui::ForceROImpl< GetForce, GetSurface >
Force should display a force vector in 3D environment.
The display style of the element can be configured
See also
ForceConfig
Additionally an ArrayLabel with labels {"cx", "cy", "cz", "fx", "fy", "fz"} is created
Template Parameters
GetForce Should return an sva::ForceVecd
GetSurface Should return an sva::PTransformd where the force will be displayed
Constructor & Destructor Documentation
ForceROImpl()
template<typename GetForce, typename GetSurface> mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::ForceROImpl (const std::string & name, const ForceConfig & config, GetForce get_force_fn, GetSurface get_surface_fn) inline
Member Function Documentation
write()
template<typename GetForce, typename GetSurface> void mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write (mc_rtc::MessagePackBuilder & builder, bool ro = true) inline
References mc_rtc::MessagePackBuilder::write(), mc_rtc::gui::Element::write(), and mc_rtc::gui::ForceConfig::write().
write_size()
template<typename GetForce, typename GetSurface> static constexpr size_t mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write_size () inline static
References mc_rtc::gui::Element::write_size(), and mc_rtc::gui::ForceConfig::write_size().
Member Data Documentation
type
template<typename GetForce, typename GetSurface> constexpr auto mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::type = Elements::Force static