mc_rtc::gui::plot::impl::Abscissa< GetT > Struct Template Reference
mc_rtc::gui::plot::impl::Abscissa< GetT > Struct Template Reference
For a given plot, this holds options on the abscissa axis and a callback that returns the current abscissa value.
#include <mc_rtc/gui/plot/Abscissa.h>
Public Member Functions
Abscissa (AxisConfiguration config, GetT get_fn)
void write (mc_rtc::MessagePackBuilder &builder) const
Abscissa & range (const Range &range)
Abscissa & min (double min)
Abscissa & max (double max)
Static Public Attributes
static constexpr Type type = Type::Abscissa
Detailed Description
template<typename GetT>
struct mc_rtc::gui::plot::impl::Abscissa< GetT >
For a given plot, this holds options on the abscissa axis and a callback that returns the current abscissa value.
Constructor & Destructor Documentation
Abscissa()
template<typename GetT> mc_rtc::gui::plot::impl::Abscissa< GetT >::Abscissa (AxisConfiguration config, GetT get_fn) inline
Member Function Documentation
max()
template<typename GetT> Abscissa& mc_rtc::gui::plot::impl::Abscissa< GetT >::max (double max) inline
References mc_rtc::gui::plot::Range::max, and mc_rtc::gui::plot::AxisConfiguration::range.
min()
template<typename GetT> Abscissa& mc_rtc::gui::plot::impl::Abscissa< GetT >::min (double min) inline
References mc_rtc::gui::plot::Range::min, and mc_rtc::gui::plot::AxisConfiguration::range.
range()
template<typename GetT> Abscissa& mc_rtc::gui::plot::impl::Abscissa< GetT >::range (const Range & range) inline
References mc_rtc::gui::plot::AxisConfiguration::range.
write()
template<typename GetT> void mc_rtc::gui::plot::impl::Abscissa< GetT >::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::plot::AxisConfiguration::write().
Member Data Documentation
type
template<typename GetT> constexpr Type mc_rtc::gui::plot::impl::Abscissa< GetT >::type = Type::Abscissa static