mc_rtc::gui::details::StaticTableImpl< GetData > Struct Template Reference
mc_rtc::gui::details::StaticTableImpl< GetData > Struct Template Reference
Table should display a table of heterogeneous data.
#include <mc_rtc/gui/Table.h>
Public Member Functions
StaticTableImpl (const std::string &name, std::vector< std::string > header, std::vector< std::string > format, GetData get_data_fn)
void write (mc_rtc::MessagePackBuilder &builder)
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Table
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetData>
struct mc_rtc::gui::details::StaticTableImpl< GetData >
Table should display a table of heterogeneous data.
The user is responsible for making sure the header size and data size match
In this variant, the header data is static
Template Parameters
GetData should return data that can be converted to a JSON array of array (e.g. vector<vector<T>> or vector<tuple<...>>)
Constructor & Destructor Documentation
StaticTableImpl()
template<typename GetData> mc_rtc::gui::details::StaticTableImpl< GetData >::StaticTableImpl (const std::string & name, std::vector< std::string > header, std::vector< std::string > format, GetData get_data_fn) inline
Member Function Documentation
write()
template<typename GetData> void mc_rtc::gui::details::StaticTableImpl< GetData >::write (mc_rtc::MessagePackBuilder & builder) inline
References mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::Element::write().
write_size()
template<typename GetData> static constexpr size_t mc_rtc::gui::details::StaticTableImpl< GetData >::write_size () inline static
References mc_rtc::gui::Element::write_size().
Member Data Documentation
type
template<typename GetData> constexpr auto mc_rtc::gui::details::StaticTableImpl< GetData >::type = Elements::Table static