mc_rtc::gui::NumberSliderImpl< GetT, SetT > Struct Template Reference
mc_rtc::gui::NumberSliderImpl< GetT, SetT > Struct Template Reference
NumberSlider should display a number slider with minimum and maximum values specified.
#include <mc_rtc/gui/NumberSlider.h>
Public Member Functions
NumberSliderImpl (const std::string &name, GetT get_fn, SetT set_fn, double min, double max)
NumberSliderImpl ()
void write (mc_rtc::MessagePackBuilder &writer)
Public Member Functions inherited from mc_rtc::gui::CommonInputImpl< GetT, SetT >
CommonInputImpl (const std::string &name, GetT get_fn, SetT set_fn)
CommonInputImpl ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::CallbackElement< DataElement< GetT >, SetT >
bool handleRequest (const mc_rtc::Configuration &data)
CallbackElement (const std::string &name, SetT cb, Args &&... args)
CallbackElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
void write (mc_rtc::MessagePackBuilder &builder)
DataElement (const std::string &name, GetT get_fn)
Constructor.
DataElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::NumberSlider
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::CallbackElement< DataElement< GetT >, SetT >
SetT cb_
Protected Attributes inherited from mc_rtc::gui::DataElement< GetT >
GetT get_fn_
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetT, typename SetT>
struct mc_rtc::gui::NumberSliderImpl< GetT, SetT >
NumberSlider should display a number slider with minimum and maximum values specified.
Template Parameters
GetT Returns a numeric type
SetT Called when the slider is manipulated by the client
Constructor & Destructor Documentation
NumberSliderImpl() [1/2]
template<typename GetT, typename SetT> mc_rtc::gui::NumberSliderImpl< GetT, SetT >::NumberSliderImpl (const std::string & name, GetT get_fn, SetT set_fn, double min, double max) inline
NumberSliderImpl() [2/2]
template<typename GetT, typename SetT> mc_rtc::gui::NumberSliderImpl< GetT, SetT >::NumberSliderImpl () inline
Member Function Documentation
write()
template<typename GetT, typename SetT> void mc_rtc::gui::NumberSliderImpl< GetT, SetT >::write (mc_rtc::MessagePackBuilder & writer) inline
References mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::DataElement< GetT >::write().
write_size()
template<typename GetT, typename SetT> static constexpr size_t mc_rtc::gui::NumberSliderImpl< GetT, SetT >::write_size () inline static
References mc_rtc::gui::DataElement< GetT >::write_size().
Member Data Documentation
type
template<typename GetT, typename SetT> constexpr auto mc_rtc::gui::NumberSliderImpl< GetT, SetT >::type = Elements::NumberSlider static