mc_rtc::gui::plot::Range Struct Reference
mc_rtc::gui::plot::Range Struct Reference
Range for abscissa or ordinate display.
#include <mc_rtc/gui/plot/types.h>
Public Member Functions
Range ()=default
Range (double min, double max)
void load (const mc_rtc::Configuration &config)
void write (mc_rtc::MessagePackBuilder &builder) const
Public Attributes
double min = -inf
double max = inf
Static Public Attributes
static constexpr double inf = std::numeric_limits<double>::infinity()
Detailed Description
Range for abscissa or ordinate display.
Setting the min to -inf or max to +inf tells the client to compute the related limit (default)
Constructor & Destructor Documentation
Range() [1/2]
mc_rtc::gui::plot::Range::Range () default
Range() [2/2]
mc_rtc::gui::plot::Range::Range (double min, double max) inline
Member Function Documentation
load()
void mc_rtc::gui::plot::Range::load (const mc_rtc::Configuration & config) inline
Referenced by mc_rtc::gui::plot::AxisConfiguration::load().
write()
void mc_rtc::gui::plot::Range::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), and mc_rtc::MessagePackBuilder::write().
Referenced by mc_rtc::gui::plot::AxisConfiguration::write().
Member Data Documentation
inf
constexpr double mc_rtc::gui::plot::Range::inf = std::numeric_limits<double>::infinity() static
max
double mc_rtc::gui::plot::Range::max = inf
Referenced by mc_rtc::gui::plot::impl::Abscissa< GetT >::max(), and mc_rtc::gui::plot::AxisConfiguration::max().
min
double mc_rtc::gui::plot::Range::min = -inf
Referenced by mc_rtc::gui::plot::impl::Abscissa< GetT >::min(), and mc_rtc::gui::plot::AxisConfiguration::min().