mc_rtc::gui::plot::impl::Polygons< GetT > Struct Template Reference
mc_rtc::gui::plot::impl::Polygons< GetT > Struct Template Reference
This holds information about multiple polygons.
#include <mc_rtc/gui/plot/Polygons.h>
Public Member Functions
Polygons (const std::string &name, GetT get_fn, Side side)
void write (mc_rtc::MessagePackBuilder &builder) const
Polygons & side (Side side)
Static Public Attributes
static constexpr Type type = Type::Polygons
Detailed Description
template<typename GetT>
struct mc_rtc::gui::plot::impl::Polygons< GetT >
This holds information about multiple polygons.
Constructor & Destructor Documentation
Polygons()
template<typename GetT> mc_rtc::gui::plot::impl::Polygons< GetT >::Polygons (const std::string & name, GetT get_fn, Side side) inline
Member Function Documentation
side()
template<typename GetT> Polygons& mc_rtc::gui::plot::impl::Polygons< GetT >::side (Side side) inline
Referenced by mc_rtc::gui::plot::Polygons().
write()
template<typename GetT> void mc_rtc::gui::plot::impl::Polygons< GetT >::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), and mc_rtc::MessagePackBuilder::write().
Member Data Documentation
type
template<typename GetT> constexpr Type mc_rtc::gui::plot::impl::Polygons< GetT >::type = Type::Polygons static