mc_rtc::gui::ForceConfig Struct Reference
mc_rtc::gui::ForceConfig Struct Reference
#include <mc_rtc/gui/types.h>
Public Member Functions
ForceConfig ()
ForceConfig (const Color &color)
ForceConfig (const mc_rtc::Configuration &config)
void fromMessagePack (const mc_rtc::Configuration &config)
void fromConfig (const mc_rtc::Configuration &config)
mc_rtc::Configuration saveConfig () const
void write (mc_rtc::MessagePackBuilder &out) const
Public Member Functions inherited from mc_rtc::gui::ArrowConfig
ArrowConfig ()
ArrowConfig (const Color &color)
ArrowConfig (const mc_rtc::Configuration &config)
void fromMessagePack (const mc_rtc::Configuration &config)
void fromConfig (const mc_rtc::Configuration &config)
mc_rtc::Configuration saveConfig () const
void write (mc_rtc::MessagePackBuilder &out) const
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::ArrowConfig
static constexpr size_t write_size ()
Public Attributes
double force_scale = 0.0015
Public Attributes inherited from mc_rtc::gui::ArrowConfig
double head_diam = 0.015
double head_len = 0.05
double shaft_diam = 0.015
double scale = 0.0015
double start_point_scale = 0.0
double end_point_scale = 0.0
Color color
Constructor & Destructor Documentation
ForceConfig() [1/3]
mc_rtc::gui::ForceConfig::ForceConfig () inline
ForceConfig() [2/3]
mc_rtc::gui::ForceConfig::ForceConfig (const Color & color) inline
ForceConfig() [3/3]
mc_rtc::gui::ForceConfig::ForceConfig (const mc_rtc::Configuration & config) inline
Member Function Documentation
fromConfig()
void mc_rtc::gui::ForceConfig::fromConfig (const mc_rtc::Configuration & config) inline
References mc_rtc::gui::ArrowConfig::fromConfig().
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::ForceConfig >::load().
fromMessagePack()
void mc_rtc::gui::ForceConfig::fromMessagePack (const mc_rtc::Configuration & config) inline
References mc_rtc::gui::ArrowConfig::fromMessagePack().
saveConfig()
mc_rtc::Configuration mc_rtc::gui::ForceConfig::saveConfig () const inline
References mc_rtc::Configuration::add(), and mc_rtc::gui::ArrowConfig::saveConfig().
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::ForceConfig >::save().
write()
void mc_rtc::gui::ForceConfig::write (mc_rtc::MessagePackBuilder & out) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::ArrowConfig::write().
Referenced by mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write().
write_size()
static constexpr size_t mc_rtc::gui::ForceConfig::write_size () inline static
Referenced by mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write_size().
Member Data Documentation
force_scale
double mc_rtc::gui::ForceConfig::force_scale = 0.0015