mc_rbdyn::BodySensor Struct Reference
mc_rbdyn::BodySensor Struct Reference
This structure defines a body sensor, that is a sensor that provides dynamic information about a body.
#include <mc_rbdyn/BodySensor.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW BodySensor ()
Default constructor, does not represent a valid body sensor.
BodySensor (const std::string &name, const std::string &bodyName, const sva::PTransformd &X_b_s)
Constructor.
const std::string & name () const
Get the sensor's name.
const std::string & parentBody () const
Get the sensor's parent body name.
const sva::PTransformd & X_b_s () const
Return the transformation from the parent body to the sensor.
const Eigen::Vector3d & position () const
Return the sensor's position reading, Zero if not provided.
void position (const Eigen::Vector3d &position)
Set the sensor's position reading.
const Eigen::Quaterniond & orientation () const
Return the sensor's orientation reading, Identity if not provided.
void orientation (const Eigen::Quaterniond &orientation)
Set the sensor's orientation reading.
const Eigen::Vector3d & linearVelocity () const
Return the sensor's linear velocity reading, Zero if not provided.
void linearVelocity (const Eigen::Vector3d &linear_velocity)
Set the sensor's linear velocity reading.
const Eigen::Vector3d & angularVelocity () const
Return the sensor's angular velocity reading, Zero if not provided.
void angularVelocity (const Eigen::Vector3d &angular_velocity)
Set the sensor's angular velocity reading.
const Eigen::Vector3d & acceleration () const
Return the sensor's acceleration reading, Zero if not provided.
void acceleration (const Eigen::Vector3d &acceleration)
Set the sensor's acceleration reading.
Detailed Description
This structure defines a body sensor, that is a sensor that provides dynamic information about a body.
It would typically be used to represent an IMU reading but in more ideal (simulation, external tracking system...) it can hold more information
Constructor & Destructor Documentation
BodySensor() [1/2]
EIGEN_MAKE_ALIGNED_OPERATOR_NEW mc_rbdyn::BodySensor::BodySensor () inline
Default constructor, does not represent a valid body sensor.
BodySensor() [2/2]
mc_rbdyn::BodySensor::BodySensor (const std::string & name, const std::string & bodyName, const sva::PTransformd & X_b_s) inline
Constructor.
Parameters
name Name of the sensor
bodyName Name of the body to which the sensor is attached
X_b_s Transformation from the parent body to the sensor
Member Function Documentation
acceleration() [1/2]
const Eigen::Vector3d& mc_rbdyn::BodySensor::acceleration () const inline
Return the sensor's acceleration reading, Zero if not provided.
Referenced by acceleration().
acceleration() [2/2]
void mc_rbdyn::BodySensor::acceleration (const Eigen::Vector3d & acceleration) inline
Set the sensor's acceleration reading.
References acceleration().
angularVelocity() [1/2]
const Eigen::Vector3d& mc_rbdyn::BodySensor::angularVelocity () const inline
Return the sensor's angular velocity reading, Zero if not provided.
angularVelocity() [2/2]
void mc_rbdyn::BodySensor::angularVelocity (const Eigen::Vector3d & angular_velocity) inline
Set the sensor's angular velocity reading.
linearVelocity() [1/2]
const Eigen::Vector3d& mc_rbdyn::BodySensor::linearVelocity () const inline
Return the sensor's linear velocity reading, Zero if not provided.
linearVelocity() [2/2]
void mc_rbdyn::BodySensor::linearVelocity (const Eigen::Vector3d & linear_velocity) inline
Set the sensor's linear velocity reading.
name()
const std::string& mc_rbdyn::BodySensor::name () const inline
Get the sensor's name.
orientation() [1/2]
const Eigen::Quaterniond& mc_rbdyn::BodySensor::orientation () const inline
Return the sensor's orientation reading, Identity if not provided.
Referenced by orientation().
orientation() [2/2]
void mc_rbdyn::BodySensor::orientation (const Eigen::Quaterniond & orientation) inline
Set the sensor's orientation reading.
Note
By convention, this rotation should be given from the inertial frame (i.e. a fixed frame in the real world) to a body frame of the robot. For instance, on HRP-4 the body sensor orientation goes from the inertial frame to the "base_link" frame.
References orientation().
parentBody()
const std::string& mc_rbdyn::BodySensor::parentBody () const inline
Get the sensor's parent body name.
position() [1/2]
const Eigen::Vector3d& mc_rbdyn::BodySensor::position () const inline
Return the sensor's position reading, Zero if not provided.
Referenced by position().
position() [2/2]
void mc_rbdyn::BodySensor::position (const Eigen::Vector3d & position) inline
Set the sensor's position reading.
References position().
X_b_s()
const sva::PTransformd& mc_rbdyn::BodySensor::X_b_s () const inline
Return the transformation from the parent body to the sensor.