mc_rtc::gui::ArrowConfig Struct Reference
mc_rtc::gui::ArrowConfig Struct Reference
#include <mc_rtc/gui/types.h>
Public Member Functions
ArrowConfig ()
ArrowConfig (const Color &color)
ArrowConfig (const mc_rtc::Configuration &config)
void fromMessagePack (const mc_rtc::Configuration &config)
void fromConfig (const mc_rtc::Configuration &config)
mc_rtc::Configuration saveConfig () const
void write (mc_rtc::MessagePackBuilder &out) const
Static Public Member Functions
static constexpr size_t write_size ()
Public Attributes
double head_diam = 0.015
double head_len = 0.05
double shaft_diam = 0.015
double scale = 0.0015
double start_point_scale = 0.0
double end_point_scale = 0.0
Color color
Constructor & Destructor Documentation
ArrowConfig() [1/3]
mc_rtc::gui::ArrowConfig::ArrowConfig () inline
ArrowConfig() [2/3]
mc_rtc::gui::ArrowConfig::ArrowConfig (const Color & color) inline
ArrowConfig() [3/3]
mc_rtc::gui::ArrowConfig::ArrowConfig (const mc_rtc::Configuration & config) inline
Member Function Documentation
fromConfig()
void mc_rtc::gui::ArrowConfig::fromConfig (const mc_rtc::Configuration & config) inline
Referenced by mc_rtc::gui::ForceConfig::fromConfig(), and mc_rtc::ConfigurationLoader< mc_rtc::gui::ArrowConfig >::load().
fromMessagePack()
void mc_rtc::gui::ArrowConfig::fromMessagePack (const mc_rtc::Configuration & config) inline
References mc_rtc::Configuration::fromMessagePack().
Referenced by mc_rtc::gui::ForceConfig::fromMessagePack().
saveConfig()
mc_rtc::Configuration mc_rtc::gui::ArrowConfig::saveConfig () const inline
References mc_rtc::Configuration::add().
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::ArrowConfig >::save(), and mc_rtc::gui::ForceConfig::saveConfig().
write()
void mc_rtc::gui::ArrowConfig::write (mc_rtc::MessagePackBuilder & out) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), and mc_rtc::MessagePackBuilder::write().
Referenced by mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write(), and mc_rtc::gui::ForceConfig::write().
write_size()
static constexpr size_t mc_rtc::gui::ArrowConfig::write_size () inline static
Referenced by mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write_size().
Member Data Documentation
color
Color mc_rtc::gui::ArrowConfig::color
end_point_scale
double mc_rtc::gui::ArrowConfig::end_point_scale = 0.0
head_diam
double mc_rtc::gui::ArrowConfig::head_diam = 0.015
head_len
double mc_rtc::gui::ArrowConfig::head_len = 0.05
scale
double mc_rtc::gui::ArrowConfig::scale = 0.0015
shaft_diam
double mc_rtc::gui::ArrowConfig::shaft_diam = 0.015
start_point_scale
double mc_rtc::gui::ArrowConfig::start_point_scale = 0.0