mc_rtc::gui::LineConfig Struct Reference
mc_rtc::gui::LineConfig Struct Reference
#include <mc_rtc/gui/types.h>
Public Member Functions
LineConfig ()
LineConfig (const Color &color, double width=0.01, const LineStyle &style=LineStyle::Solid)
LineConfig (const mc_rtc::Configuration &config)
void fromMessagePack (const mc_rtc::Configuration &config)
void fromConfig (const mc_rtc::Configuration &config)
mc_rtc::Configuration saveConfig () const
void write (mc_rtc::MessagePackBuilder &out) const
Static Public Member Functions
static constexpr size_t write_size ()
Public Attributes
Color color = {1, 0, 0}
double width = 0.01
LineStyle style = LineStyle::Solid
Constructor & Destructor Documentation
LineConfig() [1/3]
mc_rtc::gui::LineConfig::LineConfig () inline
LineConfig() [2/3]
mc_rtc::gui::LineConfig::LineConfig (const Color & color, double width = 0.01, const LineStyle & style = LineStyle::Solid) inline
LineConfig() [3/3]
mc_rtc::gui::LineConfig::LineConfig (const mc_rtc::Configuration & config) inline
Member Function Documentation
fromConfig()
void mc_rtc::gui::LineConfig::fromConfig (const mc_rtc::Configuration & config) inline
References mc_rtc::gui::Dotted, mc_rtc::Configuration::has(), and mc_rtc::gui::Solid.
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::LineConfig >::load().
fromMessagePack()
void mc_rtc::gui::LineConfig::fromMessagePack (const mc_rtc::Configuration & config) inline
References mc_rtc::gui::Color::fromMessagePack().
saveConfig()
mc_rtc::Configuration mc_rtc::gui::LineConfig::saveConfig () const inline
References mc_rtc::Configuration::add(), mc_rtc::gui::Dotted, and mc_rtc::gui::Solid.
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::LineConfig >::save().
write()
void mc_rtc::gui::LineConfig::write (mc_rtc::MessagePackBuilder & out) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::Color::write().
Referenced by mc_rtc::gui::TrajectoryImpl< GetT >::write().
write_size()
static constexpr size_t mc_rtc::gui::LineConfig::write_size () inline static
Referenced by mc_rtc::gui::TrajectoryImpl< GetT >::write_size().
Member Data Documentation
color
Color mc_rtc::gui::LineConfig::color = {1, 0, 0}
style
LineStyle mc_rtc::gui::LineConfig::style = LineStyle::Solid
width
double mc_rtc::gui::LineConfig::width = 0.01