mc_rtc::MessagePackBuilder Struct Reference
mc_rtc::MessagePackBuilder Struct Reference
Helper class to build a MessagePack message.
#include <mc_rtc/MessagePackBuilder.h>
Public Member Functions
MessagePackBuilder (std::vector< char > &buffer)
Constructor.
~MessagePackBuilder ()
Destructor.
void start_array (size_t size)
Start serializing an array.
void finish_array ()
Finished serializing an array.
void start_map (size_t size)
Start serializing a map.
void finish_map ()
Finished serializing a map.
void write_object (const char *data, size_t s)
Write an existing object into the object being constructed.
size_t finish ()
Finish building the message.
Add data to the MessagePack (basic)
These overload set allows to write basic data to the MessagePack
void write ()
Write null.
void write (bool b)
Write a bool.
void write (int8_t i)
Write a int8_t.
void write (int16_t i)
Write a int16_t.
void write (int32_t i)
Write a int32_t.
void write (int64_t i)
Write a int64_t.
void write (uint8_t i)
Write a uint8_t.
void write (uint16_t i)
Write a uint16_t.
void write (uint32_t i)
Write a uint32_t.
void write (uint64_t i)
Write a uint64_t.
void write (float f)
Write a float.
void write (double d)
Write a double.
void write (const std::string &s)
Write an std::string.
void write (const char *s)
Write a C-style string.
void write (const char *s, size_t len)
Write a C-style string with available size.
Add data to the MessagePack (extended)
These functions serialize common types used throughout mc_rtc.
This does not use MessagePack extension mechanism. Instead, this serializes to simple primitives, if type retrieval is desired, one should implement a specific mechanism.
void write (const Eigen::Vector2d &v)
Write an Eigen::Vector2d.
void write (const Eigen::Vector3d &v)
Write an Eigen::Vector3d.
void write (const Eigen::Vector6d &v)
Write an Eigen::Vector6d.
void write (const Eigen::VectorXd &v)
Write an Eigen::VectorXd.
void write (const Eigen::Quaterniond &q)
Write an Eigen::Quaterniond.
void write (const Eigen::Matrix3d &m)
Write an Eigen::Matrix3d.
void write (const sva::PTransformd &pt)
Write an sva::PTransformd.
void write (const sva::ForceVecd &fv)
Write an sva::ForceVecd.
void write (const sva::MotionVecd &mv)
Write an sva::MotionVecd.
void write (const mc_rtc::Configuration &config)
Write an mc_rtc::Configuration.
Add data to the MessagePack (containers)
These functions support the serialization of standard containers of serializable objects.
template<typename T , typename A >
void write (const std::vector< T, A > &v)
Write an std::vector<T, A>
template<typename T , std::size_t N>
void write (const std::array< T, N > &a)
Write an std::array<T, N>
template<typename T1 , typename T2 >
void write (const std::pair< T1, T2 > &p)
Write an std::pair<T1, T2>
template<typename KeyT , typename T , typename C , typename A >
void write (const std::map< KeyT, T, C, A > &m)
Write an std::map<KeyT, T, C, A>
template<typename T , typename C , typename A >
void write (const std::set< T, C, A > &s)
Write an std::set<T, C, A>
template<typename... Args>
void write (const std::tuple< Args... > &t)
Write an std::tuple<Args...>
Detailed Description
Helper class to build a MessagePack message.
After a message has been built, the builder object must be discarded to create a new message.
Constructor & Destructor Documentation
MessagePackBuilder()
mc_rtc::MessagePackBuilder::MessagePackBuilder (std::vector< char > & buffer)
Constructor.
Parameters
buffer Buffer used to store the data, it may grow depending on the needs
~MessagePackBuilder()
mc_rtc::MessagePackBuilder::~MessagePackBuilder ()
Destructor.
Member Function Documentation
finish()
size_t mc_rtc::MessagePackBuilder::finish ()
Finish building the message.
Afterwards, data cannot be appended to the builder
Returns
Effective size of MessagePack data, note that buffer.size() is likely different
Referenced by mc_rtc::gui::FormImpl< Callback >::addElement(), and mc_rtc::gui::FormImpl< Callback >::FormImpl().
finish_array()
void mc_rtc::MessagePackBuilder::finish_array ()
Finished serializing an array.
Referenced by mc_rtc::gui::FormImpl< Callback >::addElement(), mc_rtc::gui::FormImpl< Callback >::FormImpl(), mc_rtc::gui::plot::impl::Polygons< GetT >::write(), mc_rtc::gui::plot::impl::Polygon< GetT >::write(), mc_rtc::gui::plot::impl::Abscissa< GetT >::write(), mc_rtc::gui::plot::impl::Ordinate< GetT >::write(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write(), mc_rtc::gui::FormImpl< Callback >::write(), mc_rtc::gui::Color::write(), mc_rtc::gui::plot::Range::write(), mc_rtc::gui::LineConfig::write(), mc_rtc::gui::plot::AxisConfiguration::write(), mc_rtc::gui::ArrowConfig::write(), mc_rtc::gui::ForceConfig::write(), mc_rtc::gui::plot::PolygonDescription::write(), and mc_rtc::gui::PointConfig::write().
finish_map()
void mc_rtc::MessagePackBuilder::finish_map ()
Finished serializing a map.
start_array()
void mc_rtc::MessagePackBuilder::start_array (size_t size)
Start serializing an array.
Parameters
size Size of the array
Referenced by mc_rtc::gui::FormImpl< Callback >::addElement(), mc_rtc::gui::FormImpl< Callback >::FormImpl(), mc_rtc::gui::plot::impl::Polygons< GetT >::write(), mc_rtc::gui::plot::impl::Polygon< GetT >::write(), mc_rtc::gui::plot::impl::Abscissa< GetT >::write(), mc_rtc::gui::plot::impl::Ordinate< GetT >::write(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write(), mc_rtc::gui::FormImpl< Callback >::write(), mc_rtc::gui::Color::write(), mc_rtc::gui::plot::Range::write(), mc_rtc::gui::LineConfig::write(), mc_rtc::gui::plot::AxisConfiguration::write(), mc_rtc::gui::ArrowConfig::write(), mc_rtc::gui::ForceConfig::write(), mc_rtc::gui::plot::PolygonDescription::write(), and mc_rtc::gui::PointConfig::write().
start_map()
void mc_rtc::MessagePackBuilder::start_map (size_t size)
Start serializing a map.
Parameters
size Size of the map, the map must then contains 2*size elements
write() [1/31]
void mc_rtc::MessagePackBuilder::write ()
Write null.
Referenced by mc_rtc::gui::plot::impl::Polygon< GetT >::write(), mc_rtc::gui::plot::impl::Polygons< GetT >::write(), mc_rtc::gui::plot::impl::Abscissa< GetT >::write(), mc_rtc::gui::plot::impl::Ordinate< GetT >::write(), mc_rtc::gui::SchemaImpl< Callback >::write(), mc_rtc::gui::DataComboInputImpl< GetT, SetT >::write(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write(), mc_rtc::gui::ComboInputImpl< GetT, SetT >::write(), mc_rtc::gui::NumberSliderImpl< GetT, SetT >::write(), mc_rtc::gui::XYThetaROImpl< GetT >::write(), mc_rtc::gui::RotationROImpl< GetT >::write(), mc_rtc::gui::ArrayLabelImpl< GetT >::write(), mc_rtc::gui::ArrayInputImpl< GetT, SetT >::write(), mc_rtc::gui::TransformROImpl< GetT >::write(), mc_rtc::gui::Point3DROImpl< GetT >::write(), mc_rtc::gui::details::TableImpl< GetHeader, GetData >::write(), mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write(), mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write(), mc_rtc::gui::Color::write(), mc_rtc::gui::XYThetaImpl< GetT, SetT >::write(), mc_rtc::gui::RotationImpl< GetT, SetT >::write(), mc_rtc::gui::details::FormattedTableImpl< GetHeader, GetFormat, GetData >::write(), mc_rtc::gui::TransformImpl< GetT, SetT >::write(), mc_rtc::gui::Point3DImpl< GetT, SetT >::write(), mc_rtc::gui::plot::Range::write(), mc_rtc::gui::FormElement< FormArrayInput< T >, Elements::ArrayInput >::write(), mc_rtc::gui::LineConfig::write(), mc_rtc::gui::details::StaticTableImpl< GetData >::write(), mc_rtc::gui::DataElement< GetT >::write(), mc_rtc::log::LogWriter< T >::write(), mc_rtc::gui::plot::AxisConfiguration::write(), mc_rtc::gui::ArrowConfig::write(), mc_rtc::gui::ForceConfig::write(), mc_rtc::gui::plot::PolygonDescription::write(), mc_rtc::gui::PointConfig::write(), mc_rtc::gui::FormDataInput< T, element >::write_(), mc_rtc::gui::FormArrayInput< T >::write_(), mc_rtc::gui::FormComboInput::write_(), and mc_rtc::gui::FormDataComboInput::write_().
write() [2/31]
void mc_rtc::MessagePackBuilder::write (bool b)
Write a bool.
write() [3/31]
void mc_rtc::MessagePackBuilder::write (int8_t i)
Write a int8_t.
write() [4/31]
void mc_rtc::MessagePackBuilder::write (int16_t i)
Write a int16_t.
write() [5/31]
void mc_rtc::MessagePackBuilder::write (int32_t i)
Write a int32_t.
write() [6/31]
void mc_rtc::MessagePackBuilder::write (int64_t i)
Write a int64_t.
write() [7/31]
void mc_rtc::MessagePackBuilder::write (uint8_t i)
Write a uint8_t.
write() [8/31]
void mc_rtc::MessagePackBuilder::write (uint16_t i)
Write a uint16_t.
write() [9/31]
void mc_rtc::MessagePackBuilder::write (uint32_t i)
Write a uint32_t.
write() [10/31]
void mc_rtc::MessagePackBuilder::write (uint64_t i)
Write a uint64_t.
write() [11/31]
void mc_rtc::MessagePackBuilder::write (float f)
Write a float.
write() [12/31]
void mc_rtc::MessagePackBuilder::write (double d)
Write a double.
write() [13/31]
void mc_rtc::MessagePackBuilder::write (const std::string & s)
Write an std::string.
write() [14/31]
void mc_rtc::MessagePackBuilder::write (const char * s)
Write a C-style string.
write() [15/31]
void mc_rtc::MessagePackBuilder::write (const char * s, size_t len)
Write a C-style string with available size.
write() [16/31]
void mc_rtc::MessagePackBuilder::write (const Eigen::Vector2d & v)
Write an Eigen::Vector2d.
Serializes as an array of size 2
write() [17/31]
void mc_rtc::MessagePackBuilder::write (const Eigen::Vector3d & v)
Write an Eigen::Vector3d.
Serializes as an array of size 3
write() [18/31]
void mc_rtc::MessagePackBuilder::write (const Eigen::Vector6d & v)
Write an Eigen::Vector6d.
Serializes as an array of size 6
write() [19/31]
void mc_rtc::MessagePackBuilder::write (const Eigen::VectorXd & v)
Write an Eigen::VectorXd.
Serializes as an array of size X
write() [20/31]
void mc_rtc::MessagePackBuilder::write (const Eigen::Quaterniond & q)
Write an Eigen::Quaterniond.
Serializes as an array of size X
write() [21/31]
void mc_rtc::MessagePackBuilder::write (const Eigen::Matrix3d & m)
Write an Eigen::Matrix3d.
Serializes as an array of size 9
write() [22/31]
void mc_rtc::MessagePackBuilder::write (const sva::PTransformd & pt)
Write an sva::PTransformd.
Serializes as an array of size 12 (Matrix3d + Vector3d)
write() [23/31]
void mc_rtc::MessagePackBuilder::write (const sva::ForceVecd & fv)
Write an sva::ForceVecd.
Serialized as an array of size 6 (Torque + Force)
write() [24/31]
void mc_rtc::MessagePackBuilder::write (const sva::MotionVecd & mv)
Write an sva::MotionVecd.
Serialized as an array of size 6 (Angular + Linear)
write() [25/31]
void mc_rtc::MessagePackBuilder::write (const mc_rtc::Configuration & config)
Write an mc_rtc::Configuration.
Serialied as the JSON data it holds
write() [26/31]
template<typename T , typename A > void mc_rtc::MessagePackBuilder::write (const std::vector< T, A > & v) inline
Write an std::vector<T, A>
write() [27/31]
template<typename T , std::size_t N> void mc_rtc::MessagePackBuilder::write (const std::array< T, N > & a) inline
Write an std::array<T, N>
write() [28/31]
template<typename T1 , typename T2 > void mc_rtc::MessagePackBuilder::write (const std::pair< T1, T2 > & p) inline
Write an std::pair<T1, T2>
write() [29/31]
template<typename KeyT , typename T , typename C , typename A > void mc_rtc::MessagePackBuilder::write (const std::map< KeyT, T, C, A > & m) inline
Write an std::map<KeyT, T, C, A>
write() [30/31]
template<typename T , typename C , typename A > void mc_rtc::MessagePackBuilder::write (const std::set< T, C, A > & s) inline
Write an std::set<T, C, A>
write() [31/31]
template<typename... Args> void mc_rtc::MessagePackBuilder::write (const std::tuple< Args... > & t) inline
Write an std::tuple<Args...>
write_object()
void mc_rtc::MessagePackBuilder::write_object (const char * data, size_t s)
Write an existing object into the object being constructed.
Parameters
data Data written into the object
size Size of the data
Referenced by mc_rtc::gui::FormImpl< Callback >::addElement(), and mc_rtc::gui::FormImpl< Callback >::write().