mc_rtc::gui::Color Struct Reference
mc_rtc::gui::Color Struct Reference
#include <mc_rtc/gui/types.h>
Public Member Functions
Color ()
Color (double r, double g, double b, double a=1.0)
Color (const mc_rtc::Configuration &config)
bool operator== (const Color &rhs) const
bool operator!= (const Color &rhs) const
void fromMessagePack (const mc_rtc::Configuration &config)
void fromConfig (const mc_rtc::Configuration &config)
mc_rtc::Configuration saveConfig () const
void write (mc_rtc::MessagePackBuilder &builder) const
Static Public Member Functions
static constexpr size_t write_size ()
Public Attributes
double r = 1.0
double g = 0.0
double b = 0.0
double a = 1.0
Static Public Attributes
static const Color White
static const Color Black
static const Color Red
static const Color Green
static const Color Blue
static const Color Cyan
static const Color Magenta
static const Color Yellow
static const Color Gray
static const Color LightGray
static const std::map< std::string, Color > ColorMap
Constructor & Destructor Documentation
Color() [1/3]
mc_rtc::gui::Color::Color () inline
Color() [2/3]
mc_rtc::gui::Color::Color (double r, double g, double b, double a = 1.0) inline
Color() [3/3]
mc_rtc::gui::Color::Color (const mc_rtc::Configuration & config) inline
Member Function Documentation
fromConfig()
void mc_rtc::gui::Color::fromConfig (const mc_rtc::Configuration & config) inline
References mc_rtc::Configuration::at(), mc_rtc::log::error(), and mc_rtc::Configuration::Exception::silence().
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::Color >::load().
fromMessagePack()
void mc_rtc::gui::Color::fromMessagePack (const mc_rtc::Configuration & config) inline
Referenced by mc_rtc::gui::LineConfig::fromMessagePack().
operator!=()
bool mc_rtc::gui::Color::operator!= (const Color & rhs) const inline
operator==()
bool mc_rtc::gui::Color::operator== (const Color & rhs) const inline
References a, b, g, and r.
saveConfig()
mc_rtc::Configuration mc_rtc::gui::Color::saveConfig () const inline
References mc_rtc::Configuration::rootArray().
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::Color >::save().
write()
void mc_rtc::gui::Color::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), and mc_rtc::MessagePackBuilder::write().
Referenced by mc_rtc::gui::plot::impl::Ordinate< GetT >::write(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write(), mc_rtc::gui::PolygonImpl< GetT >::write(), and mc_rtc::gui::LineConfig::write().
write_size()
static constexpr size_t mc_rtc::gui::Color::write_size () inline static
Referenced by mc_rtc::gui::PolygonImpl< GetT >::write_size().
Member Data Documentation
a
double mc_rtc::gui::Color::a = 1.0
Referenced by operator==().
b
double mc_rtc::gui::Color::b = 0.0
Referenced by operator==().
Black
const Color mc_rtc::gui::Color::Black static
Blue
const Color mc_rtc::gui::Color::Blue static
ColorMap
const std::map<std::string, Color> mc_rtc::gui::Color::ColorMap static
Cyan
const Color mc_rtc::gui::Color::Cyan static
g
double mc_rtc::gui::Color::g = 0.0
Referenced by operator==().
Gray
const Color mc_rtc::gui::Color::Gray static
Green
const Color mc_rtc::gui::Color::Green static
LightGray
const Color mc_rtc::gui::Color::LightGray static
Magenta
const Color mc_rtc::gui::Color::Magenta static
r
double mc_rtc::gui::Color::r = 1.0
Referenced by operator==().
Red
const Color mc_rtc::gui::Color::Red static
White
const Color mc_rtc::gui::Color::White static
Yellow
const Color mc_rtc::gui::Color::Yellow static