mc_rtc::gui::PointConfig Struct Reference
mc_rtc::gui::PointConfig Struct Reference
#include <mc_rtc/gui/types.h>
Public Member Functions
PointConfig ()
PointConfig (const Color &color, double scale=0.02)
PointConfig (const mc_rtc::Configuration &config)
void fromMessagePack (const mc_rtc::Configuration &config)
void fromConfig (const mc_rtc::Configuration &config)
mc_rtc::Configuration saveConfig () const
void write (mc_rtc::MessagePackBuilder &out) const
Static Public Member Functions
static constexpr size_t write_size ()
Public Attributes
Color color
double scale = 0.02
Constructor & Destructor Documentation
PointConfig() [1/3]
mc_rtc::gui::PointConfig::PointConfig () inline
PointConfig() [2/3]
mc_rtc::gui::PointConfig::PointConfig (const Color & color, double scale = 0.02) inline
PointConfig() [3/3]
mc_rtc::gui::PointConfig::PointConfig (const mc_rtc::Configuration & config) inline
Member Function Documentation
fromConfig()
void mc_rtc::gui::PointConfig::fromConfig (const mc_rtc::Configuration & config) inline
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::PointConfig >::load().
fromMessagePack()
void mc_rtc::gui::PointConfig::fromMessagePack (const mc_rtc::Configuration & config) inline
saveConfig()
mc_rtc::Configuration mc_rtc::gui::PointConfig::saveConfig () const inline
References mc_rtc::Configuration::add().
Referenced by mc_rtc::ConfigurationLoader< mc_rtc::gui::PointConfig >::save().
write()
void mc_rtc::gui::PointConfig::write (mc_rtc::MessagePackBuilder & out) const inline
References mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::MessagePackBuilder::start_array(), and mc_rtc::MessagePackBuilder::write().
Referenced by mc_rtc::gui::Point3DROImpl< GetT >::write().
write_size()
static constexpr size_t mc_rtc::gui::PointConfig::write_size () inline static
Referenced by mc_rtc::gui::Point3DROImpl< GetT >::write_size(), and mc_rtc::gui::Point3DImpl< GetT, SetT >::write_size().
Member Data Documentation
color
Color mc_rtc::gui::PointConfig::color
scale
double mc_rtc::gui::PointConfig::scale = 0.02