mc_rtc::gui::details::TableImpl< GetHeader, GetData > Struct Template Reference
mc_rtc::gui::details::TableImpl< GetHeader, GetData > Struct Template Reference
Table should display a table of heterogeneous data.
#include <mc_rtc/gui/Table.h>
Public Member Functions
TableImpl (const std::string &name, GetHeader get_header_fn, GetData get_data_fn)
void write (mc_rtc::MessagePackBuilder &builder)
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Table
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetHeader, typename GetData>
struct mc_rtc::gui::details::TableImpl< GetHeader, GetData >
Table should display a table of heterogeneous data.
The user is responsible for making sure the header size and data size match
Template Parameters
GetHeader should return the header information for the table
GetData should return data that can be converted to a JSON array of array (e.g. vector<vector<T>> or vector<tuple<...>>)
Constructor & Destructor Documentation
TableImpl()
template<typename GetHeader, typename GetData> mc_rtc::gui::details::TableImpl< GetHeader, GetData >::TableImpl (const std::string & name, GetHeader get_header_fn, GetData get_data_fn) inline
Member Function Documentation
write()
template<typename GetHeader, typename GetData> void mc_rtc::gui::details::TableImpl< GetHeader, GetData >::write (mc_rtc::MessagePackBuilder & builder) inline
References mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::Element::write().
Referenced by mc_rtc::gui::details::FormattedTableImpl< GetHeader, GetFormat, GetData >::write().
write_size()
template<typename GetHeader, typename GetData> static constexpr size_t mc_rtc::gui::details::TableImpl< GetHeader, GetData >::write_size () inline static
References mc_rtc::gui::Element::write_size().
Referenced by mc_rtc::gui::details::FormattedTableImpl< GetHeader, GetFormat, GetData >::write_size().
Member Data Documentation
type
template<typename GetHeader, typename GetData> constexpr auto mc_rtc::gui::details::TableImpl< GetHeader, GetData >::type = Elements::Table static