mc_rtc::gui::plot::AxisConfiguration Struct Reference
mc_rtc::gui::plot::AxisConfiguration Struct Reference
Describe the configuration of an axis.
#include <mc_rtc/gui/plot/types.h>
Public Member Functions
AxisConfiguration ()=default
AxisConfiguration (const std::string &name)
AxisConfiguration (Range range)
AxisConfiguration (const std::string &name, Range range)
AxisConfiguration & min (double min)
AxisConfiguration & max (double max)
void load (const mc_rtc::Configuration &config)
void write (mc_rtc::MessagePackBuilder &builder) const
Public Attributes
std::string name
Range range
Detailed Description
Describe the configuration of an axis.
Constructor & Destructor Documentation
AxisConfiguration() [1/4]
mc_rtc::gui::plot::AxisConfiguration::AxisConfiguration () default
AxisConfiguration() [2/4]
mc_rtc::gui::plot::AxisConfiguration::AxisConfiguration (const std::string & name) inline
AxisConfiguration() [3/4]
mc_rtc::gui::plot::AxisConfiguration::AxisConfiguration (Range range) inline
AxisConfiguration() [4/4]
mc_rtc::gui::plot::AxisConfiguration::AxisConfiguration (const std::string & name, Range range) inline
Member Function Documentation
load()
void mc_rtc::gui::plot::AxisConfiguration::load (const mc_rtc::Configuration & config) inline
References mc_rtc::gui::plot::Range::load().
max()
AxisConfiguration& mc_rtc::gui::plot::AxisConfiguration::max (double max) inline
References mc_rtc::gui::plot::Range::max.
min()
AxisConfiguration& mc_rtc::gui::plot::AxisConfiguration::min (double min) inline
References mc_rtc::gui::plot::Range::min.
write()
void mc_rtc::gui::plot::AxisConfiguration::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::MessagePackBuilder::finish_array(), MC_RTC_GUI_DLLAPI, mc_rtc::MessagePackBuilder::start_array(), mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::plot::Range::write().
Referenced by mc_rtc::gui::plot::impl::Abscissa< GetT >::write().
Member Data Documentation
name
std::string mc_rtc::gui::plot::AxisConfiguration::name
range
Range mc_rtc::gui::plot::AxisConfiguration::range
Referenced by mc_rtc::gui::plot::impl::Abscissa< GetT >::max(), mc_rtc::gui::plot::impl::Abscissa< GetT >::min(), and mc_rtc::gui::plot::impl::Abscissa< GetT >::range().