mc_rtc::gui::DataElement< GetT > Struct Template Reference
mc_rtc::gui::DataElement< GetT > Struct Template Reference
A generic element to write data to the GUI.
#include <mc_rtc/gui/elements.h>
Public Member Functions
void write (mc_rtc::MessagePackBuilder &builder)
DataElement (const std::string &name, GetT get_fn)
Constructor.
DataElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Protected Attributes
GetT get_fn_
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Detailed Description
template<typename GetT>
struct mc_rtc::gui::DataElement< GetT >
A generic element to write data to the GUI.
This is a common building block for other elements
Constructor & Destructor Documentation
DataElement() [1/2]
template<typename GetT > mc_rtc::gui::DataElement< GetT >::DataElement (const std::string & name, GetT get_fn) inline
Constructor.
DataElement() [2/2]
template<typename GetT > mc_rtc::gui::DataElement< GetT >::DataElement () inline
Invalid element.
Member Function Documentation
write()
template<typename GetT > void mc_rtc::gui::DataElement< GetT >::write (mc_rtc::MessagePackBuilder & builder) inline
References mc_rtc::MessagePackBuilder::write().
Referenced by mc_rtc::gui::DataComboInputImpl< GetT, SetT >::write(), mc_rtc::gui::ComboInputImpl< GetT, SetT >::write(), mc_rtc::gui::NumberSliderImpl< GetT, SetT >::write(), mc_rtc::gui::RotationROImpl< GetT >::write(), mc_rtc::gui::XYThetaROImpl< GetT >::write(), mc_rtc::gui::ArrayLabelImpl< GetT >::write(), mc_rtc::gui::TransformROImpl< GetT >::write(), mc_rtc::gui::ArrayInputImpl< GetT, SetT >::write(), mc_rtc::gui::Point3DROImpl< GetT >::write(), mc_rtc::gui::PolygonImpl< GetT >::write(), mc_rtc::gui::TrajectoryImpl< GetT >::write(), mc_rtc::gui::XYThetaImpl< GetT, SetT >::write(), mc_rtc::gui::RotationImpl< GetT, SetT >::write(), mc_rtc::gui::TransformImpl< GetT, SetT >::write(), and mc_rtc::gui::Point3DImpl< GetT, SetT >::write().
write_size()
template<typename GetT > static constexpr size_t mc_rtc::gui::DataElement< GetT >::write_size () inline static
References mc_rtc::gui::Element::write_size().
Referenced by mc_rtc::gui::DataComboInputImpl< GetT, SetT >::write_size(), mc_rtc::gui::ComboInputImpl< GetT, SetT >::write_size(), mc_rtc::gui::NumberSliderImpl< GetT, SetT >::write_size(), mc_rtc::gui::RotationROImpl< GetT >::write_size(), mc_rtc::gui::XYThetaROImpl< GetT >::write_size(), mc_rtc::gui::ArrayLabelImpl< GetT >::write_size(), mc_rtc::gui::TransformROImpl< GetT >::write_size(), mc_rtc::gui::ArrayInputImpl< GetT, SetT >::write_size(), mc_rtc::gui::Point3DROImpl< GetT >::write_size(), mc_rtc::gui::PolygonImpl< GetT >::write_size(), mc_rtc::gui::TrajectoryImpl< GetT >::write_size(), mc_rtc::gui::XYThetaImpl< GetT, SetT >::write_size(), mc_rtc::gui::RotationImpl< GetT, SetT >::write_size(), mc_rtc::gui::TransformImpl< GetT, SetT >::write_size(), and mc_rtc::gui::Point3DImpl< GetT, SetT >::write_size().
Member Data Documentation
get_fn_
template<typename GetT > GetT mc_rtc::gui::DataElement< GetT >::get_fn_ protected