mc_rtc::gui::Point3DROImpl< GetT > Struct Template Reference
mc_rtc::gui::Point3DROImpl< GetT > Struct Template Reference
Point3D should display a 3D point in the environment.
#include <mc_rtc/gui/Point3D.h>
Public Member Functions
Point3DROImpl (const std::string &name, const PointConfig &config, GetT get_fn)
void write (mc_rtc::MessagePackBuilder &builder)
Point3DROImpl ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
void write (mc_rtc::MessagePackBuilder &builder)
DataElement (const std::string &name, GetT get_fn)
Constructor.
DataElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Point3D
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::DataElement< GetT >
GetT get_fn_
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetT>
struct mc_rtc::gui::Point3DROImpl< GetT >
Point3D should display a 3D point in the environment.
A PointConfig is provided to control how the point should be displayed
With this variant, the point cannot be edited
It will also trigger an ArrayLabel with {"x", "y", "z"} labels
Template Parameters
GetT Should return an Eigen::Vector3d
Constructor & Destructor Documentation
Point3DROImpl() [1/2]
template<typename GetT> mc_rtc::gui::Point3DROImpl< GetT >::Point3DROImpl (const std::string & name, const PointConfig & config, GetT get_fn) inline
Point3DROImpl() [2/2]
template<typename GetT> mc_rtc::gui::Point3DROImpl< GetT >::Point3DROImpl () inline
Invalid element.
Member Function Documentation
write()
template<typename GetT> void mc_rtc::gui::Point3DROImpl< GetT >::write (mc_rtc::MessagePackBuilder & builder) inline
References mc_rtc::MessagePackBuilder::write(), mc_rtc::gui::DataElement< GetT >::write(), and mc_rtc::gui::PointConfig::write().
write_size()
template<typename GetT> static constexpr size_t mc_rtc::gui::Point3DROImpl< GetT >::write_size () inline static
References mc_rtc::gui::DataElement< GetT >::write_size(), and mc_rtc::gui::PointConfig::write_size().
Member Data Documentation
type
template<typename GetT> constexpr auto mc_rtc::gui::Point3DROImpl< GetT >::type = Elements::Point3D static