mc_tasks::SplineTrajectoryTask< Derived > Struct Template Reference
mc_tasks::SplineTrajectoryTask< Derived > Struct Template Reference
Generic CRTP implementation for a task tracking a curve in both position and orientation. This class takes care of much of the logic behind tracking a curve:
#include <mc_tasks/SplineTrajectoryTask.h>
Public Types
using SplineTrajectoryBase = SplineTrajectoryTask< Derived >
using TrajectoryTask = TrajectoryTaskGeneric< tasks::qp::TransformTask >
Public Types inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >
using TrajectoryBase = TrajectoryTaskGeneric< tasks::qp::TransformTask >
Public Member Functions
SplineTrajectoryTask (const mc_rbdyn::Robots &robots, unsigned int robotIndex, const std::string &surfaceName, double duration, double stiffness, double weight, const Eigen::Matrix3d &target, const std::vector< std::pair< double, Eigen::Matrix3d >> &oriWp={})
Constructor.
std::function< bool(const mc_tasks::MetaTask &, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add support for the following entries.
void oriWaypoints (const std::vector< std::pair< double, Eigen::Matrix3d >> &oriWp)
Sets the orientation waypoints.
void dimWeight (const Eigen::VectorXd &dimW) override
Sets the dimensional weights (controls the importance of orientation/translation).
Eigen::VectorXd dimWeight () const override
Gets the dimensional weights (orientation/translation)
bool timeElapsed () const
Whether the trajectory has finished.
Eigen::VectorXd eval () const override
Returns the transformError between current robot surface pose and its final target.
virtual Eigen::VectorXd evalTracking () const
Returns the trajectory tracking error: transformError between the current robot surface pose and its next desired pose along the trajectory error.
void target (const sva::PTransformd &target)
Sets the curve target pose. Translation target will be handled by the Derived curve, while orientation target is interpolated here.
const sva::PTransformd target () const
Gets the target pose (position/orientation)
std::vector< Eigen::Vector3d > controlPoints ()
Get the control points of the trajectory's b-spline.
void displaySamples (unsigned s)
Number of points to sample on the spline for the gui display.
unsigned displaySamples () const
Number of samples for displaying the spline.
void pause (bool paused)
Allows to pause the task.
bool pause () const
double currentTime () const
double duration () const
Returns the trajectory's duration.
Public Member Functions inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >
TrajectoryTaskGeneric (const mc_rbdyn::Robots &robots, unsigned int robotIndex, double stiffness, double weight)
Constructor (auto damping)
virtual ~TrajectoryTaskGeneric ()
virtual void reset () override
Reset task target velocity and acceleration to zero.
void refVel (const Eigen::VectorXd &vel)
Set the trajectory reference velocity.
const Eigen::VectorXd & refVel () const
Get the trajectory reference velocity.
void refAccel (const Eigen::VectorXd &accel)
Set the trajectory reference acceleration.
const Eigen::VectorXd & refAccel () const
Get the trajectory reference acceleration.
void stiffness (double stiffness)
Set the task stiffness/damping.
void stiffness (const Eigen::VectorXd &stiffness)
Set dimensional stiffness.
double stiffness () const
Get the current task stiffness.
void damping (double damping)
Set the task damping, leaving its stiffness unchanged.
void damping (const Eigen::VectorXd &damping)
Set dimensional damping.
double damping () const
Get the current task damping.
void setGains (double stiffness, double damping)
Set both stiffness and damping.
void setGains (const Eigen::VectorXd &stiffness, const Eigen::VectorXd &damping)
Set dimensional stiffness and damping.
const Eigen::VectorXd & dimStiffness () const
Get the current task dimensional stiffness.
const Eigen::VectorXd & dimDamping () const
Get the current task dimensional damping.
void weight (double w)
Set the task weight.
double weight () const
Returns the task weight.
virtual void selectActiveJoints (const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={}, bool checkJoints=true)
Create an active joints selector.
virtual void selectActiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={}) override
Create an active joints selector.
virtual void selectUnactiveJoints (const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={}, bool checkJoints=true)
Create an unactive joints selector.
virtual void selectUnactiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={}) override
Create an unactive joints selector.
virtual void resetJointsSelector ()
virtual void resetJointsSelector (mc_solver::QPSolver &solver) override
Reset active joints selection.
virtual Eigen::VectorXd speed () const override
Returns the task velocity.
const Eigen::VectorXd & normalAcc () const
const Eigen::MatrixXd & jac () const
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::MetaTask
virtual ~MetaTask ()
const std::string & type () const
Get the type of the task.
void name (const std::string &name)
Set a name for the task.
const std::string & name () const
Get the name of the task.
Protected Member Functions
void refPose (const sva::PTransformd &pose)
Tracks a reference world pose.
const sva::PTransformd & refPose () const
Returns the trajectory reference world pose.
void addToGUI (mc_rtc::gui::StateBuilder &gui) override
Add task controls to the GUI. Interactive controls for the trajectory waypoints and end-endpoints automatically updates the curve.
void addToSolver (mc_solver::QPSolver &solver) override
Add the task to a solver.
void addToLogger (mc_rtc::Logger &logger) override
Add information about the task to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
void update (mc_solver::QPSolver &) override
Update trajectory target.
Protected Member Functions inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >
void finalize (Args &&... args)
void addToGUI (mc_rtc::gui::StateBuilder &) override
Add elements to the GUI through the helper.
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add additional completion criterias to mc_control::CompletionCriteria object.
Protected Member Functions inherited from mc_tasks::MetaTask
virtual void removeFromGUI (mc_rtc::gui::StateBuilder &)
Remove elements from the GUI through the helper.
Protected Attributes
unsigned int rIndex_
std::string surfaceName_
double duration_
mc_trajectory::InterpolatedRotation oriSpline_
std::vector< std::pair< double, Eigen::Matrix3d > > oriWp_
bool paused_ = false
double currTime_ = 0.
double timeStep_ = 0
unsigned samples_ = 20
bool inSolver_ = false
Protected Attributes inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >
const mc_rbdyn::Robots & robots
unsigned int rIndex
std::shared_ptr< tasks::qp::TransformTask > errorT
Eigen::VectorXd refVel_
Eigen::VectorXd refAccel_
bool inSolver_
std::shared_ptr< tasks::qp::TrajectoryTask > trajectoryT_
Protected Attributes inherited from mc_tasks::MetaTask
std::string type_
std::string name_
Additional Inherited Members
Static Protected Member Functions inherited from mc_tasks::MetaTask
static void addToSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void removeFromSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void update (MetaTask &t, mc_solver::QPSolver &solver)
static void addToLogger (MetaTask &t, mc_rtc::Logger &logger)
static void removeFromLogger (MetaTask &t, mc_rtc::Logger &logger)
static void addToGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void removeFromGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void ensureHasJoints (const mc_rbdyn::Robot &robot, const std::vector< std::string > &joints, const std::string &prefix)
Detailed Description
template<typename Derived>
struct mc_tasks::SplineTrajectoryTask< Derived >
Generic CRTP implementation for a task tracking a curve in both position and orientation. This class takes care of much of the logic behind tracking a curve:
Interpolates between orientation waypoints defined as pairs [time, orientation]
Provides reference position/velocity/acceleration from underlying curve (defined in the Derived class)
Implements GUI elements for controlling waypoints, targets, etc.
Brings in all the functionalities from TrajectoryTaskGeneric
To implement tracking of a new curve, simply derive from this class and implement the functionalites specific to the curve. You need to at least implement:
spline() accessors
targetPos() accessors/setters The spline itself (as returned by spline()) should at least implement:
update() triggers the curve computation if needed (if waypoints/constraints changed)
target() accessors/setters
splev(t, order) computes the position and its nth-order derivatives at time t along the curve
Member Typedef Documentation
SplineTrajectoryBase
template<typename Derived> using mc_tasks::SplineTrajectoryTask< Derived >::SplineTrajectoryBase = SplineTrajectoryTask<Derived>
TrajectoryTask
template<typename Derived> using mc_tasks::SplineTrajectoryTask< Derived >::TrajectoryTask = TrajectoryTaskGeneric<tasks::qp::TransformTask>
Constructor & Destructor Documentation
SplineTrajectoryTask()
template<typename Derived> mc_tasks::SplineTrajectoryTask< Derived >::SplineTrajectoryTask (const mc_rbdyn::Robots & robots, unsigned int robotIndex, const std::string & surfaceName, double duration, double stiffness, double weight, const Eigen::Matrix3d & target, const std::vector< std::pair< double, Eigen::Matrix3d >> & oriWp = {})
Constructor.
Parameters
robots Robots controlled by the task
robotIndex Which robot is controlled
surfaceName Surface controlled by the task (should belong to the controlled robot)
duration Length of the movement
stiffness Task stiffness (position and orientation)
posW Task weight (position)
oriW Task weight (orientation)
oriWp Optional orientation waypoints (pairs of [time, orientation])
Member Function Documentation
addToGUI()
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::addToGUI (mc_rtc::gui::StateBuilder & gui) override protected virtual
Add task controls to the GUI. Interactive controls for the trajectory waypoints and end-endpoints automatically updates the curve.
Reimplemented from mc_tasks::MetaTask.
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
addToLogger()
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::addToLogger (mc_rtc::Logger & logger) override protected virtual
Add information about the task to the logger.
Parameters
logger
Reimplemented from mc_tasks::MetaTask.
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
addToSolver()
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::addToSolver (mc_solver::QPSolver & solver) override protected virtual
Add the task to a solver.
Parameters
solver Solver where to add the task
Reimplemented from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >.
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
buildCompletionCriteria()
template<typename Derived> std::function<bool(const mc_tasks::MetaTask &, std::string &)> mc_tasks::SplineTrajectoryTask< Derived >::buildCompletionCriteria (double dt, const mc_rtc::Configuration & config) const override virtual
Add support for the following entries.
timeElapsed: True when the task duration has elapsed
wrench: True when the force applied on the robot surface is higher than the provided threshold (6d vector, NaN value ignores the reading, negative values invert the condition). Ignored if the surface has no force-sensor attached.
Exceptions
if the surface does not have an associated force sensor
Reimplemented from mc_tasks::MetaTask.
controlPoints()
template<typename Derived> std::vector<Eigen::Vector3d> mc_tasks::SplineTrajectoryTask< Derived >::controlPoints ()
Get the control points of the trajectory's b-spline.
Returns
The list of control points in the spline
currentTime()
template<typename Derived> double mc_tasks::SplineTrajectoryTask< Derived >::currentTime () const inline
dimWeight() [1/2]
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::dimWeight (const Eigen::VectorXd & dimW) override virtual
Sets the dimensional weights (controls the importance of orientation/translation).
Exceptions
if dimW is not a Vector6d
Parameters
dimW Weights expressed as a Vector6d [wx, wy, wz, tx, ty, tz]
Reimplemented from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >.
dimWeight() [2/2]
template<typename Derived> Eigen::VectorXd mc_tasks::SplineTrajectoryTask< Derived >::dimWeight () const override virtual
Gets the dimensional weights (orientation/translation)
Returns
Dimensional weights expressed as a Vector6d [wx, wy, wz, tx, ty, tz]
Reimplemented from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >.
displaySamples() [1/2]
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::displaySamples (unsigned s)
Number of points to sample on the spline for the gui display.
Parameters
s number of samples
displaySamples() [2/2]
template<typename Derived> unsigned mc_tasks::SplineTrajectoryTask< Derived >::displaySamples () const
Number of samples for displaying the spline.
Returns
number of samples
duration()
template<typename Derived> double mc_tasks::SplineTrajectoryTask< Derived >::duration () const inline
Returns the trajectory's duration.
eval()
template<typename Derived> Eigen::VectorXd mc_tasks::SplineTrajectoryTask< Derived >::eval () const override virtual
Returns the transformError between current robot surface pose and its final target.
Returns
The error w.r.t the final target
Reimplemented from mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >.
evalTracking()
template<typename Derived> virtual Eigen::VectorXd mc_tasks::SplineTrajectoryTask< Derived >::evalTracking () const virtual
Returns the trajectory tracking error: transformError between the current robot surface pose and its next desired pose along the trajectory error.
Returns
The trajectory tracking error
oriWaypoints()
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::oriWaypoints (const std::vector< std::pair< double, Eigen::Matrix3d >> & oriWp)
Sets the orientation waypoints.
Parameters
oriWp Orientation waypoints defined as pairs of [time, orientation]
pause() [1/2]
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::pause (bool paused) inline
Allows to pause the task.
This feature is mainly intended to allow starting the task in paused state to allow adjusting the parameters of the trajectory before its execution. Use with care in other contexts.
Warning
Pausing sets the task's desired velocity and acceleration to zero, which will suddently stop the motion. Unpausing causes the motion to resume at the current speed along the trajectory. Avoid pausing/resuming during high-speed trajectories.
Parameters
paused True to pause the task, False to resume.
pause() [2/2]
template<typename Derived> bool mc_tasks::SplineTrajectoryTask< Derived >::pause () const inline
refPose() [1/2]
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::refPose (const sva::PTransformd & pose) protected
Tracks a reference world pose.
Parameters
pose Desired position (world)
refPose() [2/2]
template<typename Derived> const sva::PTransformd& mc_tasks::SplineTrajectoryTask< Derived >::refPose () const protected
Returns the trajectory reference world pose.
Returns
Desired pose (world)
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
removeFromLogger()
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::removeFromLogger (mc_rtc::Logger &) override protected virtual
Remove entries from the logger.
This will be called by the solver when the task is removed.
The default implementation removes nothing from the log.
Reimplemented from mc_tasks::MetaTask.
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
target() [1/2]
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::target (const sva::PTransformd & target)
Sets the curve target pose. Translation target will be handled by the Derived curve, while orientation target is interpolated here.
Parameters
target Target pose for the curve
target() [2/2]
template<typename Derived> const sva::PTransformd mc_tasks::SplineTrajectoryTask< Derived >::target () const
Gets the target pose (position/orientation)
Returns
target pose
timeElapsed()
template<typename Derived> bool mc_tasks::SplineTrajectoryTask< Derived >::timeElapsed () const
Whether the trajectory has finished.
Returns
True if the trajectory has finished
update()
template<typename Derived> void mc_tasks::SplineTrajectoryTask< Derived >::update (mc_solver::QPSolver &) override protected virtual
Update trajectory target.
Implements mc_tasks::MetaTask.
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
Member Data Documentation
currTime_
template<typename Derived> double mc_tasks::SplineTrajectoryTask< Derived >::currTime_ = 0. protected
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::currentTime().
duration_
template<typename Derived> double mc_tasks::SplineTrajectoryTask< Derived >::duration_ protected
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::duration().
inSolver_
template<typename Derived> bool mc_tasks::SplineTrajectoryTask< Derived >::inSolver_ = false protected
oriSpline_
template<typename Derived> mc_trajectory::InterpolatedRotation mc_tasks::SplineTrajectoryTask< Derived >::oriSpline_ protected
oriWp_
template<typename Derived> std::vector<std::pair<double, Eigen::Matrix3d> > mc_tasks::SplineTrajectoryTask< Derived >::oriWp_ protected
paused_
template<typename Derived> bool mc_tasks::SplineTrajectoryTask< Derived >::paused_ = false protected
Referenced by mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >::pause().
rIndex_
template<typename Derived> unsigned int mc_tasks::SplineTrajectoryTask< Derived >::rIndex_ protected
samples_
template<typename Derived> unsigned mc_tasks::SplineTrajectoryTask< Derived >::samples_ = 20 protected
surfaceName_
template<typename Derived> std::string mc_tasks::SplineTrajectoryTask< Derived >::surfaceName_ protected
timeStep_
template<typename Derived> double mc_tasks::SplineTrajectoryTask< Derived >::timeStep_ = 0 protected