mc_tasks::lipm_stabilizer::StabilizerTask Struct Reference
mc_tasks::lipm_stabilizer::StabilizerTask Struct Reference
Walking stabilization based on linear inverted pendulum tracking.
#include <mc_tasks/lipm_stabilizer/StabilizerTask.h>
Classes
struct EnumClassHash
Workaround a C++11 standard bug: no specialization of the hash functor exists for enum types.
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW StabilizerTask (const mc_rbdyn::Robots &robots, const mc_rbdyn::Robots &realRobots, unsigned int robotIndex, const std::string &leftSurface, const std::string &rightSurface, const std::string &torsoBodyName, double dt)
Creates a stabilizer meta task.
StabilizerTask (const mc_rbdyn::Robots &robots, const mc_rbdyn::Robots &realRobots, unsigned int robotIndex, double dt)
Creates a stabilizer meta task.
void reset () override
Resets the stabilizer tasks and parameters to their default configuration.
Eigen::VectorXd eval () const override
Returns the task error.
Eigen::VectorXd speed () const override
Returns the task velocity.
void enable ()
Enables stabilizer.
void disable ()
Disable all feedback components.
void configure (const StabilizerConfiguration &config)
Configure stabilizer's parameters from a stabilizer's configuration object.
void commitConfig ()
Use the current configuration as the new default.
void load (mc_solver::QPSolver &, const mc_rtc::Configuration &config) override
Load targets and contacts from configuration.
const StabilizerConfiguration & config () const
Get current stabilizer's configuration (including changes from GUI/code)
const StabilizerConfiguration & commitedConfig () const
Get last commited configuration.
void reconfigure ()
Reset stabilizer configuration from last configuration set by configure()
void run ()
Update QP task targets.
void setContacts (const ContactDescriptionVector &contacts)
Configure foot tasks for contact at a given location, and add contacts to the solver.
void setContacts (const std::vector< std::pair< ContactState, sva::PTransformd >> &contacts)
Helper to set contacts with a provided target pose.
void setContacts (const std::vector< ContactState > &contacts)
Helper to set contacts from the current surface pose.
const sva::PTransformd & contactAnklePose (ContactState s) const
Projected pose of the ankle frame in the contact frame.
const std::string & footSurface (ContactState s) const
double leftFootRatio () const
Interpolation paremeter between left and right foot.
sva::PTransformd anchorFrame (const mc_rbdyn::Robot &robot) const
computes the anchorFrame compatible with the state observers (e.g KinematicInertial)
void staticTarget (const Eigen::Vector3d &com, double zmpHeight=0)
Provides a static target to the stabilizer.
void target (const Eigen::Vector3d &com, const Eigen::Vector3d &comd, const Eigen::Vector3d &comdd, const Eigen::Vector3d &zmp)
Provides a dynamic target to the stabilizer.
const Eigen::Vector3d & measuredDCM ()
const Eigen::Vector3d & measuredZMP ()
const Eigen::Vector3d & measuredCoM ()
const Eigen::Vector3d & measuredCoMd ()
bool inContact (ContactState state) const
bool inDoubleSupport () const
const mc_rbdyn::Robot & robot () const
const mc_rbdyn::Robot & realRobot () const
Public Member Functions inherited from mc_tasks::MetaTask
virtual ~MetaTask ()
const std::string & type () const
Get the type of the task.
void name (const std::string &name)
Set a name for the task.
const std::string & name () const
Get the name of the task.
Setters to reconfigure the stabilizer online
Setters for the main parameters of the stabilizer.
For safety purposes, values are clamped against the maximum values defined by the stabilizer configuration.
See also
StabilizerConfiguration for details on each of these parameters.
config() Access the current stabilizer configuration values
commitConfig() Make the current configuration the new default
std::unordered_map< ContactState, internal::Contact, EnumClassHash, std::equal_to< ContactState >, Eigen::aligned_allocator< std::pair< const ContactState, internal::Contact > > > contacts_
std::vector< ContactState > addContacts_
Contacts to add to the QPSolver when the task is inserted.
std::unordered_map< ContactState, std::shared_ptr< mc_tasks::force::CoPTask >, EnumClassHash > footTasks
std::vector< std::shared_ptr< mc_tasks::force::CoPTask > > contactTasks
std::vector< std::string > contactSensors
Foot tasks for the established contacts.
std::vector< std::vector< Eigen::Vector3d > > supportPolygons_
Force sensors corresponding to established contacts.
Eigen::Vector2d supportMin_ = Eigen::Vector2d::Zero()
Eigen::Vector2d supportMax_ = Eigen::Vector2d::Zero()
std::shared_ptr< mc_tasks::CoMTask > comTask
std::shared_ptr< mc_tasks::OrientationTask > pelvisTask
Pelvis orientation task.
std::shared_ptr< mc_tasks::OrientationTask > torsoTask
Torso orientation task.
const mc_rbdyn::Robots & robots_
const mc_rbdyn::Robots & realRobots_
unsigned int robotIndex_
Eigen::Vector3d comTarget_ = Eigen::Vector3d::Zero()
Stabilizer targets.
Eigen::Vector3d comdTarget_ = Eigen::Vector3d::Zero()
Eigen::Vector3d comddTarget_ = Eigen::Vector3d::Zero()
Eigen::Vector3d zmpTarget_ = Eigen::Vector3d::Zero()
Eigen::Vector3d dcmTarget_ = Eigen::Vector3d::Zero()
double omega_
double t_ = 0.
Time elapsed since the task is running.
StabilizerConfiguration defaultConfig_
< Default (user-provided) configuration for the stabilizer.
StabilizerConfiguration lastConfig_
Online stabilizer configuration, can be set from the GUI.
StabilizerConfiguration c_
Whether the stabilizer needs to be reconfigured at the next update(solver) call.
bool reconfigure_ = true
bool enabled_ = true
Eigen::QuadProgDense qpSolver_
Whether the stabilizer is enabled.
Eigen::Vector3d dcmAverageError_ = Eigen::Vector3d::Zero()
Eigen::Vector3d dcmError_ = Eigen::Vector3d::Zero()
Eigen::Vector3d dcmVelError_ = Eigen::Vector3d::Zero()
Eigen::Vector3d measuredCoM_ = Eigen::Vector3d::Zero()
Eigen::Vector3d measuredCoMd_ = Eigen::Vector3d::Zero()
Eigen::Vector3d measuredZMP_ = Eigen::Vector3d::Zero()
Eigen::Vector3d measuredDCM_ = Eigen::Vector3d::Zero()
sva::ForceVecd measuredNetWrench_ = sva::ForceVecd::Zero()
bool zmpccOnlyDS_ = true
Only apply ZMPCC in double support.
ZMPCC zmpcc_
Compute CoM offset due to ZMPCC compensation.
mc_filter::ExponentialMovingAverage< Eigen::Vector3d > dcmIntegrator_
mc_filter::StationaryOffset< Eigen::Vector3d > dcmDerivator_
bool inTheAir_ = false
Is the robot in the air?
double dfzForceError_ = 0.
Force error in foot force difference control.
double dfzHeightError_ = 0.
Height error in foot force difference control.
double dt_ = 0.005
Controller cycle in [s].
double leftFootRatio_ = 0.5
Weight distribution ratio (0: all weight on right foot, 1: all on left foot)
double mass_ = 38.
Robot mass in [kg].
double runTime_ = 0.
double vdcHeightError_ = 0.
Average height error used in vertical drift compensation.
sva::ForceVecd distribWrench_ = sva::ForceVecd::Zero()
Result of the force distribution QP.
sva::PTransformd zmpFrame_ = sva::PTransformd::Identity()
Frame in which the ZMP is computed.
void torsoPitch (double pitch)
void torsoWeight (double weight)
void torsoStiffness (double stiffness)
void pelvisWeight (double weight)
void pelvisStiffness (double stiffness)
void dcmGains (double p, double i, double d)
void dcmIntegratorTimeConstant (double dcmIntegratorTimeConstant)
void dcmDerivatorTimeConstant (double dcmDerivatorTimeConstant)
void comWeight (double weight)
void comStiffness (const Eigen::Vector3d &stiffness)
void contactWeight (double weight)
void contactStiffness (const sva::MotionVecd &stiffness)
void contactDamping (const sva::MotionVecd &damping)
void copAdmittance (const Eigen::Vector2d &copAdmittance)
void copMaxVel (const sva::MotionVecd &copMaxVel)
void vdcFrequency (double freq)
void vdcStiffness (double stiffness)
void dfzAdmittance (double dfzAdmittance)
void dfzDamping (double dfzDamping)
void fdqpWeights (const FDQPWeights &fdqp)
void safetyThresholds (const SafetyThresholds &thresholds)
Changes the safety thresholds.
void addToSolver (mc_solver::QPSolver &solver) override
Add the task to a solver.
void removeFromSolver (mc_solver::QPSolver &solver) override
Remove the task from a solver.
void removeFromGUI (mc_rtc::gui::StateBuilder &) override
Remove elements from the GUI through the helper.
void update (mc_solver::QPSolver &) override
Update the task.
void addToLogger (mc_rtc::Logger &) override
Log stabilizer entries.
void removeFromLogger (mc_rtc::Logger &) override
Remove entries from the logger.
void addToGUI (mc_rtc::gui::StateBuilder &) override
Add elements to the GUI through the helper.
void configure_ (mc_solver::QPSolver &solver)
Actual configuration of the stabilizer.
void checkConfiguration (const StabilizerConfiguration &config)
Ensures that the configuration is valid.
Additional Inherited Members
Protected Member Functions inherited from mc_tasks::MetaTask
virtual std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const
Add additional completion criterias to mc_control::CompletionCriteria object.
Static Protected Member Functions inherited from mc_tasks::MetaTask
static void addToSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void removeFromSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void update (MetaTask &t, mc_solver::QPSolver &solver)
static void addToLogger (MetaTask &t, mc_rtc::Logger &logger)
static void removeFromLogger (MetaTask &t, mc_rtc::Logger &logger)
static void addToGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void removeFromGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void ensureHasJoints (const mc_rbdyn::Robot &robot, const std::vector< std::string > &joints, const std::string &prefix)
Protected Attributes inherited from mc_tasks::MetaTask
std::string type_
std::string name_
Detailed Description
Walking stabilization based on linear inverted pendulum tracking.
Stabilization bridges the gap between the open-loop behavior of the pendulum state reference (feedforward controls) and feedback read from state estimation. In our case, feedback is done on the DCM of the LIPM:
\[ \dot{\xi} = \dot{\xi}^{d} + k_p (\xi^d - \xi) + k_i \int (\xi^d - \xi) \]
Which boils down into corresponding formulas for the CoP and CoM acceleration targets.
Constructor & Destructor Documentation
StabilizerTask() [1/2]
EIGEN_MAKE_ALIGNED_OPERATOR_NEW mc_tasks::lipm_stabilizer::StabilizerTask::StabilizerTask (const mc_rbdyn::Robots & robots, const mc_rbdyn::Robots & realRobots, unsigned int robotIndex, const std::string & leftSurface, const std::string & rightSurface, const std::string & torsoBodyName, double dt)
Creates a stabilizer meta task.
Parameters
robots Robots on which the task acts
realRobots Corresponding real robot instances
robotIndex Index of the robot to stabilize
leftSurface Left foot surface name. Its origin should be the center of the foot sole
rightSurface Left foot surface name. Its origin should be the center of the foot sole
torsoBodyName Body name of the robot's torso (i.e a link above the floating base)
dt Controller's timestep
StabilizerTask() [2/2]
mc_tasks::lipm_stabilizer::StabilizerTask::StabilizerTask (const mc_rbdyn::Robots & robots, const mc_rbdyn::Robots & realRobots, unsigned int robotIndex, double dt)
Creates a stabilizer meta task.
This constructor uses the stabilizer configuration in the robot module associated to the controlled robot. The stabilizer is started with two feet contacts.
Parameters
robots Robots on which the task acts
realRobots Corresponding real robots instance
robotIndex Index of the robot
dt Controller's timestep
Member Function Documentation
addToGUI()
void mc_tasks::lipm_stabilizer::StabilizerTask::addToGUI (mc_rtc::gui::StateBuilder &) override protected virtual
Add elements to the GUI through the helper.
This will be called by the solver when the task is added.
The default implementation adds the type of the task under the {"Tasks", name_} category.
Reimplemented from mc_tasks::MetaTask.
addToLogger()
void mc_tasks::lipm_stabilizer::StabilizerTask::addToLogger (mc_rtc::Logger &) override protected virtual
Log stabilizer entries.
Parameters
logger Logger.
Reimplemented from mc_tasks::MetaTask.
addToSolver()
void mc_tasks::lipm_stabilizer::StabilizerTask::addToSolver (mc_solver::QPSolver & solver) override protected virtual
Add the task to a solver.
Parameters
solver Solver where to add the task
Implements mc_tasks::MetaTask.
anchorFrame()
sva::PTransformd mc_tasks::lipm_stabilizer::StabilizerTask::anchorFrame (const mc_rbdyn::Robot & robot) const
computes the anchorFrame compatible with the state observers (e.g KinematicInertial)
Parameters
robot Robot from which the frame will be computed
Returns
Anchor frame in-between the feet according to leftFootRatio()
checkConfiguration()
void mc_tasks::lipm_stabilizer::StabilizerTask::checkConfiguration (const StabilizerConfiguration & config) protected
Ensures that the configuration is valid.
commitConfig()
void mc_tasks::lipm_stabilizer::StabilizerTask::commitConfig ()
Use the current configuration as the new default.
commitedConfig()
const StabilizerConfiguration& mc_tasks::lipm_stabilizer::StabilizerTask::commitedConfig () const
Get last commited configuration.
Commited configuration is corresponds to the latest one set by calling commitConfig(), either manually or from the GUI.
See also
config()
comStiffness()
void mc_tasks::lipm_stabilizer::StabilizerTask::comStiffness (const Eigen::Vector3d & stiffness) inline
comWeight()
void mc_tasks::lipm_stabilizer::StabilizerTask::comWeight (double weight) inline
config()
const StabilizerConfiguration& mc_tasks::lipm_stabilizer::StabilizerTask::config () const
Get current stabilizer's configuration (including changes from GUI/code)
See also
commitedConfig()
configure()
void mc_tasks::lipm_stabilizer::StabilizerTask::configure (const StabilizerConfiguration & config)
Configure stabilizer's parameters from a stabilizer's configuration object.
Parameters
config Stabilizer configuration. Default values can be found in the RobotModule, and modified from YAML configuration or manually.
See also
load(mc_solver::QPSolver &, const mc_rtc::Configuration &) to set stabilizer targets and contacts from configuration
configure_()
void mc_tasks::lipm_stabilizer::StabilizerTask::configure_ (mc_solver::QPSolver & solver) protected
Actual configuration of the stabilizer.
Called when reconfigure_ is true
Parameters
solver Solver to which this task has been added
contactAnklePose()
const sva::PTransformd& mc_tasks::lipm_stabilizer::StabilizerTask::contactAnklePose (ContactState s) const inline
Projected pose of the ankle frame in the contact frame.
Parameters
s Contact for which the frame is requested
Returns
The projected ankle frame expressed in world frame.
contactDamping()
void mc_tasks::lipm_stabilizer::StabilizerTask::contactDamping (const sva::MotionVecd & damping) inline
contactStiffness()
void mc_tasks::lipm_stabilizer::StabilizerTask::contactStiffness (const sva::MotionVecd & stiffness) inline
contactWeight()
void mc_tasks::lipm_stabilizer::StabilizerTask::contactWeight (double weight) inline
copAdmittance()
void mc_tasks::lipm_stabilizer::StabilizerTask::copAdmittance (const Eigen::Vector2d & copAdmittance) inline
References mc_filter::utils::clamp().
copMaxVel()
void mc_tasks::lipm_stabilizer::StabilizerTask::copMaxVel (const sva::MotionVecd & copMaxVel) inline
dcmDerivatorTimeConstant()
void mc_tasks::lipm_stabilizer::StabilizerTask::dcmDerivatorTimeConstant (double dcmDerivatorTimeConstant) inline
dcmGains()
void mc_tasks::lipm_stabilizer::StabilizerTask::dcmGains (double p, double i, double d) inline
References mc_filter::utils::clamp().
dcmIntegratorTimeConstant()
void mc_tasks::lipm_stabilizer::StabilizerTask::dcmIntegratorTimeConstant (double dcmIntegratorTimeConstant) inline
dfzAdmittance()
void mc_tasks::lipm_stabilizer::StabilizerTask::dfzAdmittance (double dfzAdmittance) inline
References mc_filter::utils::clamp().
dfzDamping()
void mc_tasks::lipm_stabilizer::StabilizerTask::dfzDamping (double dfzDamping) inline
References mc_filter::utils::clamp().
disable()
void mc_tasks::lipm_stabilizer::StabilizerTask::disable ()
Disable all feedback components.
enable()
void mc_tasks::lipm_stabilizer::StabilizerTask::enable ()
Enables stabilizer.
This will reinitialize all integrators, and set the stabilizer gains according to the last call to configure()
eval()
Eigen::VectorXd mc_tasks::lipm_stabilizer::StabilizerTask::eval () const override virtual
Returns the task error.
Since the StabilizerTask is a MetaTask, the vector is a concatenation of each sub-tasks. The vector's dimensions depend on the underlying task, and the sub-tasks evaluation depends on their order of insertion.
Implements mc_tasks::MetaTask.
fdqpWeights()
void mc_tasks::lipm_stabilizer::StabilizerTask::fdqpWeights (const FDQPWeights & fdqp) inline
footSurface()
const std::string& mc_tasks::lipm_stabilizer::StabilizerTask::footSurface (ContactState s) const inline
inContact()
bool mc_tasks::lipm_stabilizer::StabilizerTask::inContact (ContactState state) const inline
inDoubleSupport()
bool mc_tasks::lipm_stabilizer::StabilizerTask::inDoubleSupport () const inline
leftFootRatio()
double mc_tasks::lipm_stabilizer::StabilizerTask::leftFootRatio () const inline
Interpolation paremeter between left and right foot.
Returns
Left foot ratio between [0,1]
References mc_rbdyn::zmp().
load()
void mc_tasks::lipm_stabilizer::StabilizerTask::load (mc_solver::QPSolver & , const mc_rtc::Configuration & config) override virtual
Load targets and contacts from configuration.
Reimplemented from mc_tasks::MetaTask.
measuredCoM()
const Eigen::Vector3d& mc_tasks::lipm_stabilizer::StabilizerTask::measuredCoM () inline
measuredCoMd()
const Eigen::Vector3d& mc_tasks::lipm_stabilizer::StabilizerTask::measuredCoMd () inline
measuredDCM()
const Eigen::Vector3d& mc_tasks::lipm_stabilizer::StabilizerTask::measuredDCM () inline
measuredZMP()
const Eigen::Vector3d& mc_tasks::lipm_stabilizer::StabilizerTask::measuredZMP () inline
pelvisStiffness()
void mc_tasks::lipm_stabilizer::StabilizerTask::pelvisStiffness (double stiffness) inline
pelvisWeight()
void mc_tasks::lipm_stabilizer::StabilizerTask::pelvisWeight (double weight) inline
realRobot()
const mc_rbdyn::Robot& mc_tasks::lipm_stabilizer::StabilizerTask::realRobot () const inline
reconfigure()
void mc_tasks::lipm_stabilizer::StabilizerTask::reconfigure ()
Reset stabilizer configuration from last configuration set by configure()
Does not include changes made from the GUI.
removeFromGUI()
void mc_tasks::lipm_stabilizer::StabilizerTask::removeFromGUI (mc_rtc::gui::StateBuilder &) override protected virtual
Remove elements from the GUI through the helper.
This will be called by the solver when the task is removed.
The default implementation removes the {"Tasks", name_} category.
Reimplemented from mc_tasks::MetaTask.
removeFromLogger()
void mc_tasks::lipm_stabilizer::StabilizerTask::removeFromLogger (mc_rtc::Logger &) override protected virtual
Remove entries from the logger.
This will be called by the solver when the task is removed.
The default implementation removes nothing from the log.
Reimplemented from mc_tasks::MetaTask.
removeFromSolver()
void mc_tasks::lipm_stabilizer::StabilizerTask::removeFromSolver (mc_solver::QPSolver & solver) override protected virtual
Remove the task from a solver.
Parameters
solver Solver from which to remove the task
Implements mc_tasks::MetaTask.
reset()
void mc_tasks::lipm_stabilizer::StabilizerTask::reset () override virtual
Resets the stabilizer tasks and parameters to their default configuration.
Resets all tasks and errors/integrator/derivators to their initial configuration. Configures the default stabilizer parameters from the robot module.
You can configure the stabilizer parameters (DCM tacking gains, task gains, etc) by calling configure(const StabilizerConfiguration & config)
Note
If you wish to reset the stabilizer from it's current configuration, you can do so by storing its current configuration as accessed by config() or commitedConfig() and set it explitely after calling reset by calling configure(const StabilizerConfiguration &);
Implements mc_tasks::MetaTask.
robot()
const mc_rbdyn::Robot& mc_tasks::lipm_stabilizer::StabilizerTask::robot () const inline
run()
void mc_tasks::lipm_stabilizer::StabilizerTask::run ()
Update QP task targets.
This function is called once the reference has been updated.
safetyThresholds()
void mc_tasks::lipm_stabilizer::StabilizerTask::safetyThresholds (const SafetyThresholds & thresholds) inline
Changes the safety thresholds.
This ensures that all the parameters depending on these safety parameters are within the new thresholds. If they are out of bounds, they will be clamped back to the new range, and a warning message will be displayed.
Parameters
thresholds New safety thresholds
setContacts() [1/3]
void mc_tasks::lipm_stabilizer::StabilizerTask::setContacts (const ContactDescriptionVector & contacts)
Configure foot tasks for contact at a given location, and add contacts to the solver.
Note
To use the stabilizer with dynamics constraint, you need to add the corresponding mc_rbdyn::Contact to the solver and free the roll/pitch rotation and z translation (in contact frame). This assumes the foot surfaces to have x pointing towards the front of the foot, and z from the ground up.
Parameters
solver The QP solver to which the contact tasks will be added. Note that this method will not add contact constraints to the QPSolver. If you wish to do so, bear in mind that for the stabilizer to work properly, the contact's dofs along the x and y rotations and z translation need to be free.
setContacts() [2/3]
void mc_tasks::lipm_stabilizer::StabilizerTask::setContacts (const std::vector< std::pair< ContactState, sva::PTransformd >> & contacts)
Helper to set contacts with a provided target pose.
Parameters
contacts vectors of contacts defined by their ContactState and a desired pose
setContacts() [3/3]
void mc_tasks::lipm_stabilizer::StabilizerTask::setContacts (const std::vector< ContactState > & contacts)
Helper to set contacts from the current surface pose.
Parameters
contacts Contacts to add. Their pose will be determined set from the realRobot estimate of the foot surface pose. Use with caution.
See also
void setContacts(mc_solver::QPSolver &, const std::vector<std::pair<ContactState, sva::PTransformd>> &);
speed()
Eigen::VectorXd mc_tasks::lipm_stabilizer::StabilizerTask::speed () const override virtual
Returns the task velocity.
Since the StabilizerTask is a MetaTask, the vector is a concatenation of each sub-tasks. The vector's dimensions depend on the underlying task, and the sub-tasks evaluation depends on their order of insertion.
Implements mc_tasks::MetaTask.
staticTarget()
void mc_tasks::lipm_stabilizer::StabilizerTask::staticTarget (const Eigen::Vector3d & com, double zmpHeight = 0)
Provides a static target to the stabilizer.
CoM target : user-provided
CoM velocity target: zero (static)
CoM acceleration target: zero (static)
ZMP: computed under the CoM
Parameters
com desired com position
zmpHeight[=0] optional height of the ZMP plane (eg contacts), used to compute the pendulums omega.
See also
target for dynamic motions.
target()
void mc_tasks::lipm_stabilizer::StabilizerTask::target (const Eigen::Vector3d & com, const Eigen::Vector3d & comd, const Eigen::Vector3d & comdd, const Eigen::Vector3d & zmp)
Provides a dynamic target to the stabilizer.
Note that this target should be updated at each iteration and provide a dynamically-consistent trajectory. This would typically be generated by a compatible Model Preview Controller.
See https://github.com/jrl-umi3218/lipm_walking_controller for example in the context of walking.
Parameters
com Desired CoM position
comd Desired CoM velocity
comdd Desired CoM acceleration
zmp Desired ZMP
See also
staticTarget for a helper to define the stabilizer target when the CoM is static
torsoPitch()
void mc_tasks::lipm_stabilizer::StabilizerTask::torsoPitch (double pitch) inline
torsoStiffness()
void mc_tasks::lipm_stabilizer::StabilizerTask::torsoStiffness (double stiffness) inline
torsoWeight()
void mc_tasks::lipm_stabilizer::StabilizerTask::torsoWeight (double weight) inline
update()
void mc_tasks::lipm_stabilizer::StabilizerTask::update (mc_solver::QPSolver & solver) override protected virtual
Update the task.
This function (usually) has to be called at every iteration of the solver once it has been added. It should update the state of the task.
Parameters
solver Solver in which the task is inserted
Implements mc_tasks::MetaTask.
vdcFrequency()
void mc_tasks::lipm_stabilizer::StabilizerTask::vdcFrequency (double freq) inline
References mc_filter::utils::clamp().
vdcStiffness()
void mc_tasks::lipm_stabilizer::StabilizerTask::vdcStiffness (double stiffness) inline
References mc_filter::utils::clamp().
Member Data Documentation
addContacts_
std::vector<ContactState> mc_tasks::lipm_stabilizer::StabilizerTask::addContacts_ protected
Contacts to add to the QPSolver when the task is inserted.
c_
StabilizerConfiguration mc_tasks::lipm_stabilizer::StabilizerTask::c_ protected
Whether the stabilizer needs to be reconfigured at the next update(solver) call.
comddTarget_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::comddTarget_ = Eigen::Vector3d::Zero() protected
comdTarget_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::comdTarget_ = Eigen::Vector3d::Zero() protected
comTarget_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::comTarget_ = Eigen::Vector3d::Zero() protected
Stabilizer targets.
comTask
std::shared_ptr<mc_tasks::CoMTask> mc_tasks::lipm_stabilizer::StabilizerTask::comTask protected
contacts_
std::unordered_map<ContactState, internal::Contact, EnumClassHash, std::equal_to<ContactState>, Eigen::aligned_allocator<std::pair<const ContactState, internal::Contact> > > mc_tasks::lipm_stabilizer::StabilizerTask::contacts_ protected
contactSensors
std::vector<std::string> mc_tasks::lipm_stabilizer::StabilizerTask::contactSensors protected
Foot tasks for the established contacts.
contactTasks
std::vector<std::shared_ptr<mc_tasks::force::CoPTask> > mc_tasks::lipm_stabilizer::StabilizerTask::contactTasks protected
dcmAverageError_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::dcmAverageError_ = Eigen::Vector3d::Zero() protected
dcmDerivator_
mc_filter::StationaryOffset<Eigen::Vector3d> mc_tasks::lipm_stabilizer::StabilizerTask::dcmDerivator_ protected
dcmError_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::dcmError_ = Eigen::Vector3d::Zero() protected
dcmIntegrator_
mc_filter::ExponentialMovingAverage<Eigen::Vector3d> mc_tasks::lipm_stabilizer::StabilizerTask::dcmIntegrator_ protected
dcmTarget_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::dcmTarget_ = Eigen::Vector3d::Zero() protected
dcmVelError_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::dcmVelError_ = Eigen::Vector3d::Zero() protected
defaultConfig_
StabilizerConfiguration mc_tasks::lipm_stabilizer::StabilizerTask::defaultConfig_ protected
< Default (user-provided) configuration for the stabilizer.
This configuration is superseeded by the parameters set in the GUI Last valid stabilizer configuration.
dfzForceError_
double mc_tasks::lipm_stabilizer::StabilizerTask::dfzForceError_ = 0. protected
Force error in foot force difference control.
dfzHeightError_
double mc_tasks::lipm_stabilizer::StabilizerTask::dfzHeightError_ = 0. protected
Height error in foot force difference control.
distribWrench_
sva::ForceVecd mc_tasks::lipm_stabilizer::StabilizerTask::distribWrench_ = sva::ForceVecd::Zero() protected
Result of the force distribution QP.
dt_
double mc_tasks::lipm_stabilizer::StabilizerTask::dt_ = 0.005 protected
Controller cycle in [s].
enabled_
bool mc_tasks::lipm_stabilizer::StabilizerTask::enabled_ = true protected
footTasks
std::unordered_map<ContactState, std::shared_ptr<mc_tasks::force::CoPTask>, EnumClassHash> mc_tasks::lipm_stabilizer::StabilizerTask::footTasks protected
inTheAir_
bool mc_tasks::lipm_stabilizer::StabilizerTask::inTheAir_ = false protected
Is the robot in the air?
lastConfig_
StabilizerConfiguration mc_tasks::lipm_stabilizer::StabilizerTask::lastConfig_ protected
Online stabilizer configuration, can be set from the GUI.
Defaults to defaultConfig_
leftFootRatio_
double mc_tasks::lipm_stabilizer::StabilizerTask::leftFootRatio_ = 0.5 protected
Weight distribution ratio (0: all weight on right foot, 1: all on left foot)
mass_
double mc_tasks::lipm_stabilizer::StabilizerTask::mass_ = 38. protected
Robot mass in [kg].
measuredCoM_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::measuredCoM_ = Eigen::Vector3d::Zero() protected
measuredCoMd_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::measuredCoMd_ = Eigen::Vector3d::Zero() protected
measuredDCM_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::measuredDCM_ = Eigen::Vector3d::Zero() protected
measuredNetWrench_
sva::ForceVecd mc_tasks::lipm_stabilizer::StabilizerTask::measuredNetWrench_ = sva::ForceVecd::Zero() protected
measuredZMP_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::measuredZMP_ = Eigen::Vector3d::Zero() protected
omega_
double mc_tasks::lipm_stabilizer::StabilizerTask::omega_ protected
pelvisTask
std::shared_ptr<mc_tasks::OrientationTask> mc_tasks::lipm_stabilizer::StabilizerTask::pelvisTask protected
Pelvis orientation task.
qpSolver_
Eigen::QuadProgDense mc_tasks::lipm_stabilizer::StabilizerTask::qpSolver_ protected
Whether the stabilizer is enabled.
Least-squares solver for wrench distribution
realRobots_
const mc_rbdyn::Robots& mc_tasks::lipm_stabilizer::StabilizerTask::realRobots_ protected
reconfigure_
bool mc_tasks::lipm_stabilizer::StabilizerTask::reconfigure_ = true protected
robotIndex_
unsigned int mc_tasks::lipm_stabilizer::StabilizerTask::robotIndex_ protected
robots_
const mc_rbdyn::Robots& mc_tasks::lipm_stabilizer::StabilizerTask::robots_ protected
runTime_
double mc_tasks::lipm_stabilizer::StabilizerTask::runTime_ = 0. protected
supportMax_
Eigen::Vector2d mc_tasks::lipm_stabilizer::StabilizerTask::supportMax_ = Eigen::Vector2d::Zero() protected
supportMin_
Eigen::Vector2d mc_tasks::lipm_stabilizer::StabilizerTask::supportMin_ = Eigen::Vector2d::Zero() protected
supportPolygons_
std::vector<std::vector<Eigen::Vector3d> > mc_tasks::lipm_stabilizer::StabilizerTask::supportPolygons_ protected
Force sensors corresponding to established contacts.
For GUI display
t_
double mc_tasks::lipm_stabilizer::StabilizerTask::t_ = 0. protected
Time elapsed since the task is running.
torsoTask
std::shared_ptr<mc_tasks::OrientationTask> mc_tasks::lipm_stabilizer::StabilizerTask::torsoTask protected
Torso orientation task.
vdcHeightError_
double mc_tasks::lipm_stabilizer::StabilizerTask::vdcHeightError_ = 0. protected
Average height error used in vertical drift compensation.
zmpcc_
ZMPCC mc_tasks::lipm_stabilizer::StabilizerTask::zmpcc_ protected
Compute CoM offset due to ZMPCC compensation.
zmpccOnlyDS_
bool mc_tasks::lipm_stabilizer::StabilizerTask::zmpccOnlyDS_ = true protected
Only apply ZMPCC in double support.
zmpFrame_
sva::PTransformd mc_tasks::lipm_stabilizer::StabilizerTask::zmpFrame_ = sva::PTransformd::Identity() protected
Frame in which the ZMP is computed.
zmpTarget_
Eigen::Vector3d mc_tasks::lipm_stabilizer::StabilizerTask::zmpTarget_ = Eigen::Vector3d::Zero() protected