mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT > Struct Template Reference
mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT > Struct Template Reference
For a given plot, this holds options on the ordinate plot and a callback that returns the current value.
#include <mc_rtc/gui/plot/AbscissaOrdinate.h>
Public Member Functions
AbscissaOrdinate (const std::string &name, GetXT get_x_fn, GetYT get_y_fn, Color color, Style style, Side side)
void write (mc_rtc::MessagePackBuilder &builder) const
AbscissaOrdinate & style (Style style)
AbscissaOrdinate & side (Side side)
Static Public Attributes
static constexpr Type type = Type::AbscissaOrdinate
Protected Attributes
std::string name_
GetXT get_x_fn_
GetYT get_y_fn_
Color color_
Style style_
Side side_
Detailed Description
template<typename GetXT, typename GetYT>
struct mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >
For a given plot, this holds options on the ordinate plot and a callback that returns the current value.
Constructor & Destructor Documentation
AbscissaOrdinate()
template<typename GetXT, typename GetYT> mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::AbscissaOrdinate (const std::string & name, GetXT get_x_fn, GetYT get_y_fn, Color color, Style style, Side side) inline
Member Function Documentation
side()
template<typename GetXT, typename GetYT> AbscissaOrdinate& mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side (Side side) inline
References mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side_.
Referenced by mc_rtc::gui::plot::XY().
style()
template<typename GetXT, typename GetYT> AbscissaOrdinate& mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style (Style style) inline
References mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style_.
Referenced by mc_rtc::gui::plot::XY().
write()
template<typename GetXT, typename GetYT> void mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::color_, mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::get_x_fn_, mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::get_y_fn_, mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::name_, mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side_, mc_rtc::MessagePackBuilder::start_array(), mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style_, mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::Color::write().
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinateWithColor< GetXT, GetYT, GetColor >::write().
Member Data Documentation
color_
template<typename GetXT, typename GetYT> Color mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::color_ mutable protected
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write(), and mc_rtc::gui::plot::impl::AbscissaOrdinateWithColor< GetXT, GetYT, GetColor >::write().
get_x_fn_
template<typename GetXT, typename GetYT> GetXT mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::get_x_fn_ protected
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write().
get_y_fn_
template<typename GetXT, typename GetYT> GetYT mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::get_y_fn_ protected
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write().
name_
template<typename GetXT, typename GetYT> std::string mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::name_ protected
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write().
side_
template<typename GetXT, typename GetYT> Side mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side_ protected
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::side(), and mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write().
style_
template<typename GetXT, typename GetYT> Style mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style_ protected
Referenced by mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::style(), and mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::write().
type
template<typename GetXT, typename GetYT> constexpr Type mc_rtc::gui::plot::impl::AbscissaOrdinate< GetXT, GetYT >::type = Type::AbscissaOrdinate static