mc_rtc::gui::Element Struct Reference
mc_rtc::gui::Element Struct Reference
Element is the common class for every element's type available in the GUI.
#include <mc_rtc/gui/elements.h>
Public Member Functions
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Protected Member Functions
Element (const std::string &name)
Protected Attributes
std::string name_
int id_
Detailed Description
Element is the common class for every element's type available in the GUI.
Since we use static polymorphism in the StateBuilder we don't need to make any functions virtual
Constructor & Destructor Documentation
Element() [1/2]
mc_rtc::gui::Element::Element () inline
Invalid element, used for Python bindings.
Element() [2/2]
mc_rtc::gui::Element::Element (const std::string & name) protected
Member Function Documentation
handleRequest()
bool mc_rtc::gui::Element::handleRequest (const mc_rtc::Configuration &) inline
Take care of answering request from the client.
id() [1/2]
int mc_rtc::gui::Element::id () const inline
Access the stack id of an element (also referred to as SID)
Elements that should be displayed on the same line share the same id
id() [2/2]
void mc_rtc::gui::Element::id (int idIn) inline
Set the stack id of an element.
name()
const std::string& mc_rtc::gui::Element::name () const inline
Name of the element.
Referenced by mc_rtc::gui::ArrayInput(), mc_rtc::gui::ArrayLabel(), mc_rtc::gui::Arrow(), mc_rtc::gui::Button(), mc_rtc::gui::Checkbox(), mc_rtc::gui::ComboInput(), mc_rtc::gui::DataComboInput(), mc_rtc::gui::Force(), mc_rtc::gui::Form(), mc_rtc::gui::IntegerInput(), mc_rtc::gui::Label(), mc_rtc::gui::NumberInput(), mc_rtc::gui::NumberSlider(), mc_rtc::gui::Point3D(), mc_rtc::gui::Polygon(), mc_rtc::gui::Rotation(), mc_rtc::gui::Schema(), mc_rtc::gui::StringInput(), mc_rtc::gui::Trajectory(), mc_rtc::gui::Transform(), and mc_rtc::gui::XYTheta().
write()
void mc_rtc::gui::Element::write (mc_rtc::MessagePackBuilder &) inline
Write the widget to a MessagePackBuilder.
Writes nothing, the default data is written by GUIState since it knows if the sid is relevant.
Referenced by mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write(), and mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write().
write_size()
static constexpr size_t mc_rtc::gui::Element::write_size () inline static
Returns the size of the array representing the widget in the MessagePack.
By default, it includes the widget name, type and SID.
Referenced by mc_rtc::gui::ForceROImpl< GetForce, GetSurface >::write_size(), mc_rtc::gui::ArrowROImpl< GetStart, GetEnd >::write_size(), and mc_rtc::gui::DataElement< GetT >::write_size().
Member Data Documentation
id_
int mc_rtc::gui::Element::id_ protected
name_
std::string mc_rtc::gui::Element::name_ protected
Referenced by mc_rtc::gui::FormElement< FormArrayInput< T >, Elements::ArrayInput >::write().