mc_rtc::gui::ArrayLabelImpl< GetT > Struct Template Reference
mc_rtc::gui::ArrayLabelImpl< GetT > Struct Template Reference
ArrayLabel should display data in an array form.
#include <mc_rtc/gui/ArrayLabel.h>
Public Member Functions
ArrayLabelImpl (const std::string &name, GetT get_fn)
ArrayLabelImpl (const std::string &name, const std::vector< std::string > &labels, GetT get_fn)
ArrayLabelImpl ()
Invalid element.
void write (mc_rtc::MessagePackBuilder &writer)
Public Member Functions inherited from mc_rtc::gui::LabelImpl< GetT >
LabelImpl (const std::string &name, GetT get_fn)
LabelImpl ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
void write (mc_rtc::MessagePackBuilder &builder)
DataElement (const std::string &name, GetT get_fn)
Constructor.
DataElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::ArrayLabel
Static Public Attributes inherited from mc_rtc::gui::LabelImpl< GetT >
static constexpr auto type = Elements::Label
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::DataElement< GetT >
GetT get_fn_
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetT>
struct mc_rtc::gui::ArrayLabelImpl< GetT >
ArrayLabel should display data in an array form.
Labels can be provided optionally
Template Parameters
GetT should return anything that can be serialized as an array
See also
LabelImpl to display simple data
Constructor & Destructor Documentation
ArrayLabelImpl() [1/3]
template<typename GetT> mc_rtc::gui::ArrayLabelImpl< GetT >::ArrayLabelImpl (const std::string & name, GetT get_fn) inline
ArrayLabelImpl() [2/3]
template<typename GetT> mc_rtc::gui::ArrayLabelImpl< GetT >::ArrayLabelImpl (const std::string & name, const std::vector< std::string > & labels, GetT get_fn) inline
ArrayLabelImpl() [3/3]
template<typename GetT> mc_rtc::gui::ArrayLabelImpl< GetT >::ArrayLabelImpl () inline
Invalid element.
Member Function Documentation
write()
template<typename GetT> void mc_rtc::gui::ArrayLabelImpl< GetT >::write (mc_rtc::MessagePackBuilder & writer) inline
References mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::DataElement< GetT >::write().
write_size()
template<typename GetT> static constexpr size_t mc_rtc::gui::ArrayLabelImpl< GetT >::write_size () inline static
References mc_rtc::gui::DataElement< GetT >::write_size().
Member Data Documentation
type
template<typename GetT> constexpr auto mc_rtc::gui::ArrayLabelImpl< GetT >::type = Elements::ArrayLabel static