mc_rtc::gui::plot::impl::Ordinate< GetT > Struct Template Reference
mc_rtc::gui::plot::impl::Ordinate< GetT > Struct Template Reference
For a given plot, this holds options on the ordinate plot and a callback that returns the current value.
#include <mc_rtc/gui/plot/Ordinate.h>
Public Member Functions
Ordinate (const std::string &name, GetT get_fn, Color color, Style style, Side side)
void write (mc_rtc::MessagePackBuilder &builder) const
Ordinate & style (Style style)
Ordinate & side (Side side)
Static Public Attributes
static constexpr Type type = Type::Ordinate
Protected Attributes
std::string name_
GetT get_fn_
Color color_
Style style_
Side side_
Detailed Description
template<typename GetT>
struct mc_rtc::gui::plot::impl::Ordinate< GetT >
For a given plot, this holds options on the ordinate plot and a callback that returns the current value.
Constructor & Destructor Documentation
Ordinate()
template<typename GetT> mc_rtc::gui::plot::impl::Ordinate< GetT >::Ordinate (const std::string & name, GetT get_fn, Color color, Style style, Side side) inline
Member Function Documentation
side()
template<typename GetT> Ordinate& mc_rtc::gui::plot::impl::Ordinate< GetT >::side (Side side) inline
References mc_rtc::gui::plot::impl::Ordinate< GetT >::side_.
Referenced by mc_rtc::gui::plot::Y().
style()
template<typename GetT> Ordinate& mc_rtc::gui::plot::impl::Ordinate< GetT >::style (Style style) inline
References mc_rtc::gui::plot::impl::Ordinate< GetT >::style_.
Referenced by mc_rtc::gui::plot::Y().
write()
template<typename GetT> void mc_rtc::gui::plot::impl::Ordinate< GetT >::write (mc_rtc::MessagePackBuilder & builder) const inline
References mc_rtc::gui::plot::impl::Ordinate< GetT >::color_, mc_rtc::MessagePackBuilder::finish_array(), mc_rtc::gui::plot::impl::Ordinate< GetT >::get_fn_, mc_rtc::gui::plot::impl::Ordinate< GetT >::name_, mc_rtc::gui::plot::impl::Ordinate< GetT >::side_, mc_rtc::MessagePackBuilder::start_array(), mc_rtc::gui::plot::impl::Ordinate< GetT >::style_, mc_rtc::MessagePackBuilder::write(), and mc_rtc::gui::Color::write().
Referenced by mc_rtc::gui::plot::impl::OrdinateWithColor< GetT, GetColor >::write().
Member Data Documentation
color_
template<typename GetT> Color mc_rtc::gui::plot::impl::Ordinate< GetT >::color_ mutable protected
Referenced by mc_rtc::gui::plot::impl::Ordinate< GetT >::write(), and mc_rtc::gui::plot::impl::OrdinateWithColor< GetT, GetColor >::write().
get_fn_
template<typename GetT> GetT mc_rtc::gui::plot::impl::Ordinate< GetT >::get_fn_ protected
Referenced by mc_rtc::gui::plot::impl::Ordinate< GetT >::write().
name_
template<typename GetT> std::string mc_rtc::gui::plot::impl::Ordinate< GetT >::name_ protected
Referenced by mc_rtc::gui::plot::impl::Ordinate< GetT >::write().
side_
template<typename GetT> Side mc_rtc::gui::plot::impl::Ordinate< GetT >::side_ protected
Referenced by mc_rtc::gui::plot::impl::Ordinate< GetT >::side(), and mc_rtc::gui::plot::impl::Ordinate< GetT >::write().
style_
template<typename GetT> Style mc_rtc::gui::plot::impl::Ordinate< GetT >::style_ protected
Referenced by mc_rtc::gui::plot::impl::Ordinate< GetT >::style(), and mc_rtc::gui::plot::impl::Ordinate< GetT >::write().
type
template<typename GetT> constexpr Type mc_rtc::gui::plot::impl::Ordinate< GetT >::type = Type::Ordinate static