mc_tasks::MetaTask Struct Reference
mc_tasks::MetaTask Struct Reference abstract
Represents a generic task.
#include <mc_tasks/MetaTask.h>
Public Member Functions
virtual ~MetaTask ()
const std::string & type () const
Get the type of the task.
void name (const std::string &name)
Set a name for the task.
const std::string & name () const
Get the name of the task.
virtual void reset ()=0
Reset the task.
virtual void dimWeight (const Eigen::VectorXd &dimW)=0
Set the task's dimension weight vector.
virtual Eigen::VectorXd dimWeight () const =0
Get the current task's dim weight vector.
virtual void selectActiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={})=0
Setup an active joints selector.
virtual void selectUnactiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={})=0
Setup an unactive joints selector.
virtual void resetJointsSelector (mc_solver::QPSolver &solver)=0
Reset active joints selection.
virtual Eigen::VectorXd eval () const =0
Returns the task error.
virtual Eigen::VectorXd speed () const =0
Returns the task velocity.
virtual void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config)
Load parameters from a Configuration object.
Protected Member Functions
virtual void addToSolver (mc_solver::QPSolver &solver)=0
Add the task to a solver.
virtual void removeFromSolver (mc_solver::QPSolver &solver)=0
Remove the task from a solver.
virtual void update (mc_solver::QPSolver &solver)=0
Update the task.
virtual void addToLogger (mc_rtc::Logger &)
Add entries to the logger.
virtual void removeFromLogger (mc_rtc::Logger &)
Remove entries from the logger.
virtual void addToGUI (mc_rtc::gui::StateBuilder &)
Add elements to the GUI through the helper.
virtual void removeFromGUI (mc_rtc::gui::StateBuilder &)
Remove elements from the GUI through the helper.
virtual std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const
Add additional completion criterias to mc_control::CompletionCriteria object.
Static Protected Member Functions
static void addToSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void removeFromSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void update (MetaTask &t, mc_solver::QPSolver &solver)
static void addToLogger (MetaTask &t, mc_rtc::Logger &logger)
static void removeFromLogger (MetaTask &t, mc_rtc::Logger &logger)
static void addToGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void removeFromGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void ensureHasJoints (const mc_rbdyn::Robot &robot, const std::vector< std::string > &joints, const std::string &prefix)
Protected Attributes
std::string type_
std::string name_
Friends
struct mc_solver::QPSolver
struct mc_control::CompletionCriteria
Detailed Description
Represents a generic task.
A meta task may be composed of several tasks that work together to achieve a given goal
Constructor & Destructor Documentation
~MetaTask()
virtual mc_tasks::MetaTask::~MetaTask () virtual
Member Function Documentation
addToGUI() [1/2]
virtual void mc_tasks::MetaTask::addToGUI (mc_rtc::gui::StateBuilder &) protected virtual
Add elements to the GUI through the helper.
This will be called by the solver when the task is added.
The default implementation adds the type of the task under the {"Tasks", name_} category.
Reimplemented in mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::AdmittanceTask, mc_tasks::SurfaceTransformTask, mc_tasks::force::CoPTask, mc_tasks::EndEffectorTask, mc_tasks::VectorOrientationTask, mc_tasks::PostureTask, mc_tasks::PositionTask, mc_tasks::ExactCubicTrajectoryTask, mc_tasks::BSplineTrajectoryTask, mc_tasks::RelativeEndEffectorTask, mc_tasks::CoMTask, mc_tasks::OrientationTask, and mc_tasks::MomentumTask.
Referenced by addToGUI().
addToGUI() [2/2]
static void mc_tasks::MetaTask::addToGUI (MetaTask & t, mc_rtc::gui::StateBuilder & gui) inline static protected
Helper function to add a task to the gui when using another MetaTask inside a MetaTask
References addToGUI().
addToLogger() [1/2]
virtual void mc_tasks::MetaTask::addToLogger (mc_rtc::Logger &) inline protected virtual
Add entries to the logger.
This will be called by the solver if it holds a valid logger instance when the task is added.
The default implementation adds nothing to the log.
Reimplemented in mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::AdmittanceTask, mc_tasks::force::CoPTask, mc_tasks::EndEffectorTask, mc_tasks::VectorOrientationTask, mc_tasks::PostureTask, mc_tasks::SurfaceTransformTask, mc_tasks::PositionTask, mc_tasks::PositionBasedVisServoTask, mc_tasks::CoMTask, mc_tasks::OrientationTask, and mc_tasks::MomentumTask.
Referenced by addToLogger().
addToLogger() [2/2]
static void mc_tasks::MetaTask::addToLogger (MetaTask & t, mc_rtc::Logger & logger) inline static protected
Helper function to add a task to the logger when using another MetaTask inside a MetaTask
References addToLogger().
addToSolver() [1/2]
virtual void mc_tasks::MetaTask::addToSolver (mc_solver::QPSolver & solver) protected pure virtual
Add the task to a solver.
Parameters
solver Solver where to add the task
Implemented in mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::AdmittanceTask, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
Referenced by addToSolver().
addToSolver() [2/2]
static void mc_tasks::MetaTask::addToSolver (MetaTask & t, mc_solver::QPSolver & solver) inline static protected
Helper function when using another MetaTask inside a MetaTask as adding the task through the solver interface has important side-effects
References addToSolver().
buildCompletionCriteria()
virtual std::function<bool(const mc_tasks::MetaTask & task, std::string &)> mc_tasks::MetaTask::buildCompletionCriteria (double dt, const mc_rtc::Configuration & config) const protected virtual
Add additional completion criterias to mc_control::CompletionCriteria object.
Based on the input data, this should return a function that operates on the task and return true and complete the output if the criteria has been reached. In this function parameter, the output string should be completed by the function and not overwritten. The task passed to this function is always of the MetaTask type you're implementing and thus can be safely casted.
The default implementation is a function that returns true whatever happens.
Parameters
dt Timestep of the completion criteria
config Configuration for the CompletionCriteria
Reimplemented in mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::SurfaceTransformTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, and mc_tasks::force::CoPTask.
dimWeight() [1/2]
virtual void mc_tasks::MetaTask::dimWeight (const Eigen::VectorXd & dimW) pure virtual
Set the task's dimension weight vector.
It is the caller responsibility to ensure the dimensionality fits the underlying tasks' error function
Parameters
dimW The new tasks's dimension weight vector
Implemented in mc_tasks::force::ComplianceTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::AddRemoveContactTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
dimWeight() [2/2]
virtual Eigen::VectorXd mc_tasks::MetaTask::dimWeight () const pure virtual
Get the current task's dim weight vector.
Implemented in mc_tasks::force::ComplianceTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::AddRemoveContactTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
ensureHasJoints()
static void mc_tasks::MetaTask::ensureHasJoints (const mc_rbdyn::Robot & robot, const std::vector< std::string > & joints, const std::string & prefix) inline static protected
References mc_rbdyn::Robot::hasJoint(), and mc_rbdyn::Robot::name().
eval()
virtual Eigen::VectorXd mc_tasks::MetaTask::eval () const pure virtual
Returns the task error.
The vector's dimensions depend on the underlying task
Implemented in mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::ComplianceTask, mc_tasks::AddRemoveContactTask, mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
load()
virtual void mc_tasks::MetaTask::load (mc_solver::QPSolver & solver, const mc_rtc::Configuration & config) virtual
Load parameters from a Configuration object.
Reimplemented in mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::AdmittanceTask, mc_tasks::SurfaceTransformTask, mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::EndEffectorTask, mc_tasks::CoMTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::MomentumTask, and mc_tasks::PostureTask.
name() [1/2]
void mc_tasks::MetaTask::name (const std::string & name) inline
Set a name for the task.
This name will be used to identify the task in logs, GUI...
The name should be set before being added to the solver.
name() [2/2]
const std::string& mc_tasks::MetaTask::name () const inline
Get the name of the task.
removeFromGUI() [1/2]
virtual void mc_tasks::MetaTask::removeFromGUI (mc_rtc::gui::StateBuilder &) protected virtual
Remove elements from the GUI through the helper.
This will be called by the solver when the task is removed.
The default implementation removes the {"Tasks", name_} category.
Reimplemented in mc_tasks::lipm_stabilizer::StabilizerTask.
Referenced by removeFromGUI().
removeFromGUI() [2/2]
static void mc_tasks::MetaTask::removeFromGUI (MetaTask & t, mc_rtc::gui::StateBuilder & gui) inline static protected
Helper function to remove a task from the gui when using another MetaTask inside a MetaTask
References removeFromGUI().
removeFromLogger() [1/2]
virtual void mc_tasks::MetaTask::removeFromLogger (mc_rtc::Logger &) inline protected virtual
Remove entries from the logger.
This will be called by the solver when the task is removed.
The default implementation removes nothing from the log.
Reimplemented in mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::AdmittanceTask, mc_tasks::force::CoPTask, mc_tasks::EndEffectorTask, mc_tasks::VectorOrientationTask, mc_tasks::PostureTask, mc_tasks::SurfaceTransformTask, mc_tasks::PositionTask, mc_tasks::PositionBasedVisServoTask, mc_tasks::CoMTask, mc_tasks::OrientationTask, and mc_tasks::MomentumTask.
Referenced by removeFromLogger().
removeFromLogger() [2/2]
static void mc_tasks::MetaTask::removeFromLogger (MetaTask & t, mc_rtc::Logger & logger) inline static protected
Helper function to remove a task from the logger when using another MetaTask inside a MetaTask
References removeFromLogger().
removeFromSolver() [1/2]
virtual void mc_tasks::MetaTask::removeFromSolver (mc_solver::QPSolver & solver) protected pure virtual
Remove the task from a solver.
Parameters
solver Solver from which to remove the task
Implemented in mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
Referenced by removeFromSolver().
removeFromSolver() [2/2]
static void mc_tasks::MetaTask::removeFromSolver (MetaTask & t, mc_solver::QPSolver & solver) inline static protected
Helper function when using another MetaTask inside a MetaTask as removing the task through the solver interface has important side-effects
References removeFromSolver().
reset()
virtual void mc_tasks::MetaTask::reset () pure virtual
Reset the task.
Implemented in mc_tasks::force::ComplianceTask, mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::GazeTask, mc_tasks::force::AdmittanceTask, mc_tasks::PositionBasedVisServoTask, mc_tasks::force::CoPTask, mc_tasks::PositionTask, mc_tasks::RelativeEndEffectorTask, mc_tasks::EndEffectorTask, mc_tasks::VectorOrientationTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::SurfaceTransformTask, mc_tasks::LookAtTask, mc_tasks::OrientationTask, mc_tasks::MomentumTask, mc_tasks::CoMTask, and mc_tasks::PostureTask.
resetJointsSelector()
virtual void mc_tasks::MetaTask::resetJointsSelector (mc_solver::QPSolver & solver) pure virtual
Reset active joints selection.
Parameters
solver Solver where the task is involved
Implemented in mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::force::ComplianceTask, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
selectActiveJoints()
virtual void mc_tasks::MetaTask::selectActiveJoints (mc_solver::QPSolver & solver, const std::vector< std::string > & activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> & activeDofs = {}) pure virtual
Setup an active joints selector.
This function setups a tasks::qp;:JointsSelector for the task. Only the provided joints will be used to solve the task.
Note
Calling this method or the related selectUnactiveJoints should reset the current joints' selection
Parameters
solver Solver where the task is involved
activeJointsName Active joints in the task
activeDofs Allow to select only part of the dofs of a joint
Implemented in mc_tasks::force::ComplianceTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
selectUnactiveJoints()
virtual void mc_tasks::MetaTask::selectUnactiveJoints (mc_solver::QPSolver & solver, const std::vector< std::string > & unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> & unactiveDofs = {}) pure virtual
Setup an unactive joints selector.
This function setups a tasks::qp;:JointsSelector for the task. All joints will be used to realize the task except those provided here.
Note
Calling this method or the related selectActiveJoints should reset the current joints' selection
Parameters
solver Solver where the task is involved
unactiveJointsName Active joints in the task
unactiveDofs Allow to select only part of the dofs of a joint
Implemented in mc_tasks::force::ComplianceTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
speed()
virtual Eigen::VectorXd mc_tasks::MetaTask::speed () const pure virtual
Returns the task velocity.
The vector's dimensions depend on the underlying task
Implemented in mc_tasks::force::ComplianceTask, mc_tasks::TrajectoryTaskGeneric< T >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::OrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::TransformTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::CoMTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::MomentumTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::PositionBasedVisServoTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::VectorOrientationTask >, mc_tasks::TrajectoryTaskGeneric< tasks::qp::GazeTask >, mc_tasks::AddRemoveContactTask, mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::EndEffectorTask, and mc_tasks::PostureTask.
type()
const std::string& mc_tasks::MetaTask::type () const inline
Get the type of the task.
update() [1/2]
virtual void mc_tasks::MetaTask::update (mc_solver::QPSolver & solver) protected pure virtual
Update the task.
This function (usually) has to be called at every iteration of the solver once it has been added. It should update the state of the task.
Parameters
solver Solver in which the task is inserted
Implemented in mc_tasks::lipm_stabilizer::StabilizerTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >, mc_tasks::force::AdmittanceTask, mc_tasks::EndEffectorTask, mc_tasks::PostureTask, mc_tasks::force::DampingTask, mc_tasks::LookAtTFTask, and mc_tasks::LookAtSurfaceTask.
Referenced by update().
update() [2/2]
static void mc_tasks::MetaTask::update (MetaTask & t, mc_solver::QPSolver & solver) inline static protected
Helper function when using another MetaTask inside a MetaTask
References update().
Friends And Related Function Documentation
mc_control::CompletionCriteria
friend struct mc_control::CompletionCriteria friend
mc_solver::QPSolver
friend struct mc_solver::QPSolver friend
Member Data Documentation
name_
std::string mc_tasks::MetaTask::name_ protected
type_
std::string mc_tasks::MetaTask::type_ protected