mc_rtc::gui::TrajectoryImpl< GetT > Struct Template Reference
mc_rtc::gui::TrajectoryImpl< GetT > Struct Template Reference
Trajectory can represent a pre-defined trajectory or a real-time trajectory depending on type of data returned by the callback.
#include <mc_rtc/gui/Trajectory.h>
Public Member Functions
TrajectoryImpl (const std::string &name, const LineConfig &config, GetT get_fn)
TrajectoryImpl ()
Invalid element.
void write (mc_rtc::MessagePackBuilder &builder)
Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
void write (mc_rtc::MessagePackBuilder &builder)
DataElement (const std::string &name, GetT get_fn)
Constructor.
DataElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Trajectory
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::DataElement< GetT >
GetT get_fn_
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetT>
struct mc_rtc::gui::TrajectoryImpl< GetT >
Trajectory can represent a pre-defined trajectory or a real-time trajectory depending on type of data returned by the callback.
Styling information is provided to inform the client about how to display the trajectory
Template Parameters
GetT Should return either an sva::PTransformd or an Eigen::Vector3d (real-time trajectory) or a vector of these types (pre-defined trajectory)
Constructor & Destructor Documentation
TrajectoryImpl() [1/2]
template<typename GetT> mc_rtc::gui::TrajectoryImpl< GetT >::TrajectoryImpl (const std::string & name, const LineConfig & config, GetT get_fn) inline
TrajectoryImpl() [2/2]
template<typename GetT> mc_rtc::gui::TrajectoryImpl< GetT >::TrajectoryImpl () inline
Invalid element.
Member Function Documentation
write()
template<typename GetT> void mc_rtc::gui::TrajectoryImpl< GetT >::write (mc_rtc::MessagePackBuilder & builder) inline
References mc_rtc::gui::LineConfig::write(), and mc_rtc::gui::DataElement< GetT >::write().
write_size()
template<typename GetT> static constexpr size_t mc_rtc::gui::TrajectoryImpl< GetT >::write_size () inline static
References mc_rtc::gui::LineConfig::write_size(), and mc_rtc::gui::DataElement< GetT >::write_size().
Member Data Documentation
type
template<typename GetT> constexpr auto mc_rtc::gui::TrajectoryImpl< GetT >::type = Elements::Trajectory static