mc_tasks::SurfaceTransformTask Struct Reference
mc_tasks::SurfaceTransformTask Struct Reference
Control the Surface of a body.
#include <mc_tasks/SurfaceTransformTask.h>
Public Types
using TrajectoryBase = TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
Public Types inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
using TrajectoryBase = TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
Public Member Functions
SurfaceTransformTask (const std::string &surfaceName, const mc_rbdyn::Robots &robots, unsigned int robotIndex, double stiffness=2.0, double weight=500)
Constructor.
virtual void reset () override
Reset the task.
sva::PTransformd target () const
Get the body Surface target.
void target (const sva::PTransformd &pos)
Set the body Surface target.
void targetSurface (unsigned int robotIndex, const std::string &surfaceName, const sva::PTransformd &offset)
Targets a robot surface with an optional offset.
const std::string & surface () const
Retrieve the controlled surface name.
const sva::PTransformd surfacePose () const
Returns the pose of the surface in the inertial frame.
std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add support for the following criterias:
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
void setGains (const sva::MotionVecd &stiffness, const sva::MotionVecd &damping)
Set dimensional stiffness and damping.
void stiffness (const sva::MotionVecd &stiffness)
Set dimensional stiffness.
sva::MotionVecd mvStiffness ()
Get dimensional stiffness as a motion vector.
void damping (const sva::MotionVecd &damping)
Set dimensional damping.
sva::MotionVecd mvDamping ()
Get dimensional damping as a motion vector.
void refVelB (const sva::MotionVecd &velB)
Set trajectory task's reference velocity from motion vector in body coordinates.
sva::MotionVecd refVelB () const
Get reference velocity in body coordinates as a motion vector.
void refAccel (const sva::MotionVecd &accel)
Set trajectory task's reference acceleration from motion vector.
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
TrajectoryTaskGeneric (const mc_rbdyn::Robots &robots, unsigned int robotIndex, double stiffness, double weight)
Constructor (auto damping)
virtual ~TrajectoryTaskGeneric ()
void refVel (const Eigen::VectorXd &vel)
Set the trajectory reference velocity.
const Eigen::VectorXd & refVel () const
Get the trajectory reference velocity.
void refAccel (const Eigen::VectorXd &accel)
Set the trajectory reference acceleration.
const Eigen::VectorXd & refAccel () const
Get the trajectory reference acceleration.
void stiffness (double stiffness)
Set the task stiffness/damping.
void stiffness (const Eigen::VectorXd &stiffness)
Set dimensional stiffness.
double stiffness () const
Get the current task stiffness.
void damping (double damping)
Set the task damping, leaving its stiffness unchanged.
void damping (const Eigen::VectorXd &damping)
Set dimensional damping.
double damping () const
Get the current task damping.
void setGains (double stiffness, double damping)
Set both stiffness and damping.
void setGains (const Eigen::VectorXd &stiffness, const Eigen::VectorXd &damping)
Set dimensional stiffness and damping.
const Eigen::VectorXd & dimStiffness () const
Get the current task dimensional stiffness.
const Eigen::VectorXd & dimDamping () const
Get the current task dimensional damping.
void weight (double w)
Set the task weight.
double weight () const
Returns the task weight.
virtual void dimWeight (const Eigen::VectorXd &dimW) override
Set the task's dimension weight vector.
virtual Eigen::VectorXd dimWeight () const override
Get the current task's dim weight vector.
virtual void selectActiveJoints (const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={}, bool checkJoints=true)
Create an active joints selector.
virtual void selectActiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={}) override
Create an active joints selector.
virtual void selectUnactiveJoints (const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={}, bool checkJoints=true)
Create an unactive joints selector.
virtual void selectUnactiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={}) override
Create an unactive joints selector.
virtual void resetJointsSelector ()
virtual void resetJointsSelector (mc_solver::QPSolver &solver) override
Reset active joints selection.
virtual Eigen::VectorXd eval () const override
Returns the task error.
virtual Eigen::VectorXd speed () const override
Returns the task velocity.
const Eigen::VectorXd & normalAcc () const
const Eigen::MatrixXd & jac () const
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::MetaTask
virtual ~MetaTask ()
const std::string & type () const
Get the type of the task.
void name (const std::string &name)
Set a name for the task.
const std::string & name () const
Get the name of the task.
Protected Member Functions
void addToGUI (mc_rtc::gui::StateBuilder &gui) override
Add elements to the GUI through the helper.
Protected Member Functions inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
void finalize (Args &&... args)
void addToGUI (mc_rtc::gui::StateBuilder &) override
Add elements to the GUI through the helper.
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add additional completion criterias to mc_control::CompletionCriteria object.
virtual void addToSolver (mc_solver::QPSolver &solver) override
Add the task to a solver.
Protected Member Functions inherited from mc_tasks::MetaTask
virtual void removeFromGUI (mc_rtc::gui::StateBuilder &)
Remove elements from the GUI through the helper.
Protected Attributes
std::string surfaceName
Protected Attributes inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
const mc_rbdyn::Robots & robots
unsigned int rIndex
std::shared_ptr< tasks::qp::SurfaceTransformTask > errorT
Eigen::VectorXd refVel_
Eigen::VectorXd refAccel_
bool inSolver_
std::shared_ptr< tasks::qp::TrajectoryTask > trajectoryT_
Protected Attributes inherited from mc_tasks::MetaTask
std::string type_
std::string name_
Additional Inherited Members
Static Protected Member Functions inherited from mc_tasks::MetaTask
static void addToSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void removeFromSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void update (MetaTask &t, mc_solver::QPSolver &solver)
static void addToLogger (MetaTask &t, mc_rtc::Logger &logger)
static void removeFromLogger (MetaTask &t, mc_rtc::Logger &logger)
static void addToGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void removeFromGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void ensureHasJoints (const mc_rbdyn::Robot &robot, const std::vector< std::string > &joints, const std::string &prefix)
Detailed Description
Control the Surface of a body.
This task is thin wrapper around the appropriate tasks in Tasks.
Member Typedef Documentation
TrajectoryBase
using mc_tasks::SurfaceTransformTask::TrajectoryBase = TrajectoryTaskGeneric<tasks::qp::SurfaceTransformTask>
Constructor & Destructor Documentation
SurfaceTransformTask()
mc_tasks::SurfaceTransformTask::SurfaceTransformTask (const std::string & surfaceName, const mc_rbdyn::Robots & robots, unsigned int robotIndex, double stiffness = 2.0, double weight = 500)
Constructor.
Parameters
surfaceName Name of the surface frame to control
robots Robots controlled by this task
robotIndex Index of the robot controlled by this task
stiffness Task stiffness
weight Task weight
Member Function Documentation
addToGUI()
void mc_tasks::SurfaceTransformTask::addToGUI (mc_rtc::gui::StateBuilder &) override protected virtual
Add elements to the GUI through the helper.
This will be called by the solver when the task is added.
The default implementation adds the type of the task under the {"Tasks", name_} category.
Reimplemented from mc_tasks::MetaTask.
addToLogger()
void mc_tasks::SurfaceTransformTask::addToLogger (mc_rtc::Logger &) override virtual
Add entries to the logger.
This will be called by the solver if it holds a valid logger instance when the task is added.
The default implementation adds nothing to the log.
Reimplemented from mc_tasks::MetaTask.
buildCompletionCriteria()
std::function<bool(const mc_tasks::MetaTask & task, std::string &)> mc_tasks::SurfaceTransformTask::buildCompletionCriteria (double dt, const mc_rtc::Configuration & config) const override virtual
Add support for the following criterias:
wrench: completed when the surface wrench reaches the given wrench, if some values are NaN, this direction is ignored. Only valid if the surface controlled by this task is attached to a force sensor, throws otherwise
Exceptions
If wrench is used but the surface is not attached to a force sensor
Reimplemented from mc_tasks::MetaTask.
damping()
void mc_tasks::SurfaceTransformTask::damping (const sva::MotionVecd & damping) inline
Set dimensional damping.
Parameters
damping Dimensional damping as a motion vector
References mc_tasks::TrajectoryTaskGeneric< T >::damping().
load()
void mc_tasks::SurfaceTransformTask::load (mc_solver::QPSolver & solver, const mc_rtc::Configuration & config) override virtual
Load parameters from a Configuration object.
Reimplemented from mc_tasks::MetaTask.
mvDamping()
sva::MotionVecd mc_tasks::SurfaceTransformTask::mvDamping () inline
Get dimensional damping as a motion vector.
mvStiffness()
sva::MotionVecd mc_tasks::SurfaceTransformTask::mvStiffness () inline
Get dimensional stiffness as a motion vector.
refAccel()
void mc_tasks::SurfaceTransformTask::refAccel (const sva::MotionVecd & accel) inline
Set trajectory task's reference acceleration from motion vector.
Parameters
acc Reference acceleration.
References mc_tasks::TrajectoryTaskGeneric< T >::refAccel().
refVelB() [1/2]
void mc_tasks::SurfaceTransformTask::refVelB (const sva::MotionVecd & velB) inline
Set trajectory task's reference velocity from motion vector in body coordinates.
Parameters
velB Reference velocity in body coordinates, i.e. velocity of the surface frame in the surface frame.
References mc_tasks::TrajectoryTaskGeneric< T >::refVel().
refVelB() [2/2]
sva::MotionVecd mc_tasks::SurfaceTransformTask::refVelB () const inline
Get reference velocity in body coordinates as a motion vector.
removeFromLogger()
void mc_tasks::SurfaceTransformTask::removeFromLogger (mc_rtc::Logger &) override virtual
Remove entries from the logger.
This will be called by the solver when the task is removed.
The default implementation removes nothing from the log.
Reimplemented from mc_tasks::MetaTask.
reset()
virtual void mc_tasks::SurfaceTransformTask::reset () override virtual
Reset the task.
Set the task target to the current surface, and reset its target velocity and acceleration to zero.
Reimplemented from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >.
Reimplemented in mc_tasks::force::AdmittanceTask, and mc_tasks::force::CoPTask.
setGains()
void mc_tasks::SurfaceTransformTask::setGains (const sva::MotionVecd & stiffness, const sva::MotionVecd & damping) inline
Set dimensional stiffness and damping.
Parameters
stiffness Dimensional stiffness
damping Dimensional damping
References mc_tasks::TrajectoryTaskGeneric< T >::setGains().
stiffness()
void mc_tasks::SurfaceTransformTask::stiffness (const sva::MotionVecd & stiffness) inline
Set dimensional stiffness.
Damping is automatically set to 2*sqrt(stiffness)
Parameters
stiffness Dimensional stiffness as a motion vector
References mc_tasks::TrajectoryTaskGeneric< T >::stiffness().
surface()
const std::string& mc_tasks::SurfaceTransformTask::surface () const inline
Retrieve the controlled surface name.
surfacePose()
const sva::PTransformd mc_tasks::SurfaceTransformTask::surfacePose () const
Returns the pose of the surface in the inertial frame.
target() [1/2]
sva::PTransformd mc_tasks::SurfaceTransformTask::target () const
Get the body Surface target.
target() [2/2]
void mc_tasks::SurfaceTransformTask::target (const sva::PTransformd & pos)
Set the body Surface target.
Parameters
pos Surface in world frame
targetSurface()
void mc_tasks::SurfaceTransformTask::targetSurface (unsigned int robotIndex, const std::string & surfaceName, const sva::PTransformd & offset)
Targets a robot surface with an optional offset.
The offset is expressed in the target contact frame
Parameters
robotIndex Index of the robot to target (could be the environment)
surfaceName Surface name in the target robot
offset offset defined in the target contact frame
Member Data Documentation
surfaceName
std::string mc_tasks::SurfaceTransformTask::surfaceName protected