mc_rtc::gui::PolygonImpl< GetT > Struct Template Reference
mc_rtc::gui::PolygonImpl< GetT > Struct Template Reference
Polygon should display a polygon or a set of polygons.
#include <mc_rtc/gui/Polygon.h>
Public Member Functions
PolygonImpl (const std::string &name, const Color &color, GetT get_fn)
PolygonImpl ()
Invalid element.
void write (mc_rtc::MessagePackBuilder &builder)
Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
void write (mc_rtc::MessagePackBuilder &builder)
DataElement (const std::string &name, GetT get_fn)
Constructor.
DataElement ()
Invalid element.
Public Member Functions inherited from mc_rtc::gui::Element
const std::string & name () const
Name of the element.
int id () const
Access the stack id of an element (also referred to as SID)
void id (int idIn)
Set the stack id of an element.
void write (mc_rtc::MessagePackBuilder &)
Write the widget to a MessagePackBuilder.
bool handleRequest (const mc_rtc::Configuration &)
Take care of answering request from the client.
Element ()
Invalid element, used for Python bindings.
Static Public Member Functions
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::DataElement< GetT >
static constexpr size_t write_size ()
Static Public Member Functions inherited from mc_rtc::gui::Element
static constexpr size_t write_size ()
Returns the size of the array representing the widget in the MessagePack.
Static Public Attributes
static constexpr auto type = Elements::Polygon
Additional Inherited Members
Protected Member Functions inherited from mc_rtc::gui::Element
Element (const std::string &name)
Protected Attributes inherited from mc_rtc::gui::DataElement< GetT >
GetT get_fn_
Protected Attributes inherited from mc_rtc::gui::Element
std::string name_
int id_
Detailed Description
template<typename GetT>
struct mc_rtc::gui::PolygonImpl< GetT >
Polygon should display a polygon or a set of polygons.
A color is provided to display the polygon(s)
Template Parameters
GetT Should return an std::vector<Eigen::Vector3d> (one polygon) or an std::vector<std::vector<Eigen:Vector3d>> (list of polygons)
Constructor & Destructor Documentation
PolygonImpl() [1/2]
template<typename GetT> mc_rtc::gui::PolygonImpl< GetT >::PolygonImpl (const std::string & name, const Color & color, GetT get_fn) inline
PolygonImpl() [2/2]
template<typename GetT> mc_rtc::gui::PolygonImpl< GetT >::PolygonImpl () inline
Invalid element.
Member Function Documentation
write()
template<typename GetT> void mc_rtc::gui::PolygonImpl< GetT >::write (mc_rtc::MessagePackBuilder & builder) inline
References mc_rtc::gui::Color::write(), and mc_rtc::gui::DataElement< GetT >::write().
write_size()
template<typename GetT> static constexpr size_t mc_rtc::gui::PolygonImpl< GetT >::write_size () inline static
References mc_rtc::gui::Color::write_size(), and mc_rtc::gui::DataElement< GetT >::write_size().
Member Data Documentation
type
template<typename GetT> constexpr auto mc_rtc::gui::PolygonImpl< GetT >::type = Elements::Polygon static