mc_tasks::TrajectoryTaskGeneric< T > Struct Template Reference
mc_tasks::TrajectoryTaskGeneric< T > Struct Template Reference
Generic wrapper for a tasks::qp::TrajectoryTask.
#include <mc_tasks/TrajectoryTaskGeneric.h>
Public Types
using TrajectoryBase = TrajectoryTaskGeneric< T >
Public Member Functions
TrajectoryTaskGeneric (const mc_rbdyn::Robots &robots, unsigned int robotIndex, double stiffness, double weight)
Constructor (auto damping)
virtual ~TrajectoryTaskGeneric ()
virtual void reset () override
Reset task target velocity and acceleration to zero.
void refVel (const Eigen::VectorXd &vel)
Set the trajectory reference velocity.
const Eigen::VectorXd & refVel () const
Get the trajectory reference velocity.
void refAccel (const Eigen::VectorXd &accel)
Set the trajectory reference acceleration.
const Eigen::VectorXd & refAccel () const
Get the trajectory reference acceleration.
void stiffness (double stiffness)
Set the task stiffness/damping.
void stiffness (const Eigen::VectorXd &stiffness)
Set dimensional stiffness.
void damping (double damping)
Set the task damping, leaving its stiffness unchanged.
void damping (const Eigen::VectorXd &damping)
Set dimensional damping.
void setGains (double stiffness, double damping)
Set both stiffness and damping.
void setGains (const Eigen::VectorXd &stiffness, const Eigen::VectorXd &damping)
Set dimensional stiffness and damping.
double stiffness () const
Get the current task stiffness.
double damping () const
Get the current task damping.
const Eigen::VectorXd & dimStiffness () const
Get the current task dimensional stiffness.
const Eigen::VectorXd & dimDamping () const
Get the current task dimensional damping.
void weight (double w)
Set the task weight.
double weight () const
Returns the task weight.
virtual void dimWeight (const Eigen::VectorXd &dimW) override
Set the task's dimension weight vector.
virtual Eigen::VectorXd dimWeight () const override
Get the current task's dim weight vector.
virtual void selectActiveJoints (const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={})
virtual void selectActiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={}) override
Setup an active joints selector.
virtual void selectUnactiveJoints (const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={})
virtual void selectUnactiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={}) override
Setup an unactive joints selector.
virtual void resetJointsSelector ()
virtual void resetJointsSelector (mc_solver::QPSolver &solver) override
Reset active joints selection.
virtual Eigen::VectorXd eval () const override
Returns the task error.
virtual Eigen::VectorXd speed () const override
Returns the task velocity.
const Eigen::VectorXd & normalAcc () const
const Eigen::MatrixXd & jac () const
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::MetaTask
virtual ~MetaTask ()
const std::string & type () const
Get the type of the task.
void name (const std::string &name)
Set a name for the task.
const std::string & name () const
Get the name of the task.
Protected Member Functions
template<typename... Args>
void finalize (Args &&... args)
void addToGUI (mc_rtc::gui::StateBuilder &) override
Add elements to the GUI through the helper.
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add additional completion criterias to mc_control::CompletionCriteria object.
virtual void addToSolver (mc_solver::QPSolver &solver) override
Add the task to a solver.
Protected Member Functions inherited from mc_tasks::MetaTask
virtual void removeFromGUI (mc_rtc::gui::StateBuilder &)
Remove elements from the GUI through the helper.
Protected Attributes
const mc_rbdyn::Robots & robots
unsigned int rIndex
std::shared_ptr< T > errorT = nullptr
Eigen::VectorXd refVel_
Eigen::VectorXd refAccel_
bool inSolver_ = false
std::shared_ptr< tasks::qp::TrajectoryTask > trajectoryT_ = nullptr
Protected Attributes inherited from mc_tasks::MetaTask
std::string type_
std::string name_
Additional Inherited Members
Static Protected Member Functions inherited from mc_tasks::MetaTask
static void addToSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void removeFromSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void update (MetaTask &t)
Detailed Description
template<typename T>
struct mc_tasks::TrajectoryTaskGeneric< T >
Generic wrapper for a tasks::qp::TrajectoryTask.
This task is meant to be derived to build actual tasks
Member Typedef Documentation
TrajectoryBase
template<typename T> using mc_tasks::TrajectoryTaskGeneric< T >::TrajectoryBase = TrajectoryTaskGeneric<T>
Constructor & Destructor Documentation
TrajectoryTaskGeneric()
template<typename T> mc_tasks::TrajectoryTaskGeneric< T >::TrajectoryTaskGeneric (const mc_rbdyn::Robots & robots, unsigned int robotIndex, double stiffness, double weight)
Constructor (auto damping)
This is a simple constructor alternative. Damping is set to 2*sqrt(stiffness). This is the most appropriate constructor to use TrajectoryTask as a SetPointTask
Parameters
robots Robots used in the task
robotIndex Index of the robot controlled by the task
stiffness Stiffness of the task
weight Weight of the task
~TrajectoryTaskGeneric()
template<typename T> virtual mc_tasks::TrajectoryTaskGeneric< T >::~TrajectoryTaskGeneric () virtual
Member Function Documentation
addToGUI()
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::addToGUI (mc_rtc::gui::StateBuilder &) override protected virtual
Add elements to the GUI through the helper.
This will be called by the solver when the task is added.
The default implementation adds the type of the task under the {"Tasks", name_} category.
Reimplemented from mc_tasks::MetaTask.
addToLogger()
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::addToLogger (mc_rtc::Logger &) override protected virtual
Add entries to the logger.
This will be called by the solver if it holds a valid logger instance when the task is added.
The default implementation adds nothing to the log.
Reimplemented from mc_tasks::MetaTask.
addToSolver()
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::addToSolver (mc_solver::QPSolver & solver) override protected virtual
Add the task to a solver.
Parameters
solver Solver where to add the task
Implements mc_tasks::MetaTask.
Reimplemented in mc_tasks::force::AdmittanceTask, mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, and mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >.
buildCompletionCriteria()
template<typename T> std::function<bool(const mc_tasks::MetaTask & task, std::string &)> mc_tasks::TrajectoryTaskGeneric< T >::buildCompletionCriteria (double dt, const mc_rtc::Configuration & config) const override protected virtual
Add additional completion criterias to mc_control::CompletionCriteria object.
Based on the input data, this should return a function that operates on the task and return true and complete the output if the criteria has been reached. In this function parameter, the output string should be completed by the function and not overwritten. The task passed to this function is always of the MetaTask type you're implementing and thus can be safely casted.
The default implementation is a function that returns true whatever happens.
Parameters
dt Timestep of the completion criteria
config Configuration for the CompletionCriteria
Reimplemented from mc_tasks::MetaTask.
damping() [1/3]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::damping (double damping)
Set the task damping, leaving its stiffness unchanged.
Parameters
damping Task stiffness
damping() [2/3]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::damping (const Eigen::VectorXd & damping)
Set dimensional damping.
The caller should be sure that the dimension of the vector fits the task dimension.
Parameters
damping Dimensional damping
damping() [3/3]
template<typename T> double mc_tasks::TrajectoryTaskGeneric< T >::damping () const
Get the current task damping.
Referenced by mc_tasks::SurfaceTransformTask::damping().
dimDamping()
template<typename T> const Eigen::VectorXd& mc_tasks::TrajectoryTaskGeneric< T >::dimDamping () const
Get the current task dimensional damping.
dimStiffness()
template<typename T> const Eigen::VectorXd& mc_tasks::TrajectoryTaskGeneric< T >::dimStiffness () const
Get the current task dimensional stiffness.
dimWeight() [1/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::dimWeight (const Eigen::VectorXd & dimW) override virtual
Set the task's dimension weight vector.
It is the caller responsibility to ensure the dimensionality fits the underlying tasks' error function
Parameters
dimW The new tasks's dimension weight vector
Implements mc_tasks::MetaTask.
Reimplemented in mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, and mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >.
dimWeight() [2/2]
template<typename T> virtual Eigen::VectorXd mc_tasks::TrajectoryTaskGeneric< T >::dimWeight () const override virtual
Get the current task's dim weight vector.
Implements mc_tasks::MetaTask.
Reimplemented in mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, and mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >.
eval()
template<typename T> virtual Eigen::VectorXd mc_tasks::TrajectoryTaskGeneric< T >::eval () const override virtual
Returns the task error.
The vector's dimensions depend on the underlying task
Implements mc_tasks::MetaTask.
Reimplemented in mc_tasks::SplineTrajectoryTask< Derived >, mc_tasks::SplineTrajectoryTask< ExactCubicTrajectoryTask >, and mc_tasks::SplineTrajectoryTask< BSplineTrajectoryTask >.
finalize()
template<typename T> template<typename... Args> void mc_tasks::TrajectoryTaskGeneric< T >::finalize (Args &&... args) protected
This function should be called to finalize the task creation, it will create the actual tasks objects
jac()
template<typename T> const Eigen::MatrixXd& mc_tasks::TrajectoryTaskGeneric< T >::jac () const
load()
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::load (mc_solver::QPSolver & solver, const mc_rtc::Configuration & config) override virtual
Load parameters from a Configuration object.
Reimplemented from mc_tasks::MetaTask.
normalAcc()
template<typename T> const Eigen::VectorXd& mc_tasks::TrajectoryTaskGeneric< T >::normalAcc () const
refAccel() [1/2]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::refAccel (const Eigen::VectorXd & accel)
Set the trajectory reference acceleration.
Parameters
accel New reference acceleration
refAccel() [2/2]
template<typename T> const Eigen::VectorXd& mc_tasks::TrajectoryTaskGeneric< T >::refAccel () const
Get the trajectory reference acceleration.
Referenced by mc_tasks::SurfaceTransformTask::refAccel().
refVel() [1/2]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::refVel (const Eigen::VectorXd & vel)
Set the trajectory reference velocity.
Parameters
vel New reference velocity
refVel() [2/2]
template<typename T> const Eigen::VectorXd& mc_tasks::TrajectoryTaskGeneric< T >::refVel () const
Get the trajectory reference velocity.
Referenced by mc_tasks::SurfaceTransformTask::refVelB().
removeFromLogger()
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::removeFromLogger (mc_rtc::Logger &) override protected virtual
Remove entries from the logger.
This will be called by the solver when the task is removed.
The default implementation removes nothing from the log.
Reimplemented from mc_tasks::MetaTask.
reset()
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::reset () override virtual
Reset task target velocity and acceleration to zero.
Implements mc_tasks::MetaTask.
Reimplemented in mc_tasks::force::AdmittanceTask, mc_tasks::GazeTask, mc_tasks::PositionBasedVisServoTask, mc_tasks::force::CoPTask, mc_tasks::PositionTask, mc_tasks::VectorOrientationTask, mc_tasks::LookAtTask, mc_tasks::OrientationTask, mc_tasks::SurfaceTransformTask, and mc_tasks::CoMTask.
resetJointsSelector() [1/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::resetJointsSelector () virtual
resetJointsSelector() [2/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::resetJointsSelector (mc_solver::QPSolver & solver) override virtual
Reset active joints selection.
Parameters
solver Solver where the task is involved
Implements mc_tasks::MetaTask.
selectActiveJoints() [1/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::selectActiveJoints (const std::vector< std::string > & activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> & activeDofs = {}) virtual
selectActiveJoints() [2/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::selectActiveJoints (mc_solver::QPSolver & solver, const std::vector< std::string > & activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> & activeDofs = {}) override virtual
Setup an active joints selector.
This function setups a tasks::qp;:JointsSelector for the task. Only the provided joints will be used to solve the task.
Note
Calling this method or the related selectUnactiveJoints should reset the current joints' selection
Parameters
solver Solver where the task is involved
activeJointsName Active joints in the task
activeDofs Allow to select only part of the dofs of a joint
Implements mc_tasks::MetaTask.
selectUnactiveJoints() [1/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::selectUnactiveJoints (const std::vector< std::string > & unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> & unactiveDofs = {}) virtual
selectUnactiveJoints() [2/2]
template<typename T> virtual void mc_tasks::TrajectoryTaskGeneric< T >::selectUnactiveJoints (mc_solver::QPSolver & solver, const std::vector< std::string > & unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> & unactiveDofs = {}) override virtual
Setup an unactive joints selector.
This function setups a tasks::qp;:JointsSelector for the task. All joints will be used to realize the task except those provided here.
Note
Calling this method or the related selectActiveJoints should reset the current joints' selection
Parameters
solver Solver where the task is involved
unactiveJointsName Active joints in the task
unactiveDofs Allow to select only part of the dofs of a joint
Implements mc_tasks::MetaTask.
setGains() [1/2]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::setGains (double stiffness, double damping)
Set both stiffness and damping.
Parameters
stiffness Task stiffness
damping Task damping
Referenced by mc_tasks::SurfaceTransformTask::setGains().
setGains() [2/2]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::setGains (const Eigen::VectorXd & stiffness, const Eigen::VectorXd & damping)
Set dimensional stiffness and damping.
The caller should be sure that the dimensions of the vectors fit the task dimension.
Parameters
stiffness Dimensional stiffness
damping Dimensional damping
speed()
template<typename T> virtual Eigen::VectorXd mc_tasks::TrajectoryTaskGeneric< T >::speed () const override virtual
Returns the task velocity.
The vector's dimensions depend on the underlying task
Implements mc_tasks::MetaTask.
stiffness() [1/3]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::stiffness (double stiffness)
Set the task stiffness/damping.
Damping is automatically set to 2*sqrt(stiffness)
Parameters
stiffness Task stiffness
stiffness() [2/3]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::stiffness (const Eigen::VectorXd & stiffness)
Set dimensional stiffness.
The caller should be sure that the dimension of the vector fits the task dimension.
Damping is automatically set to 2*sqrt(stiffness)
Parameters
stiffness Dimensional stiffness
stiffness() [3/3]
template<typename T> double mc_tasks::TrajectoryTaskGeneric< T >::stiffness () const
Get the current task stiffness.
Referenced by mc_tasks::SurfaceTransformTask::stiffness().
weight() [1/2]
template<typename T> void mc_tasks::TrajectoryTaskGeneric< T >::weight (double w)
Set the task weight.
Parameters
w Task weight
weight() [2/2]
template<typename T> double mc_tasks::TrajectoryTaskGeneric< T >::weight () const
Returns the task weight.
Member Data Documentation
errorT
template<typename T> std::shared_ptr<T> mc_tasks::TrajectoryTaskGeneric< T >::errorT = nullptr protected
inSolver_
template<typename T> bool mc_tasks::TrajectoryTaskGeneric< T >::inSolver_ = false protected
refAccel_
template<typename T> Eigen::VectorXd mc_tasks::TrajectoryTaskGeneric< T >::refAccel_ protected
refVel_
template<typename T> Eigen::VectorXd mc_tasks::TrajectoryTaskGeneric< T >::refVel_ protected
rIndex
template<typename T> unsigned int mc_tasks::TrajectoryTaskGeneric< T >::rIndex protected
robots
template<typename T> const mc_rbdyn::Robots& mc_tasks::TrajectoryTaskGeneric< T >::robots protected
trajectoryT_
template<typename T> std::shared_ptr<tasks::qp::TrajectoryTask> mc_tasks::TrajectoryTaskGeneric< T >::trajectoryT_ = nullptr protected