mc_tasks::force::CoPTask Struct Reference
mc_tasks::force::CoPTask Struct Reference
Track center-of-pressure (CoP) references at contact.
#include <mc_tasks/CoPTask.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW CoPTask (const std::string &robotSurface, const mc_rbdyn::Robots &robots, unsigned robotIndex, double stiffness=5.0, double weight=1000.0)
Initialize a new CoP task.
void reset () override
Reset the task.
std::function< bool(const mc_tasks::MetaTask &, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add support for the following entries.
Eigen::Vector2d measuredCoP () const
Measured CoP in surface frame.
Eigen::Vector3d measuredCoPW () const
Measured CoP in world frame.
void setZeroTargetWrench ()
Set targent wrench to zero.
const Eigen::Vector2d & targetCoP () const
Get target CoP in the surface frame.
Eigen::Vector3d targetCoPW () const
Get target CoP in the world frame.
void targetCoP (const Eigen::Vector2d &targetCoP)
Set target CoP in the surface frame.
const Eigen::Vector3d & targetForce () const
Get target force in the surface frame.
void targetForce (const Eigen::Vector3d &targetForce)
Set target force in the surface frame.
void targetForceW (const Eigen::Vector3d &targetForceW)
Set target force in the world frame.
const sva::ForceVecd & targetWrench () const
Get target wrench in the surface frame.
Public Member Functions inherited from mc_tasks::force::DampingTask
EIGEN_MAKE_ALIGNED_OPERATOR_NEW DampingTask (const std::string &robotSurface, const mc_rbdyn::Robots &robots, unsigned robotIndex, double stiffness=5.0, double weight=1000.0)
Initialize a new admittance task.
Public Member Functions inherited from mc_tasks::force::AdmittanceTask
EIGEN_MAKE_ALIGNED_OPERATOR_NEW AdmittanceTask (const std::string &robotSurface, const mc_rbdyn::Robots &robots, unsigned robotIndex, double stiffness=5.0, double weight=1000.0)
Initialize a new admittance task.
const sva::ForceVecd & admittance () const
Get the admittance coefficients of the task.
void admittance (const sva::ForceVecd &admittance)
Set the admittance coefficients of the task.
sva::PTransformd surfacePose () const
Get the current pose of the robot surface in the inertial frame.
sva::PTransformd targetPose ()
Get the target pose of the surface in the world frame.
void targetPose (const sva::PTransformd &X_0_target)
Set target pose (position and orientation) of the surface in the world frame.
sva::PTransformd poseError ()
Transform from current surface pose to target.
const sva::ForceVecd & targetWrench () const
Get the target wrench in the surface frame.
void targetWrenchW (const sva::ForceVecd &wrenchW)
Set the target wrench in world frame. This function will convert the world wrench to surface frame, and call targetWrench()
void targetWrench (const sva::ForceVecd &wrench)
Set the target wrench in the surface frame.
sva::ForceVecd measuredWrench () const
Get the measured wrench in the surface frame.
void maxLinearVel (const Eigen::Vector3d &maxLinearVel)
Set the maximum translation velocity of the task.
void maxAngularVel (const Eigen::Vector3d &maxAngularVel)
Set the maximum angular velocity of the task.
void refVelB (const sva::MotionVecd &velB)
Set the reference body velocity.
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::SurfaceTransformTask
SurfaceTransformTask (const std::string &surfaceName, const mc_rbdyn::Robots &robots, unsigned int robotIndex, double stiffness=2.0, double weight=500)
Constructor.
sva::PTransformd target () const
Get the body Surface target.
void target (const sva::PTransformd &pos)
Set the body Surface target.
void targetSurface (unsigned int robotIndex, const std::string &surfaceName, const sva::PTransformd &offset)
Targets a robot surface with an optional offset.
const std::string & surface () const
Retrieve the controlled surface name.
const sva::PTransformd surfacePose () const
Returns the pose of the surface in the inertial frame.
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
void setGains (const sva::MotionVecd &stiffness, const sva::MotionVecd &damping)
Set dimensional stiffness and damping.
void stiffness (const sva::MotionVecd &stiffness)
Set dimensional stiffness.
sva::MotionVecd mvStiffness ()
Get dimensional stiffness as a motion vector.
void damping (const sva::MotionVecd &damping)
Set dimensional damping.
sva::MotionVecd mvDamping ()
Get dimensional damping as a motion vector.
void refVelB (const sva::MotionVecd &velB)
Set trajectory task's reference velocity from motion vector in body coordinates.
sva::MotionVecd refVelB () const
Get reference velocity in body coordinates as a motion vector.
void refAccel (const sva::MotionVecd &accel)
Set trajectory task's reference acceleration from motion vector.
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
TrajectoryTaskGeneric (const mc_rbdyn::Robots &robots, unsigned int robotIndex, double stiffness, double weight)
Constructor (auto damping)
virtual ~TrajectoryTaskGeneric ()
void refVel (const Eigen::VectorXd &vel)
Set the trajectory reference velocity.
const Eigen::VectorXd & refVel () const
Get the trajectory reference velocity.
void refAccel (const Eigen::VectorXd &accel)
Set the trajectory reference acceleration.
const Eigen::VectorXd & refAccel () const
Get the trajectory reference acceleration.
void stiffness (double stiffness)
Set the task stiffness/damping.
void stiffness (const Eigen::VectorXd &stiffness)
Set dimensional stiffness.
double stiffness () const
Get the current task stiffness.
void damping (double damping)
Set the task damping, leaving its stiffness unchanged.
void damping (const Eigen::VectorXd &damping)
Set dimensional damping.
double damping () const
Get the current task damping.
void setGains (double stiffness, double damping)
Set both stiffness and damping.
void setGains (const Eigen::VectorXd &stiffness, const Eigen::VectorXd &damping)
Set dimensional stiffness and damping.
const Eigen::VectorXd & dimStiffness () const
Get the current task dimensional stiffness.
const Eigen::VectorXd & dimDamping () const
Get the current task dimensional damping.
void weight (double w)
Set the task weight.
double weight () const
Returns the task weight.
virtual void dimWeight (const Eigen::VectorXd &dimW) override
Set the task's dimension weight vector.
virtual Eigen::VectorXd dimWeight () const override
Get the current task's dim weight vector.
virtual void selectActiveJoints (const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={})
virtual void selectActiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &activeJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &activeDofs={}) override
Setup an active joints selector.
virtual void selectUnactiveJoints (const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={})
virtual void selectUnactiveJoints (mc_solver::QPSolver &solver, const std::vector< std::string > &unactiveJointsName, const std::map< std::string, std::vector< std::array< int, 2 >>> &unactiveDofs={}) override
Setup an unactive joints selector.
virtual void resetJointsSelector ()
virtual void resetJointsSelector (mc_solver::QPSolver &solver) override
Reset active joints selection.
virtual Eigen::VectorXd eval () const override
Returns the task error.
virtual Eigen::VectorXd speed () const override
Returns the task velocity.
const Eigen::VectorXd & normalAcc () const
const Eigen::MatrixXd & jac () const
void load (mc_solver::QPSolver &solver, const mc_rtc::Configuration &config) override
Load parameters from a Configuration object.
Public Member Functions inherited from mc_tasks::MetaTask
virtual ~MetaTask ()
const std::string & type () const
Get the type of the task.
void name (const std::string &name)
Set a name for the task.
const std::string & name () const
Get the name of the task.
Protected Member Functions
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
void addToGUI (mc_rtc::gui::StateBuilder &gui) override
Add elements to the GUI through the helper.
Protected Member Functions inherited from mc_tasks::force::DampingTask
void update (mc_solver::QPSolver &) override
Update the task.
Protected Member Functions inherited from mc_tasks::force::AdmittanceTask
void addToSolver (mc_solver::QPSolver &solver) override
Override addToSolver in order to get the timestep's solver automatically.
Protected Member Functions inherited from mc_tasks::SurfaceTransformTask
void addToGUI (mc_rtc::gui::StateBuilder &gui) override
Add elements to the GUI through the helper.
Protected Member Functions inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
void finalize (Args &&... args)
void addToGUI (mc_rtc::gui::StateBuilder &) override
Add elements to the GUI through the helper.
void addToLogger (mc_rtc::Logger &logger) override
Add entries to the logger.
void removeFromLogger (mc_rtc::Logger &logger) override
Remove entries from the logger.
std::function< bool(const mc_tasks::MetaTask &task, std::string &)> buildCompletionCriteria (double dt, const mc_rtc::Configuration &config) const override
Add additional completion criterias to mc_control::CompletionCriteria object.
Protected Member Functions inherited from mc_tasks::MetaTask
virtual void removeFromGUI (mc_rtc::gui::StateBuilder &)
Remove elements from the GUI through the helper.
Additional Inherited Members
Public Types inherited from mc_tasks::SurfaceTransformTask
using TrajectoryBase = TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
Public Types inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
using TrajectoryBase = TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
Static Protected Member Functions inherited from mc_tasks::MetaTask
static void addToSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void removeFromSolver (MetaTask &t, mc_solver::QPSolver &solver)
static void update (MetaTask &t, mc_solver::QPSolver &solver)
static void addToLogger (MetaTask &t, mc_rtc::Logger &logger)
static void removeFromLogger (MetaTask &t, mc_rtc::Logger &logger)
static void addToGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
static void removeFromGUI (MetaTask &t, mc_rtc::gui::StateBuilder &gui)
Protected Attributes inherited from mc_tasks::force::AdmittanceTask
Eigen::Vector3d maxAngularVel_ = {0.1, 0.1, 0.1}
Eigen::Vector3d maxLinearVel_ = {0.1, 0.1, 0.1}
const mc_rbdyn::Robots & robots_
unsigned int rIndex_
double timestep_
const mc_rbdyn::Surface & surface_
sva::ForceVecd admittance_ = sva::ForceVecd(Eigen::Vector6d::Zero())
sva::ForceVecd targetWrench_ = sva::ForceVecd(Eigen::Vector6d::Zero())
sva::ForceVecd wrenchError_ = sva::ForceVecd(Eigen::Vector6d::Zero())
sva::MotionVecd feedforwardVelB_ = sva::MotionVecd(Eigen::Vector6d::Zero())
sva::MotionVecd refVelB_ = sva::MotionVecd(Eigen::Vector6d::Zero())
Protected Attributes inherited from mc_tasks::SurfaceTransformTask
std::string surfaceName
Protected Attributes inherited from mc_tasks::TrajectoryTaskGeneric< tasks::qp::SurfaceTransformTask >
const mc_rbdyn::Robots & robots
unsigned int rIndex
std::shared_ptr< tasks::qp::SurfaceTransformTask > errorT
Eigen::VectorXd refVel_
Eigen::VectorXd refAccel_
bool inSolver_
std::shared_ptr< tasks::qp::TrajectoryTask > trajectoryT_
Protected Attributes inherited from mc_tasks::MetaTask
std::string type_
std::string name_
Detailed Description
Track center-of-pressure (CoP) references at contact.
The CoPTask is basically an AdmittanceTask where contact wrenches are expressed in terms of center of pressure (a.k.a. ZMP, see e.g. [1]) rather than torques. This is better-suited to locomotion applications.
The CoP is well-defined only when the contact pressure is strictly positive. When there is no contact pressure, the CoPTask will automatically disable torque tracking in the underlying AdmittanceTask.
[1] https://scaron.info/teaching/zero-tilting-moment-point.html
Constructor & Destructor Documentation
CoPTask()
EIGEN_MAKE_ALIGNED_OPERATOR_NEW mc_tasks::force::CoPTask::CoPTask (const std::string & robotSurface, const mc_rbdyn::Robots & robots, unsigned robotIndex, double stiffness = 5.0, double weight = 1000.0)
Initialize a new CoP task.
Parameters
robotSurface Name of the surface frame to control, in which the desired wrench will also be expressed
robots Robots where the task will be applied
robotIndex Which robot among the robots
stiffness Stiffness of the underlying SurfaceTransform task
weight Weight of the underlying SurfaceTransform task
Exceptions
If the body the task is attempting to control does not have a sensor attached to it
Member Function Documentation
addToGUI()
void mc_tasks::force::CoPTask::addToGUI (mc_rtc::gui::StateBuilder &) override protected virtual
Add elements to the GUI through the helper.
This will be called by the solver when the task is added.
The default implementation adds the type of the task under the {"Tasks", name_} category.
Reimplemented from mc_tasks::force::AdmittanceTask.
addToLogger()
void mc_tasks::force::CoPTask::addToLogger (mc_rtc::Logger &) override protected virtual
Add entries to the logger.
This will be called by the solver if it holds a valid logger instance when the task is added.
The default implementation adds nothing to the log.
Reimplemented from mc_tasks::force::AdmittanceTask.
buildCompletionCriteria()
std::function<bool(const mc_tasks::MetaTask &, std::string &)> mc_tasks::force::CoPTask::buildCompletionCriteria (double dt, const mc_rtc::Configuration & config) const override virtual
Add support for the following entries.
copError Threshold for (targetCoP - measureCoP).norm()
force Force threshold, similar to wrench for AdmittanceTask
Reimplemented from mc_tasks::force::AdmittanceTask.
measuredCoP()
Eigen::Vector2d mc_tasks::force::CoPTask::measuredCoP () const inline
Measured CoP in surface frame.
measuredCoPW()
Eigen::Vector3d mc_tasks::force::CoPTask::measuredCoPW () const inline
Measured CoP in world frame.
removeFromLogger()
void mc_tasks::force::CoPTask::removeFromLogger (mc_rtc::Logger &) override protected virtual
Remove entries from the logger.
This will be called by the solver when the task is removed.
The default implementation removes nothing from the log.
Reimplemented from mc_tasks::force::AdmittanceTask.
reset()
void mc_tasks::force::CoPTask::reset () override virtual
Reset the task.
Set the end effector objective to the current position of the end-effector, disable CoP tracking and reset admittance and target CoP to zero.
Reimplemented from mc_tasks::force::AdmittanceTask.
setZeroTargetWrench()
void mc_tasks::force::CoPTask::setZeroTargetWrench () inline
Set targent wrench to zero.
References mc_tasks::force::AdmittanceTask::targetWrench().
targetCoP() [1/2]
const Eigen::Vector2d& mc_tasks::force::CoPTask::targetCoP () const inline
Get target CoP in the surface frame.
targetCoP() [2/2]
void mc_tasks::force::CoPTask::targetCoP (const Eigen::Vector2d & targetCoP) inline
Set target CoP in the surface frame.
Parameters
targetCoP 2D vector of CoP coordinates in the surface frame
targetCoPW()
Eigen::Vector3d mc_tasks::force::CoPTask::targetCoPW () const inline
Get target CoP in the world frame.
References sva::PTransform< T >::rotation(), and sva::PTransform< T >::translation().
targetForce() [1/2]
const Eigen::Vector3d& mc_tasks::force::CoPTask::targetForce () const inline
Get target force in the surface frame.
targetForce() [2/2]
void mc_tasks::force::CoPTask::targetForce (const Eigen::Vector3d & targetForce) inline
Set target force in the surface frame.
Parameters
targetForce 3D vector of target force in the surface frame
targetForceW()
void mc_tasks::force::CoPTask::targetForceW (const Eigen::Vector3d & targetForceW) inline
Set target force in the world frame.
Parameters
targetForce 3D vector of target force in the world frame
targetWrench()
const sva::ForceVecd& mc_tasks::force::CoPTask::targetWrench () const inline
Get target wrench in the surface frame.
References mc_tasks::force::AdmittanceTask::targetWrench(), and mc_tasks::force::AdmittanceTask::targetWrenchW().