#ifndef _IDL_MCCONTROLSERVICE_IDL_
#define _IDL_MCCONTROLSERVICE_IDL_

module OpenHRP
{

  interface MCControlService
  {
    boolean EnablePostureController();

    boolean EnableBody6dController();

    boolean EnableCoMController();

    boolean change_joint(in string jname);

    boolean joint_up();

    boolean joint_down();

    boolean set_joint_pos(in string jname, in double v);

    boolean change_ef(in string body);

    boolean translate_ef(in double x, in double y, in double z);

    boolean rotate_ef(in double r, in double p, in double y);

    boolean move_com(in double x, in double y, in double z);
  };

};

#endif
