#ifndef _IDL_MCCONTROLSERVICE_IDL_
#define _IDL_MCCONTROLSERVICE_IDL_

module OpenHRP
{

  interface MCControlService
  {
    boolean EnablePostureController();

    boolean change_joint(in string jname);

    boolean joint_up();

    boolean joint_down();

    boolean set_joint_pos(in string jname, in double v);
  };

};

#endif
