#ifndef _IDL_MCCONTROLSERVICE_IDL_
#define _IDL_MCCONTROLSERVICE_IDL_

module OpenHRP
{

  interface MCControlService
  {
    boolean EnableController(in string name);

    boolean open_grippers();

    boolean close_grippers();

    boolean set_gripper(in boolean lgripper, in double v);

    boolean set_joint_pos(in string jname, in double v);

    boolean get_joint_pos(in string jname, out double v);

    boolean change_ef(in string body);

    boolean translate_ef(in double x, in double y, in double z);

    boolean rotate_ef(in double r, in double p, in double y);

    boolean move_com(in double x, in double y, in double z);

    boolean play_next_stance();

    boolean driving_service(in double wheel, in double ankle, in double pan, in double tilt);

    boolean send_msg(in string msg);

    boolean send_recv_msg(in string msg, out string msg_out);
  };

};

#endif
