name: CI - Nix
on:
  push:
    branches:
      - devel
      - master
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .github/workflows/build.yml
      - .github/workflows/package.yml
      - .pre-commit-config.yaml
      - robots/README.md
      - utils/**/README.md
      - observers/**/README.md
      - controllers/**/README.md
      - binding/**/README.md
      - src/mc_rtc/README.md
  pull_request:
    branches:
      - devel
      - master
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/nix-build.yml
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
