name: Package mc-rtc

# This workflow only runs when pushing to master or pushing a tag
#
# On master, it will:
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact-head
#
# On tagged versions it will:
# - Create a GitHub release draft
# - Attach the sources to the release
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact
# - Finalize the release

on:
  repository_dispatch:
    types: [package-master, package-release]
  push:
    paths-ignore:
      # Changes to those files don't mandate rebuilding a package
      - ".gitlab-ci.yml"
      - ".jrl-ci"
      - "doc/**"
      - "README.md"
      - ".github/workflows/build.yml"
    branches:
      - master
    tags:
      - v*

jobs:
  # For a given tag vX.Y.Z, this checks:
  # - set(PROJECT_VERSION X.Y.Z) in CMakeLists.txt
  # - version X.Y.Z in debian/changelog
  # If these checks fail, the tag is automatically deleted
  #
  # This job does not run on the master branch
  check-tag:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      if: startsWith(github.ref, 'refs/tags/')
    - name: Check version coherency
      run: |
        set -x
        export VERSION=`echo ${{ github.ref }} | sed -e 's@refs/tags/v@@'`
        echo "::set-env name=REJECTION::PROJECT_VERSION in CMakeLists.txt does not match tag"
        grep -q "set(PROJECT_VERSION ${VERSION})" CMakeLists.txt
        echo "::set-env name=REJECTION::Upstream version in debian/changelog does not match tag"
        head -n 1 debian/changelog | grep -q "mc-rtc (${VERSION}"
        echo "::set-env name=REJECTION::"
        export TAG=`echo ${{ github.ref }} | sed -e 's@refs/tags/@@'`
        echo "::set-env name=RELEASE_TAG::${TAG}"
      if: startsWith(github.ref, 'refs/tags/')
    - name: Delete tag
      run: |
        set -x
        curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/${{ github.repository }}/git/${{ github.ref }}
      if: failure()
    - name: Notify tag deletion
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          Tag *${{ github.ref }}* in *${{ github.repository }}* was deleted:
            ${{ env.REJECTION}}
      if: failure()
    - name: Create release
      uses: jrl-umi3218/github-actions/create-release@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
      if: startsWith(github.ref, 'refs/tags/')
  # This job build binary packages for Ubuntu
  build-packages:
    needs: check-tag
    strategy:
      fail-fast: true
      matrix:
        dist: [xenial, bionic, focal]
        arch: [i386, amd64]
        exclude:
          - dist: focal
            arch: i386
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup environment
      run: |
        set -x
        if [ "${{ github.event.action }}" == "package-master" ]
        then
          export REF=master
        elif [ "${{ github.event.action }}" == "package-release" ]
        then
          export REF=`git tag --sort=committerdate --list 'v[0-9]*'|tail -1`
          git checkout $REF
          git submodule sync && git submodule update
        else
          export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        fi
        if [ $REF == "master" ]
        then
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-head"
        else
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-release"
        fi
        export PACKAGES_OUT=/tmp/packages-${{ matrix.dist }}-${{ matrix.arch }}
        export ROS_DISTRO=""
        if [ "${{ matrix.dist }}" = "xenial" ]
        then
          export ROS_DISTRO="kinetic"
          export PACKAGES_OUT=${PACKAGES_OUT}-${ROS_DISTRO}
        fi
        if [ "${{ matrix.dist }}" = "bionic" -a "${{ matrix.arch }}" = "amd64" ]
        then
          export ROS_DISTRO="melodic"
          export PACKAGES_OUT=${PACKAGES_OUT}-${ROS_DISTRO}
        fi
        echo "::set-env name=ROS_DISTRO::${ROS_DISTRO}"
        echo "::set-env name=PACKAGES_OUT::${PACKAGES_OUT}"
        if [ "${ROS_DISTRO}" != "" ]
        then
          sed -e"s/@ROS_DISTRO@/${ROS_DISTRO}/" debian/control.ros | tee -a debian/control
          sed -i -e"s/# ros-@ROS_DISTRO@/ ros-${ROS_DISTRO}/" debian/control
          cat debian/control
          sed -i -e"s/@ROS_DISTRO@/${ROS_DISTRO}/" debian/rules
          sed -i -e"s/#export/export/" debian/rules
          cat debian/rules
          cp debian/ros-ROS_DISTRO-mc-rtc-plugin.install debian/ros-${ROS_DISTRO}-mc-rtc-plugin.install
        fi
    - name: Build package
      uses: jrl-umi3218/github-actions/build-package-native@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        ros-distro: ${{ env.ROS_DISTRO }}
        other-mirrors: ${{ env.EXTRA_MIRROR }}
        other-gpg-keys: "0x892EA6EE273707C6495A6FB6220D644C64666806"
    - uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
        path: ${{ env.PACKAGES_OUT }}
  # This job upload binary packages for Ubuntu
  upload-packages:
    needs: build-packages
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        dist: [xenial, bionic, focal]
        arch: [i386, amd64]
        exclude:
          - dist: focal
            arch: i386
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set upload parameters
      run: |
        if [ "${{ github.event.action }}" == "package-master" ]
        then
          export REF=master
        elif [ "${{ github.event.action }}" == "package-release" ]
        then
          export REF=`git tag --sort=committerdate --list 'v[0-9]*'|tail -1`
          git checkout $REF
          git submodule sync && git submodule update
        else
          export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        fi
        if [ $REF == "master" ]
        then
          echo "::set-env name=BINTRAY_REPO::multi-contact-head"
          echo "::set-env name=BINTRAY_VERSION::HEAD"
        else
          echo "::set-env name=BINTRAY_REPO::multi-contact-release"
          echo "::set-env name=BINTRAY_VERSION::${REF}"
        fi
    - name: Download packages
      uses: actions/download-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
    - name: Upload
      uses: jrl-umi3218/github-actions/upload-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        subject: gergondet
        repo: ${{ env.BINTRAY_REPO }}
        package: |
          name: mc-rtc
          desc: "mc_rtc is an interface for simulated and real robotic systems suitable for real-time control.  It provides programmers with a simple interface to build versatile controllers as well as a set of tools to help with the development of said controllers."
          licenses: [BSD 2-Clause]
          vcs_url: https://github.com/jrl-umi3218/Tasks
        version: ${{ env.BINTRAY_VERSION }}
        path: packages-${{ matrix.dist }}-${{ matrix.arch }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  # This job force a mirror sync
  mirror-sync:
    needs: upload-packages
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set repository parameters
      run: |
        if [ "${{ github.event.action }}" == "package-master" ]
        then
          export REF=master
        elif [ "${{ github.event.action }}" == "package-release" ]
        then
          export REF=`git tag --sort=committerdate --list 'v[0-9]*'|tail -1`
          git checkout $REF
          git submodule sync && git submodule update
        else
          export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        fi
        if [ $REF == "master" ]
        then
          echo "::set-env name=BINTRAY_REPO::multi-contact-head"
          echo "::set-env name=PACKAGE_JOB::package-master"
        else
          echo "::set-env name=BINTRAY_REPO::multi-contact-release"
          echo "::set-env name=PACKAGE_JOB::package-release"
        fi
    - name: Request mirror sync
      run: |
        curl -ugergondet:${{ secrets.BINTRAY_API_KEY }} --header "X-GPG-PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}" -X POST https://api.bintray.com/calc_metadata/gergondet/${{ env.BINTRAY_REPO }}
    - name: Trigger dependents rebuild
      run: |
        curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.GH_PAGES_TOKEN }}" --request POST --data "{\"event_type\": \"${PACKAGE_JOB}\"}" https://api.github.com/repos/jrl-umi3218/mc_rtc_ros/dispatches
        curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.GH_PAGES_TOKEN }}" --request POST --data "{\"event_type\": \"${PACKAGE_JOB}\"}" https://api.github.com/repos/jrl-umi3218/mc_openrtm/dispatches
